import { sqliteTable, text, integer, foreignKey, uniqueIndex, index, check } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import { tenants, bookSets, gstRegistrations } from "./foundation-schema";

const scoped = (table: any) => foreignKey({ columns: [table.bookSetId, table.tenantId], foreignColumns: [bookSets.id, bookSets.tenantId] });

export const complianceFactProfiles = sqliteTable("compliance_fact_profiles", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), gstRegistrationId: text("gst_registration_id"),
  effectiveFrom: text("effective_from").notNull(), effectiveTo: text("effective_to"), factsJson: text("facts_json").notNull(), sourceUrl: text("source_url").notNull(), evidenceReference: text("evidence_reference").notNull(), verificationStatus: text("verification_status").notNull(), canonicalHash: text("canonical_hash").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({
  fkTenant: foreignKey({ columns: [t.tenantId], foreignColumns: [tenants.id] }), fkScope: scoped(t), fkRegistration: foreignKey({ columns: [t.gstRegistrationId, t.tenantId], foreignColumns: [gstRegistrations.id, gstRegistrations.tenantId] }),
  uqScope: uniqueIndex("uq_compliance_fact_profiles_scope_key").on(t.id, t.tenantId, t.bookSetId), idxEffective: index("idx_compliance_fact_profiles_effective").on(t.tenantId, t.bookSetId, t.gstRegistrationId, t.effectiveFrom, t.id),
  chkStatus: check("chk_compliance_fact_profile_status", sql`${t.verificationStatus} IN ('UNVERIFIED', 'VERIFIED', 'REJECTED')`), chkDates: check("chk_compliance_fact_profile_dates", sql`${t.effectiveTo} IS NULL OR ${t.effectiveFrom} <= ${t.effectiveTo}`), chkSource: check("chk_compliance_fact_profile_source", sql`${t.sourceUrl} GLOB 'https://*' AND length(trim(${t.evidenceReference})) > 0`), chkHash: check("chk_compliance_fact_profile_hash", sql`length(${t.canonicalHash}) = 64 AND ${t.canonicalHash} NOT GLOB '*[^0-9a-f]*'`),
}));

export const complianceRuleSnapshots = sqliteTable("compliance_rule_snapshots", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), code: text("code").notNull(), version: text("version").notNull(), jurisdiction: text("jurisdiction").notNull(), authority: text("authority").notNull(), formLabel: text("form_label").notNull(), effectiveFrom: text("effective_from").notNull(), effectiveTo: text("effective_to"), officialSourceUrl: text("official_source_url").notNull(), lawReference: text("law_reference").notNull(), sourceVersion: text("source_version").notNull(), sourceHash: text("source_hash").notNull(), evidenceReference: text("evidence_reference").notNull(), verificationStatus: text("verification_status").notNull(), requiredFactKeysJson: text("required_fact_keys_json").notNull(), applicabilityPredicateJson: text("applicability_predicate_json").notNull(), canonicalHash: text("canonical_hash").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({
  fkTenant: foreignKey({ columns: [t.tenantId], foreignColumns: [tenants.id] }), fkScope: scoped(t), uqCodeVersion: uniqueIndex("uq_compliance_rule_code_version").on(t.tenantId, t.bookSetId, t.code, t.version), uqScope: uniqueIndex("uq_compliance_rule_snapshots_scope_key").on(t.id, t.tenantId, t.bookSetId), idxEffective: index("idx_compliance_rule_snapshots_effective").on(t.tenantId, t.bookSetId, t.code, t.effectiveFrom, t.id),
  chkStatus: check("chk_compliance_rule_status", sql`${t.verificationStatus} IN ('UNVERIFIED', 'VERIFIED', 'REJECTED')`), chkDates: check("chk_compliance_rule_dates", sql`${t.effectiveTo} IS NULL OR ${t.effectiveFrom} <= ${t.effectiveTo}`), chkSource: check("chk_compliance_rule_source", sql`${t.officialSourceUrl} GLOB 'https://*' AND length(trim(${t.lawReference})) > 0 AND length(trim(${t.sourceVersion})) > 0 AND length(trim(${t.evidenceReference})) > 0`), chkHash: check("chk_compliance_rule_hash", sql`length(${t.sourceHash}) = 64 AND length(${t.canonicalHash}) = 64 AND ${t.sourceHash} NOT GLOB '*[^0-9a-f]*' AND ${t.canonicalHash} NOT GLOB '*[^0-9a-f]*'`),
}));

export const complianceDeadlineSnapshots = sqliteTable("compliance_deadline_snapshots", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), ruleId: text("rule_id").notNull(), periodStart: text("period_start").notNull(), periodEnd: text("period_end").notNull(), dueDate: text("due_date").notNull(), sourceUrl: text("source_url").notNull(), evidenceReference: text("evidence_reference").notNull(), sourceHash: text("source_hash").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({
  fkScope: scoped(t), fkRule: foreignKey({ columns: [t.ruleId, t.tenantId, t.bookSetId], foreignColumns: [complianceRuleSnapshots.id, complianceRuleSnapshots.tenantId, complianceRuleSnapshots.bookSetId] }), uqPeriod: uniqueIndex("uq_compliance_deadline_rule_period").on(t.ruleId, t.tenantId, t.bookSetId, t.periodStart, t.periodEnd), uqScope: uniqueIndex("uq_compliance_deadline_scope_key").on(t.id, t.tenantId, t.bookSetId), idxCalendar: index("idx_compliance_deadline_calendar").on(t.tenantId, t.bookSetId, t.dueDate, t.periodStart, t.ruleId), chkOrder: check("chk_compliance_deadline_period_order", sql`${t.periodStart} <= ${t.periodEnd} AND ${t.periodStart} <= ${t.dueDate}`), chkSource: check("chk_compliance_deadline_source", sql`${t.sourceUrl} GLOB 'https://*' AND length(trim(${t.evidenceReference})) > 0`), chkHash: check("chk_compliance_deadline_hash", sql`length(${t.sourceHash}) = 64 AND ${t.sourceHash} NOT GLOB '*[^0-9a-f]*'`),
}));

export const complianceApplicabilityDecisions = sqliteTable("compliance_applicability_decisions", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), ruleId: text("rule_id").notNull(), factProfileId: text("fact_profile_id").notNull(), decision: text("decision").notNull(), missingKeysJson: text("missing_keys_json").notNull(), inputHash: text("input_hash").notNull(), reasoningCodesJson: text("reasoning_codes_json").notNull(), evaluatedAt: text("evaluated_at").notNull(),
}, (t) => ({
  fkScope: scoped(t), fkRule: foreignKey({ columns: [t.ruleId, t.tenantId, t.bookSetId], foreignColumns: [complianceRuleSnapshots.id, complianceRuleSnapshots.tenantId, complianceRuleSnapshots.bookSetId] }), fkFacts: foreignKey({ columns: [t.factProfileId, t.tenantId, t.bookSetId], foreignColumns: [complianceFactProfiles.id, complianceFactProfiles.tenantId, complianceFactProfiles.bookSetId] }), uqInput: uniqueIndex("uq_compliance_applicability_input").on(t.ruleId, t.factProfileId, t.tenantId, t.bookSetId), uqScope: uniqueIndex("uq_compliance_applicability_scope_key").on(t.id, t.tenantId, t.bookSetId), idxDecision: index("idx_compliance_applicability_decision").on(t.tenantId, t.bookSetId, t.decision, t.ruleId), chkDecision: check("chk_compliance_applicability_decision", sql`${t.decision} IN ('APPLIES', 'DOES_NOT_APPLY', 'UNKNOWN')`), chkHash: check("chk_compliance_applicability_hash", sql`length(${t.inputHash}) = 64 AND ${t.inputHash} NOT GLOB '*[^0-9a-f]*'`),
}));

export const complianceRulePredecessors = sqliteTable("compliance_rule_predecessors", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), ruleId: text("rule_id").notNull(), predecessorRuleId: text("predecessor_rule_id").notNull(), requiredStatus: text("required_status").notNull(), sourceUrl: text("source_url").notNull(), evidenceReference: text("evidence_reference").notNull(), sourceHash: text("source_hash").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({
  fkScope: scoped(t), fkRule: foreignKey({ columns: [t.ruleId, t.tenantId, t.bookSetId], foreignColumns: [complianceRuleSnapshots.id, complianceRuleSnapshots.tenantId, complianceRuleSnapshots.bookSetId] }), fkPredecessor: foreignKey({ columns: [t.predecessorRuleId, t.tenantId, t.bookSetId], foreignColumns: [complianceRuleSnapshots.id, complianceRuleSnapshots.tenantId, complianceRuleSnapshots.bookSetId] }), uqRelationship: uniqueIndex("uq_compliance_rule_predecessor").on(t.ruleId, t.predecessorRuleId, t.requiredStatus, t.tenantId, t.bookSetId), idxRule: index("idx_compliance_rule_predecessor_rule").on(t.tenantId, t.bookSetId, t.ruleId), chkStatus: check("chk_compliance_rule_predecessor_status", sql`${t.requiredStatus} IN ('OPEN', 'READY', 'EXPORTED', 'USER_MARKED_SUBMITTED', 'ACKNOWLEDGED', 'CLOSED')`), chkSource: check("chk_compliance_rule_predecessor_source", sql`${t.sourceUrl} GLOB 'https://*' AND length(trim(${t.evidenceReference})) > 0`), chkHash: check("chk_compliance_rule_predecessor_hash", sql`length(${t.sourceHash}) = 64 AND ${t.sourceHash} NOT GLOB '*[^0-9a-f]*'`),
}));

export const complianceObligations = sqliteTable("compliance_obligations", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), gstRegistrationId: text("gst_registration_id"), ruleId: text("rule_id").notNull(), deadlineId: text("deadline_id").notNull(), factProfileId: text("fact_profile_id").notNull(), applicabilityDecisionId: text("applicability_decision_id").notNull(), periodStart: text("period_start").notNull(), periodEnd: text("period_end").notNull(), dueDate: text("due_date").notNull(), createdAt: text("created_at").notNull(), createdByActorId: text("created_by_actor_id").notNull(),
}, (t) => ({
  fkScope: scoped(t), fkRegistration: foreignKey({ columns: [t.gstRegistrationId, t.tenantId], foreignColumns: [gstRegistrations.id, gstRegistrations.tenantId] }), fkRule: foreignKey({ columns: [t.ruleId, t.tenantId, t.bookSetId], foreignColumns: [complianceRuleSnapshots.id, complianceRuleSnapshots.tenantId, complianceRuleSnapshots.bookSetId] }), fkDeadline: foreignKey({ columns: [t.deadlineId, t.tenantId, t.bookSetId], foreignColumns: [complianceDeadlineSnapshots.id, complianceDeadlineSnapshots.tenantId, complianceDeadlineSnapshots.bookSetId] }), fkFacts: foreignKey({ columns: [t.factProfileId, t.tenantId, t.bookSetId], foreignColumns: [complianceFactProfiles.id, complianceFactProfiles.tenantId, complianceFactProfiles.bookSetId] }), fkDecision: foreignKey({ columns: [t.applicabilityDecisionId, t.tenantId, t.bookSetId], foreignColumns: [complianceApplicabilityDecisions.id, complianceApplicabilityDecisions.tenantId, complianceApplicabilityDecisions.bookSetId] }), uqIdentity: uniqueIndex("uq_compliance_obligation_identity").on(t.tenantId, t.bookSetId, t.gstRegistrationId, t.ruleId, t.periodStart, t.periodEnd), uqScope: uniqueIndex("uq_compliance_obligation_scope_key").on(t.id, t.tenantId, t.bookSetId), idxDue: index("idx_compliance_obligation_due").on(t.tenantId, t.bookSetId, t.dueDate, t.ruleId), chkDates: check("chk_compliance_obligation_dates", sql`${t.periodStart} <= ${t.periodEnd} AND ${t.periodStart} <= ${t.dueDate}`),
}));

export const complianceObligationArtifacts = sqliteTable("compliance_obligation_artifacts", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), obligationId: text("obligation_id").notNull(), artifactKind: text("artifact_kind").notNull(), artifactHash: text("artifact_hash").notNull(), artifactReference: text("artifact_reference").notNull(), metadataJson: text("metadata_json").notNull(), attachedAt: text("attached_at").notNull(), attachedByActorId: text("attached_by_actor_id").notNull(),
}, (t) => ({
  fkScope: scoped(t), fkObligation: foreignKey({ columns: [t.obligationId, t.tenantId, t.bookSetId], foreignColumns: [complianceObligations.id, complianceObligations.tenantId, complianceObligations.bookSetId] }), uqArtifact: uniqueIndex("uq_compliance_obligation_artifact").on(t.obligationId, t.artifactKind, t.artifactHash, t.tenantId, t.bookSetId), uqScope: uniqueIndex("uq_compliance_artifact_scope_key").on(t.id, t.tenantId, t.bookSetId), idxObligation: index("idx_compliance_artifact_obligation").on(t.tenantId, t.bookSetId, t.obligationId), chkHash: check("chk_compliance_artifact_hash", sql`length(${t.artifactHash}) = 64 AND ${t.artifactHash} NOT GLOB '*[^0-9a-f]*'`),
}));

export const complianceObligationEvents = sqliteTable("compliance_obligation_events", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), obligationId: text("obligation_id").notNull(), eventType: text("event_type").notNull(), occurredAt: text("occurred_at").notNull(), actorId: text("actor_id").notNull(), reason: text("reason").notNull(), source: text("source").notNull(), evidenceReference: text("evidence_reference"), artifactId: text("artifact_id"), resultHash: text("result_hash").notNull(),
}, (t) => ({
  fkScope: scoped(t), fkObligation: foreignKey({ columns: [t.obligationId, t.tenantId, t.bookSetId], foreignColumns: [complianceObligations.id, complianceObligations.tenantId, complianceObligations.bookSetId] }), fkArtifact: foreignKey({ columns: [t.artifactId, t.tenantId, t.bookSetId], foreignColumns: [complianceObligationArtifacts.id, complianceObligationArtifacts.tenantId, complianceObligationArtifacts.bookSetId] }), uqScope: uniqueIndex("uq_compliance_event_scope_key").on(t.id, t.tenantId, t.bookSetId), idxTimeline: index("idx_compliance_event_timeline").on(t.tenantId, t.bookSetId, t.obligationId, t.occurredAt, t.id), chkEvent: check("chk_compliance_event_type", sql`${t.eventType} IN ('OPEN', 'READY', 'EXPORTED', 'USER_MARKED_SUBMITTED', 'ACKNOWLEDGED', 'CLOSED', 'REJECTED', 'WAIVED', 'EXEMPT')`), chkHash: check("chk_compliance_event_hash", sql`length(${t.resultHash}) = 64 AND ${t.resultHash} NOT GLOB '*[^0-9a-f]*'`), chkEvidence: check("chk_compliance_event_evidence", sql`(${t.eventType} IN ('USER_MARKED_SUBMITTED', 'ACKNOWLEDGED', 'WAIVED', 'EXEMPT') AND length(trim(COALESCE(${t.evidenceReference}, ''))) > 0) OR ${t.eventType} NOT IN ('USER_MARKED_SUBMITTED', 'ACKNOWLEDGED', 'WAIVED', 'EXEMPT')`),
}));
