import { sqliteTable, text, integer, foreignKey, uniqueIndex, index, check } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import { tenants, bookSets, accounts } from "./foundation-schema";

/** Separate append-only facts keep the ledger and existing local-currency API unchanged. */
export const tenantCurrencies = sqliteTable("tenant_currencies", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), currencyCode: text("currency_code").notNull(), exponent: integer("exponent").notNull(), isBase: integer("is_base").notNull().default(0), createdAt: text("created_at").notNull(),
}, (t) => ({
  fkTenant: foreignKey({ columns: [t.tenantId], foreignColumns: [tenants.id] }), uqCode: uniqueIndex("uq_tenant_currencies_code").on(t.tenantId, t.currencyCode),
  chkCode: check("chk_tenant_currency_code", sql`length(${t.currencyCode}) = 3 AND ${t.currencyCode} NOT GLOB '*[^A-Z]*'`), chkExponent: check("chk_tenant_currency_exponent", sql`${t.exponent} BETWEEN 0 AND 6`), chkBase: check("chk_tenant_currency_base", sql`${t.isBase} IN (0, 1)`),
}));

export const fxRateSnapshots = sqliteTable("fx_rate_snapshots", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), baseCurrencyCode: text("base_currency_code").notNull(), baseExponent: integer("base_exponent").notNull(), foreignCurrencyCode: text("foreign_currency_code").notNull(), foreignExponent: integer("foreign_exponent").notNull(), rateDecimal: text("rate_decimal").notNull(), numerator: text("numerator").notNull(), scale: integer("scale").notNull(), source: text("source").notNull(), purpose: text("purpose").notNull(), effectiveDate: text("effective_date").notNull(), effectiveAt: text("effective_at").notNull(), verified: integer("verified").notNull(), evidenceJson: text("evidence_json").notNull(), canonicalHash: text("canonical_hash").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({
  fkBookSet: foreignKey({ columns: [t.bookSetId, t.tenantId], foreignColumns: [bookSets.id, bookSets.tenantId] }), uqScope: uniqueIndex("uq_fx_rate_snapshots_scope").on(t.id, t.tenantId, t.bookSetId), uqHash: uniqueIndex("uq_fx_rate_snapshot_hash").on(t.tenantId, t.bookSetId, t.canonicalHash), idxPurpose: index("idx_fx_rate_snapshots_purpose").on(t.tenantId, t.bookSetId, t.foreignCurrencyCode, t.purpose, t.effectiveDate),
  chkCodes: check("chk_fx_rate_snapshot_codes", sql`length(${t.baseCurrencyCode}) = 3 AND ${t.baseCurrencyCode} NOT GLOB '*[^A-Z]*' AND length(${t.foreignCurrencyCode}) = 3 AND ${t.foreignCurrencyCode} NOT GLOB '*[^A-Z]*'`), chkBaseExponent: check("chk_fx_rate_snapshot_base_exponent", sql`${t.baseExponent} BETWEEN 0 AND 6`), chkExponent: check("chk_fx_rate_snapshot_exponent", sql`${t.foreignExponent} BETWEEN 0 AND 6`), chkDecimal: check("chk_fx_rate_snapshot_decimal", sql`length(trim(${t.rateDecimal})) > 0 AND ${t.rateDecimal} NOT GLOB '*[^0-9.]*'`), chkScale: check("chk_fx_rate_snapshot_scale", sql`${t.scale} BETWEEN 0 AND 18`), chkPurpose: check("chk_fx_rate_snapshot_purpose", sql`${t.purpose} IN ('BOOK_INITIAL', 'SETTLEMENT', 'PERIOD_END')`), chkVerified: check("chk_fx_rate_snapshot_verified", sql`${t.verified} IN (0, 1)`), chkHash: check("chk_fx_rate_snapshot_hash", sql`length(${t.canonicalHash}) = 64 AND ${t.canonicalHash} NOT GLOB '*[^0-9a-f]*'`),
}));

export const fxDocumentFacts = sqliteTable("fx_document_facts", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), documentType: text("document_type").notNull(), documentId: text("document_id").notNull(), currencyCode: text("currency_code").notNull(), exponent: integer("exponent").notNull(), baseExponent: integer("base_exponent").notNull(), rateSnapshotId: text("rate_snapshot_id").notNull(), roundingPolicy: text("rounding_policy").notNull(), totalForeignMinor: integer("total_foreign_minor").notNull(), totalBaseMinor: integer("total_base_minor").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({
  fkBookSet: foreignKey({ columns: [t.bookSetId, t.tenantId], foreignColumns: [bookSets.id, bookSets.tenantId] }), fkRate: foreignKey({ columns: [t.rateSnapshotId, t.tenantId, t.bookSetId], foreignColumns: [fxRateSnapshots.id, fxRateSnapshots.tenantId, fxRateSnapshots.bookSetId] }), uqDocument: uniqueIndex("uq_fx_document_facts_document").on(t.tenantId, t.bookSetId, t.documentType, t.documentId), idxCurrency: index("idx_fx_document_facts_currency").on(t.tenantId, t.bookSetId, t.currencyCode, t.documentType, t.documentId), chkType: check("chk_fx_document_facts_type", sql`${t.documentType} IN ('SALES_INVOICE', 'VENDOR_BILL')`), chkExponent: check("chk_fx_document_facts_exponent", sql`${t.exponent} BETWEEN 0 AND 6`), chkBaseExponent: check("chk_fx_document_facts_base_exponent", sql`${t.baseExponent} BETWEEN 0 AND 6`), chkRounding: check("chk_fx_document_facts_rounding", sql`${t.roundingPolicy} IN ('HALF_UP', 'HALF_EVEN', 'FLOOR', 'CEILING')`), chkAmounts: check("chk_fx_document_facts_amounts", sql`${t.totalForeignMinor} > 0 AND ${t.totalBaseMinor} > 0`),
}));

export const fxDocumentLineAmounts = sqliteTable("fx_document_line_amounts", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), documentType: text("document_type").notNull(), documentId: text("document_id").notNull(), lineId: text("line_id").notNull(), lineNumber: integer("line_number").notNull(), foreignMinor: integer("foreign_minor").notNull(), baseMinor: integer("base_minor").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({
  fkBookSet: foreignKey({ columns: [t.bookSetId, t.tenantId], foreignColumns: [bookSets.id, bookSets.tenantId] }), uqLine: uniqueIndex("uq_fx_document_line_amounts_line").on(t.tenantId, t.bookSetId, t.documentType, t.documentId, t.lineNumber), idxDocument: index("idx_fx_document_line_amounts_document").on(t.tenantId, t.bookSetId, t.documentId, t.lineNumber), chkType: check("chk_fx_document_line_amounts_type", sql`${t.documentType} IN ('SALES_INVOICE', 'VENDOR_BILL')`), chkAmounts: check("chk_fx_document_line_amounts_amounts", sql`${t.foreignMinor} > 0 AND ${t.baseMinor} > 0`),
}));

export const fxAllocationFacts = sqliteTable("fx_allocation_facts", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), allocationType: text("allocation_type").notNull(), allocationId: text("allocation_id").notNull(), documentType: text("document_type").notNull(), documentId: text("document_id").notNull(), foreignMinor: integer("foreign_minor").notNull(), carryingBaseMinor: integer("carrying_base_minor").notNull(), actualBankBaseMinor: integer("actual_bank_base_minor").notNull(), baseExponent: integer("base_exponent").notNull(), rateSnapshotId: text("rate_snapshot_id").notNull(), realizedGainLossMinor: integer("realized_gain_loss_minor").notNull(), gainLossAccountId: text("gain_loss_account_id").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({
  fkBookSet: foreignKey({ columns: [t.bookSetId, t.tenantId], foreignColumns: [bookSets.id, bookSets.tenantId] }), fkRate: foreignKey({ columns: [t.rateSnapshotId, t.tenantId, t.bookSetId], foreignColumns: [fxRateSnapshots.id, fxRateSnapshots.tenantId, fxRateSnapshots.bookSetId] }), fkGainLoss: foreignKey({ columns: [t.gainLossAccountId, t.tenantId, t.bookSetId], foreignColumns: [accounts.id, accounts.tenantId, accounts.bookSetId] }), uqAllocation: uniqueIndex("uq_fx_allocation_facts_allocation").on(t.tenantId, t.bookSetId, t.allocationType, t.allocationId), idxDocument: index("idx_fx_allocation_facts_document").on(t.tenantId, t.bookSetId, t.documentType, t.documentId, t.createdAt), chkType: check("chk_fx_allocation_facts_type", sql`${t.allocationType} IN ('RECEIPT', 'VENDOR_PAYMENT')`), chkDocument: check("chk_fx_allocation_facts_document", sql`${t.documentType} IN ('SALES_INVOICE', 'VENDOR_BILL')`), chkBaseExponent: check("chk_fx_allocation_facts_base_exponent", sql`${t.baseExponent} BETWEEN 0 AND 6`), chkAmounts: check("chk_fx_allocation_facts_amounts", sql`${t.foreignMinor} > 0 AND ${t.carryingBaseMinor} > 0 AND ${t.actualBankBaseMinor} > 0`),
}));

export const fxRevaluationPolicies = sqliteTable("fx_revaluation_policies", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), policyCode: text("policy_code").notNull(), unrealizedGainLossAccountId: text("unrealized_gain_loss_account_id").notNull(), arAdjustmentAccountId: text("ar_adjustment_account_id").notNull(), apAdjustmentAccountId: text("ap_adjustment_account_id").notNull(), canonicalHash: text("canonical_hash").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({
  fkBookSet: foreignKey({ columns: [t.bookSetId, t.tenantId], foreignColumns: [bookSets.id, bookSets.tenantId] }), fkGainLoss: foreignKey({ columns: [t.unrealizedGainLossAccountId, t.tenantId, t.bookSetId], foreignColumns: [accounts.id, accounts.tenantId, accounts.bookSetId] }), fkAr: foreignKey({ columns: [t.arAdjustmentAccountId, t.tenantId, t.bookSetId], foreignColumns: [accounts.id, accounts.tenantId, accounts.bookSetId] }), fkAp: foreignKey({ columns: [t.apAdjustmentAccountId, t.tenantId, t.bookSetId], foreignColumns: [accounts.id, accounts.tenantId, accounts.bookSetId] }), uqScope: uniqueIndex("uq_fx_revaluation_policies_scope").on(t.id, t.tenantId, t.bookSetId), uqPolicy: uniqueIndex("uq_fx_revaluation_policies_scope_hash").on(t.tenantId, t.bookSetId, t.canonicalHash), chkPolicy: check("chk_fx_revaluation_policy_code", sql`${t.policyCode} IN ('AS_11', 'IND_AS_21', 'CUSTOM_SUPPORTED')`),
}));

export const fxRevaluationRuns = sqliteTable("fx_revaluation_runs", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), policyId: text("policy_id").notNull(), asOfDate: text("as_of_date").notNull(), status: text("status").notNull(), journalId: text("journal_id"), createdAt: text("created_at").notNull(),
}, (t) => ({ fkBookSet: foreignKey({ columns: [t.bookSetId, t.tenantId], foreignColumns: [bookSets.id, bookSets.tenantId] }), fkPolicy: foreignKey({ columns: [t.policyId, t.tenantId, t.bookSetId], foreignColumns: [fxRevaluationPolicies.id, fxRevaluationPolicies.tenantId, fxRevaluationPolicies.bookSetId] }), uqScope: uniqueIndex("uq_fx_revaluation_runs_scope").on(t.id, t.tenantId, t.bookSetId), uqRun: uniqueIndex("uq_fx_revaluation_runs_scope_date_policy").on(t.tenantId, t.bookSetId, t.asOfDate, t.policyId), chkStatus: check("chk_fx_revaluation_run_status", sql`${t.status} IN ('PREVIEW', 'POSTED', 'REVERSED')`) }));

export const fxRevaluationLines = sqliteTable("fx_revaluation_lines", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), runId: text("run_id").notNull(), documentType: text("document_type").notNull(), documentId: text("document_id").notNull(), currencyCode: text("currency_code").notNull(), foreignOpenMinor: integer("foreign_open_minor").notNull(), carryingBaseMinor: integer("carrying_base_minor").notNull(), revaluedBaseMinor: integer("revalued_base_minor").notNull(), adjustmentMinor: integer("adjustment_minor").notNull(), baseExponent: integer("base_exponent").notNull(), rateSnapshotId: text("rate_snapshot_id").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({ fkRun: foreignKey({ columns: [t.runId, t.tenantId, t.bookSetId], foreignColumns: [fxRevaluationRuns.id, fxRevaluationRuns.tenantId, fxRevaluationRuns.bookSetId] }), fkRate: foreignKey({ columns: [t.rateSnapshotId, t.tenantId, t.bookSetId], foreignColumns: [fxRateSnapshots.id, fxRateSnapshots.tenantId, fxRateSnapshots.bookSetId] }), uqDocument: uniqueIndex("uq_fx_revaluation_lines_run_document").on(t.runId, t.documentType, t.documentId), chkDocument: check("chk_fx_revaluation_lines_document", sql`${t.documentType} IN ('SALES_INVOICE', 'VENDOR_BILL')`), chkBaseExponent: check("chk_fx_revaluation_lines_base_exponent", sql`${t.baseExponent} BETWEEN 0 AND 6`), chkOpen: check("chk_fx_revaluation_lines_open", sql`${t.foreignOpenMinor} > 0 AND ${t.carryingBaseMinor} > 0 AND ${t.revaluedBaseMinor} > 0`) }));

export const fxRevaluationReversals = sqliteTable("fx_revaluation_reversals", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), runId: text("run_id").notNull(), journalId: text("journal_id").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({ fkRun: foreignKey({ columns: [t.runId, t.tenantId, t.bookSetId], foreignColumns: [fxRevaluationRuns.id, fxRevaluationRuns.tenantId, fxRevaluationRuns.bookSetId] }), uqRun: uniqueIndex("uq_fx_revaluation_reversals_run").on(t.runId) }));

export const bankAccountCurrencies = sqliteTable("bank_account_currencies", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), accountId: text("account_id").notNull(), currencyCode: text("currency_code").notNull(), exponent: integer("exponent").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({ fkBookSet: foreignKey({ columns: [t.bookSetId, t.tenantId], foreignColumns: [bookSets.id, bookSets.tenantId] }), fkAccount: foreignKey({ columns: [t.accountId, t.tenantId, t.bookSetId], foreignColumns: [accounts.id, accounts.tenantId, accounts.bookSetId] }), uqAccount: uniqueIndex("uq_bank_account_currencies_account").on(t.tenantId, t.bookSetId, t.accountId), chkCode: check("chk_bank_account_currency_code", sql`length(${t.currencyCode}) = 3 AND ${t.currencyCode} NOT GLOB '*[^A-Z]*'`), chkExponent: check("chk_bank_account_currency_exponent", sql`${t.exponent} BETWEEN 0 AND 6`) }));

export const bankStatementLineCurrencies = sqliteTable("bank_statement_line_currencies", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), statementLineId: text("statement_line_id").notNull(), accountId: text("account_id").notNull(), currencyCode: text("currency_code").notNull(), exponent: integer("exponent").notNull(), statementMinor: integer("statement_minor").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({ fkBookSet: foreignKey({ columns: [t.bookSetId, t.tenantId], foreignColumns: [bookSets.id, bookSets.tenantId] }), uqLine: uniqueIndex("uq_bank_statement_line_currencies_line").on(t.tenantId, t.bookSetId, t.statementLineId), idxCurrency: index("idx_bank_statement_line_currencies_currency").on(t.tenantId, t.bookSetId, t.currencyCode, t.statementLineId), chkCode: check("chk_bank_statement_line_currency_code", sql`length(${t.currencyCode}) = 3 AND ${t.currencyCode} NOT GLOB '*[^A-Z]*'`), chkExponent: check("chk_bank_statement_line_currency_exponent", sql`${t.exponent} BETWEEN 0 AND 6`), chkAmount: check("chk_bank_statement_line_currency_amount", sql`typeof(${t.statementMinor}) = 'integer' AND ${t.statementMinor} <> 0`) }));
