import { sqliteTable, text, integer, foreignKey, uniqueIndex, index, check } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import { bookSets, legalIdentities, tenants } from "./foundation-schema";
import { closePackManifests } from "./close-pack-schema";
import { bookSetLedgerRevisions } from "./personal-taxcase-schema";

export const mcaFormPacks = sqliteTable("mca_form_packs", {
  id: text("id").primaryKey(), jurisdiction: text("jurisdiction").notNull(), authority: text("authority").notNull(), formFamily: text("form_family").notNull(), filingType: text("filing_type").notNull(), financialYear: text("financial_year").notNull(), effectiveFrom: text("effective_from").notNull(), effectiveTo: text("effective_to"), releasedAt: text("released_at").notNull(), lawReference: text("law_reference").notNull(), ruleReference: text("rule_reference").notNull(), instructionReference: text("instruction_reference").notNull(), schemaReference: text("schema_reference").notNull(), artifactReferencesJson: text("artifact_references_json").notNull(), packVersion: text("pack_version").notNull(), requiredFactDeclarationsJson: text("required_fact_declarations_json").notNull(), applicabilityRuleAstJson: text("applicability_rule_ast_json").notNull(), validationSchemaJson: text("validation_schema_json").notNull(), mappingSpecJson: text("mapping_spec_json").notNull(), canonicalHash: text("canonical_hash").notNull(), testOnly: integer("test_only").notNull(), supersedesPackId: text("supersedes_pack_id"), createdAt: text("created_at").notNull(), createdByActorKind: text("created_by_actor_kind").notNull(), createdByActorId: text("created_by_actor_id").notNull(),
}, (t) => ({
  fkSupersedes: foreignKey({ columns: [t.supersedesPackId], foreignColumns: [t.id] }).onDelete("no action"),
  uqHash: uniqueIndex("uq_mca_form_packs_hash").on(t.canonicalHash),
  uqIdentity: uniqueIndex("uq_mca_form_packs_identity").on(t.jurisdiction, t.authority, t.formFamily, t.filingType, t.financialYear, t.effectiveFrom, t.packVersion),
  idxApplicable: index("idx_mca_form_packs_applicable").on(t.formFamily, t.financialYear, t.effectiveFrom, t.effectiveTo),
  chkIdentity: check("chk_mca_form_packs_identity", sql`${t.jurisdiction} = 'IN' AND ${t.authority} = 'MCA' AND ${t.formFamily} IN ('AOC-4','AOC-4 XBRL','AOC-4 CFS','MGT-7','MGT-7A','ADT-1','MSME-1')`),
  chkHash: check("chk_mca_form_packs_hash", sql`length(${t.canonicalHash}) = 64 AND ${t.canonicalHash} NOT GLOB '*[^0-9a-f]*'`),
  chkTestOnly: check("chk_mca_form_packs_test_only", sql`${t.testOnly} = 1`),
  chkActor: check("chk_mca_form_packs_actor", sql`${t.createdByActorKind} IN ('AGENT','HUMAN') AND length(trim(${t.createdByActorId})) > 0`),
}));

export const mcaFormPackEvents = sqliteTable("mca_form_pack_events", {
  id: text("id").primaryKey(), packId: text("pack_id").notNull(), eventType: text("event_type").notNull(), actorKind: text("actor_kind").notNull(), actorId: text("actor_id").notNull(), reason: text("reason").notNull(), expectedPackHash: text("expected_pack_hash").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({ fkPack: foreignKey({ columns: [t.packId], foreignColumns: [mcaFormPacks.id] }).onDelete("no action"), uqRequest: uniqueIndex("uq_mca_form_pack_events_request").on(t.requestId), idxPack: index("idx_mca_form_pack_events_pack").on(t.packId, t.createdAt, t.id), chkType: check("chk_mca_form_pack_event_type", sql`${t.eventType} IN ('REGISTERED','HUMAN_VERIFIED','REJECTED','SUPERSEDED')`), chkActor: check("chk_mca_form_pack_event_actor", sql`${t.actorKind} IN ('AGENT','HUMAN') AND length(trim(${t.actorId})) > 0 AND (${t.eventType} IN ('REGISTERED','SUPERSEDED') OR ${t.actorKind} = 'HUMAN')`), chkHashes: check("chk_mca_form_pack_event_hashes", sql`length(${t.expectedPackHash}) = 64 AND ${t.expectedPackHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.requestHash}) = 64 AND ${t.requestHash} NOT GLOB '*[^0-9a-f]*'`) }));

export const mcaCompanyFacts = sqliteTable("mca_company_facts", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), legalIdentityId: text("legal_identity_id").notNull(), financialYear: text("financial_year").notNull(), factType: text("fact_type").notNull(), effectiveFrom: text("effective_from").notNull(), effectiveTo: text("effective_to"), factsJson: text("facts_json").notNull(), provenanceJson: text("provenance_json").notNull(), evidenceIdsJson: text("evidence_ids_json").notNull(), canonicalHash: text("canonical_hash").notNull(), createdAt: text("created_at").notNull(), createdByActorKind: text("created_by_actor_kind").notNull(), createdByActorId: text("created_by_actor_id").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(),
}, (t) => ({ fkTenant: foreignKey({ columns: [t.tenantId], foreignColumns: [tenants.id] }).onDelete("no action"), fkBookSet: foreignKey({ columns: [t.bookSetId, t.tenantId], foreignColumns: [bookSets.id, bookSets.tenantId] }).onDelete("no action"), fkIdentity: foreignKey({ columns: [t.legalIdentityId], foreignColumns: [legalIdentities.id] }).onDelete("no action"), uqScopeHash: uniqueIndex("uq_mca_company_facts_scope_hash").on(t.tenantId, t.bookSetId, t.legalIdentityId, t.financialYear, t.factType, t.canonicalHash), uqRequest: uniqueIndex("uq_mca_company_facts_request").on(t.tenantId, t.requestId), uqScopeId: uniqueIndex("uq_mca_company_facts_id_scope").on(t.id, t.tenantId, t.bookSetId), idxScope: index("idx_mca_company_facts_scope").on(t.tenantId, t.bookSetId, t.legalIdentityId, t.financialYear, t.factType, t.effectiveFrom), chkDates: check("chk_mca_company_facts_dates", sql`length(${t.effectiveFrom}) = 10 AND (${t.effectiveTo} IS NULL OR ${t.effectiveFrom} <= ${t.effectiveTo})`), chkHash: check("chk_mca_company_facts_hash", sql`length(${t.canonicalHash}) = 64 AND ${t.canonicalHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.requestHash}) = 64 AND ${t.requestHash} NOT GLOB '*[^0-9a-f]*'`), chkActor: check("chk_mca_company_facts_actor", sql`${t.createdByActorKind} IN ('AGENT','HUMAN') AND length(trim(${t.createdByActorId})) > 0`) }));

export const mcaCompanyFactEvents = sqliteTable("mca_company_fact_events", {
  id: text("id").primaryKey(), factId: text("fact_id").notNull(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), eventType: text("event_type").notNull(), actorKind: text("actor_kind").notNull(), actorId: text("actor_id").notNull(), reason: text("reason").notNull(), expectedFactHash: text("expected_fact_hash").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({ fkFact: foreignKey({ columns: [t.factId, t.tenantId, t.bookSetId], foreignColumns: [mcaCompanyFacts.id, mcaCompanyFacts.tenantId, mcaCompanyFacts.bookSetId] }).onDelete("no action"), uqRequest: uniqueIndex("uq_mca_company_fact_events_request").on(t.tenantId, t.requestId), idxFact: index("idx_mca_company_fact_events_fact").on(t.tenantId, t.bookSetId, t.factId, t.createdAt), chkType: check("chk_mca_company_fact_event_type", sql`${t.eventType} IN ('PROPOSED','HUMAN_CONFIRMED','HUMAN_REJECTED')`), chkActor: check("chk_mca_company_fact_event_actor", sql`${t.actorKind} IN ('AGENT','HUMAN') AND length(trim(${t.actorId})) > 0 AND (${t.eventType} = 'PROPOSED' OR ${t.actorKind} = 'HUMAN')`), chkHashes: check("chk_mca_company_fact_event_hashes", sql`length(${t.expectedFactHash}) = 64 AND ${t.expectedFactHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.requestHash}) = 64 AND ${t.requestHash} NOT GLOB '*[^0-9a-f]*'`) }));

export const mcaApplicabilityDecisions = sqliteTable("mca_applicability_decisions", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), formPackId: text("form_pack_id").notNull(), legalIdentityId: text("legal_identity_id").notNull(), financialYear: text("financial_year").notNull(), decision: text("decision").notNull(), missingKeysJson: text("missing_keys_json").notNull(), ruleTraceJson: text("rule_trace_json").notNull(), factsHash: text("facts_hash").notNull(), packHash: text("pack_hash").notNull(), evaluatedAt: text("evaluated_at").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(),
}, (t) => ({ fkPack: foreignKey({ columns: [t.formPackId], foreignColumns: [mcaFormPacks.id] }).onDelete("no action"), fkTenant: foreignKey({ columns: [t.tenantId], foreignColumns: [tenants.id] }).onDelete("no action"), fkBookSet: foreignKey({ columns: [t.bookSetId, t.tenantId], foreignColumns: [bookSets.id, bookSets.tenantId] }).onDelete("no action"), fkIdentity: foreignKey({ columns: [t.legalIdentityId], foreignColumns: [legalIdentities.id] }).onDelete("no action"), uqInput: uniqueIndex("uq_mca_applicability_input").on(t.tenantId, t.bookSetId, t.formPackId, t.legalIdentityId, t.financialYear, t.factsHash), uqRequest: uniqueIndex("uq_mca_applicability_request").on(t.tenantId, t.requestId), idxScope: index("idx_mca_applicability_scope").on(t.tenantId, t.bookSetId, t.financialYear, t.formPackId), chkDecision: check("chk_mca_applicability_decision", sql`${t.decision} IN ('APPLICABLE','NOT_APPLICABLE_WITH_FACT','UNKNOWN','BLOCKED')`), chkHashes: check("chk_mca_applicability_hashes", sql`length(${t.factsHash}) = 64 AND ${t.factsHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.packHash}) = 64 AND ${t.packHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.requestHash}) = 64 AND ${t.requestHash} NOT GLOB '*[^0-9a-f]*'`) }));

export const mcaAnnualArtifacts = sqliteTable("mca_annual_artifacts", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), legalIdentityId: text("legal_identity_id").notNull(), financialYear: text("financial_year").notNull(), formFamily: text("form_family").notNull(), filingType: text("filing_type").notNull(), formPackId: text("form_pack_id").notNull(), formPackHash: text("form_pack_hash").notNull(), factSetHash: text("fact_set_hash").notNull(), sourceModelHash: text("source_model_hash").notNull(), ledgerRevision: integer("ledger_revision").notNull(), closePackManifestId: text("close_pack_manifest_id").notNull(), closePackManifestHash: text("close_pack_manifest_hash").notNull(), contentJson: text("content_json").notNull(), contentByteLength: integer("content_byte_length").notNull(), contentHash: text("content_hash").notNull(), bindingsJson: text("bindings_json").notNull(), createdAt: text("created_at").notNull(), createdByActorKind: text("created_by_actor_kind").notNull(), createdByActorId: text("created_by_actor_id").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(),
}, (t) => ({ fkTenant: foreignKey({ columns: [t.tenantId], foreignColumns: [tenants.id] }).onDelete("no action"), fkBookSet: foreignKey({ columns: [t.bookSetId, t.tenantId], foreignColumns: [bookSets.id, bookSets.tenantId] }).onDelete("no action"), fkIdentity: foreignKey({ columns: [t.legalIdentityId], foreignColumns: [legalIdentities.id] }).onDelete("no action"), fkPack: foreignKey({ columns: [t.formPackId], foreignColumns: [mcaFormPacks.id] }).onDelete("no action"), fkClosePack: foreignKey({ columns: [t.closePackManifestId, t.tenantId, t.bookSetId], foreignColumns: [closePackManifests.id, closePackManifests.tenantId, closePackManifests.bookSetId] }).onDelete("no action"), fkRevision: foreignKey({ columns: [t.tenantId, t.bookSetId], foreignColumns: [bookSetLedgerRevisions.tenantId, bookSetLedgerRevisions.bookSetId] }).onDelete("no action"), uqScopeHash: uniqueIndex("uq_mca_annual_artifacts_scope_hash").on(t.tenantId, t.bookSetId, t.financialYear, t.formFamily, t.filingType, t.contentHash), uqRequest: uniqueIndex("uq_mca_annual_artifacts_request").on(t.tenantId, t.requestId), uqScopeId: uniqueIndex("uq_mca_annual_artifacts_id_scope").on(t.id, t.tenantId, t.bookSetId), idxScope: index("idx_mca_annual_artifacts_scope").on(t.tenantId, t.bookSetId, t.financialYear, t.formFamily, t.createdAt), chkIdentity: check("chk_mca_annual_artifacts_identity", sql`${t.formFamily} IN ('AOC-4','AOC-4 XBRL','AOC-4 CFS','MGT-7','MGT-7A','ADT-1','MSME-1')`), chkHashes: check("chk_mca_annual_artifacts_hashes", sql`length(${t.formPackHash}) = 64 AND ${t.formPackHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.factSetHash}) = 64 AND ${t.factSetHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.sourceModelHash}) = 64 AND ${t.sourceModelHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.closePackManifestHash}) = 64 AND ${t.closePackManifestHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.contentHash}) = 64 AND ${t.contentHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.requestHash}) = 64 AND ${t.requestHash} NOT GLOB '*[^0-9a-f]*'`), chkActor: check("chk_mca_annual_artifacts_actor", sql`${t.createdByActorKind} IN ('AGENT','HUMAN') AND length(trim(${t.createdByActorId})) > 0`) }));

export const mcaAnnualValidationRuns = sqliteTable("mca_annual_validation_runs", { id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), artifactId: text("artifact_id").notNull(), artifactHash: text("artifact_hash").notNull(), formPackHash: text("form_pack_hash").notNull(), validationHash: text("validation_hash").notNull(), status: text("status").notNull(), diagnosticsJson: text("diagnostics_json").notNull(), createdAt: text("created_at").notNull(), createdByActorKind: text("created_by_actor_kind").notNull(), createdByActorId: text("created_by_actor_id").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull() }, (t) => ({ fkArtifact: foreignKey({ columns: [t.artifactId, t.tenantId, t.bookSetId], foreignColumns: [mcaAnnualArtifacts.id, mcaAnnualArtifacts.tenantId, mcaAnnualArtifacts.bookSetId] }).onDelete("no action"), uqRequest: uniqueIndex("uq_mca_annual_validation_request").on(t.tenantId, t.requestId), idxArtifact: index("idx_mca_annual_validation_artifact").on(t.tenantId, t.bookSetId, t.artifactId, t.createdAt), chkStatus: check("chk_mca_annual_validation_status", sql`${t.status} IN ('LOCAL_VALID','LOCAL_INVALID')`), chkHashes: check("chk_mca_annual_validation_hashes", sql`length(${t.artifactHash}) = 64 AND ${t.artifactHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.formPackHash}) = 64 AND ${t.formPackHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.validationHash}) = 64 AND ${t.validationHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.requestHash}) = 64 AND ${t.requestHash} NOT GLOB '*[^0-9a-f]*'`) }));

export const mcaAnnualExportActivities = sqliteTable("mca_annual_export_activities", { id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), artifactId: text("artifact_id").notNull(), artifactHash: text("artifact_hash").notNull(), validationHash: text("validation_hash").notNull(), actorKind: text("actor_kind").notNull(), actorId: text("actor_id").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(), createdAt: text("created_at").notNull() }, (t) => ({ fkArtifact: foreignKey({ columns: [t.artifactId, t.tenantId, t.bookSetId], foreignColumns: [mcaAnnualArtifacts.id, mcaAnnualArtifacts.tenantId, mcaAnnualArtifacts.bookSetId] }).onDelete("no action"), uqRequest: uniqueIndex("uq_mca_annual_export_request").on(t.tenantId, t.requestId), idxArtifact: index("idx_mca_annual_export_artifact").on(t.tenantId, t.bookSetId, t.artifactId, t.createdAt), chkActor: check("chk_mca_annual_export_actor", sql`${t.actorKind} = 'HUMAN' AND length(trim(${t.actorId})) > 0`), chkHashes: check("chk_mca_annual_export_hashes", sql`length(${t.artifactHash}) = 64 AND ${t.artifactHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.validationHash}) = 64 AND ${t.validationHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.requestHash}) = 64 AND ${t.requestHash} NOT GLOB '*[^0-9a-f]*'`) }));
