import { sqliteTable, text, integer, foreignKey, uniqueIndex, index, check } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import { tenants, bookSets, accounts } from "./foundation-schema";
import { journalEntries } from "./ledger-schema";

const scope = (table: any) => foreignKey({ columns: [table.bookSetId, table.tenantId], foreignColumns: [bookSets.id, bookSets.tenantId] }).onDelete("no action");
const scopedId = (table: any, target: any) => foreignKey({ columns: [table.id, table.tenantId, table.bookSetId], foreignColumns: [target.id, target.tenantId, target.bookSetId] }).onDelete("no action");

export const payrollEmployees = sqliteTable("payroll_employees", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), employeeCode: text("employee_code").notNull(), legalName: text("legal_name").notNull(), joiningDate: text("joining_date").notNull(), exitDate: text("exit_date"), workState: text("work_state").notNull(), workLocation: text("work_location").notNull(), panLastFour: text("pan_last_four"), panFingerprint: text("pan_fingerprint"), panVerificationStatus: text("pan_verification_status").notNull(), uanLastFour: text("uan_last_four"), uanVerificationStatus: text("uan_verification_status").notNull(), esicLastFour: text("esic_last_four"), esicVerificationStatus: text("esic_verification_status").notNull(), bankLastFour: text("bank_last_four"), bankFingerprint: text("bank_fingerprint"), bankVerificationStatus: text("bank_verification_status").notNull(), evidenceId: text("evidence_id"), createdAt: text("created_at").notNull(), updatedAt: text("updated_at").notNull(),
}, (t) => ({ fkBookSet: scope(t), fkTenant: foreignKey({ columns: [t.tenantId], foreignColumns: [tenants.id] }), uqCode: uniqueIndex("uq_payroll_employees_code").on(t.tenantId, t.bookSetId, t.employeeCode), uqScope: uniqueIndex("uq_payroll_employees_scope_key").on(t.id, t.tenantId, t.bookSetId), idxScope: index("idx_payroll_employees_scope").on(t.tenantId, t.bookSetId, t.employeeCode), chkStatuses: check("chk_payroll_employee_verification_statuses", sql`${t.panVerificationStatus} IN ('UNVERIFIED','VERIFIED','REVIEW_REQUIRED') AND ${t.uanVerificationStatus} IN ('NOT_APPLICABLE','UNVERIFIED','VERIFIED','REVIEW_REQUIRED') AND ${t.esicVerificationStatus} IN ('NOT_APPLICABLE','UNVERIFIED','VERIFIED','REVIEW_REQUIRED') AND ${t.bankVerificationStatus} IN ('UNVERIFIED','VERIFIED','REVIEW_REQUIRED')`), chkDates: check("chk_payroll_employee_dates", sql`${t.exitDate} IS NULL OR ${t.exitDate} >= ${t.joiningDate}`), chkName: check("chk_payroll_employee_name", sql`length(trim(${t.legalName})) > 0`) }));

export const payrollEmployeeProfiles = sqliteTable("payroll_employee_profiles", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), employeeId: text("employee_id").notNull(), profileType: text("profile_type").notNull(), effectiveFrom: text("effective_from").notNull(), effectiveTo: text("effective_to"), factsJson: text("facts_json").notNull(), verificationStatus: text("verification_status").notNull(), evidenceId: text("evidence_id"), canonicalHash: text("canonical_hash").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({ fkBookSet: scope(t), fkEmployee: foreignKey({ columns: [t.employeeId, t.tenantId, t.bookSetId], foreignColumns: [payrollEmployees.id, payrollEmployees.tenantId, payrollEmployees.bookSetId] }), uqScope: uniqueIndex("uq_payroll_employee_profiles_scope_key").on(t.id, t.tenantId, t.bookSetId), uqHash: uniqueIndex("uq_payroll_employee_profiles_hash").on(t.tenantId, t.bookSetId, t.canonicalHash), idxEffective: index("idx_payroll_employee_profiles_effective").on(t.tenantId, t.bookSetId, t.employeeId, t.profileType, t.effectiveFrom), chkType: check("chk_payroll_employee_profile_type", sql`${t.profileType} IN ('TAX','STATUTORY')`), chkStatus: check("chk_payroll_employee_profile_status", sql`${t.verificationStatus} IN ('UNVERIFIED','VERIFIED','REVIEW_REQUIRED')`), chkDates: check("chk_payroll_employee_profile_dates", sql`${t.effectiveTo} IS NULL OR ${t.effectiveTo} > ${t.effectiveFrom}`) }));

export const payrollSalaryStructures = sqliteTable("payroll_salary_structures", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), name: text("name").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({ fkBookSet: scope(t), uqName: uniqueIndex("uq_payroll_salary_structures_name").on(t.tenantId, t.bookSetId, t.name), uqScope: uniqueIndex("uq_payroll_salary_structures_scope_key").on(t.id, t.tenantId, t.bookSetId) }));

export const payrollSalaryVersions = sqliteTable("payroll_salary_versions", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), structureId: text("structure_id").notNull(), versionNumber: integer("version_number").notNull(), effectiveFrom: text("effective_from").notNull(), effectiveTo: text("effective_to"), prorationPolicy: text("proration_policy").notNull(), canonicalHash: text("canonical_hash").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({ fkBookSet: scope(t), fkStructure: foreignKey({ columns: [t.structureId, t.tenantId, t.bookSetId], foreignColumns: [payrollSalaryStructures.id, payrollSalaryStructures.tenantId, payrollSalaryStructures.bookSetId] }), uqVersion: uniqueIndex("uq_payroll_salary_versions_number").on(t.structureId, t.versionNumber), uqScope: uniqueIndex("uq_payroll_salary_versions_scope_key").on(t.id, t.tenantId, t.bookSetId), uqHash: uniqueIndex("uq_payroll_salary_versions_hash").on(t.tenantId, t.bookSetId, t.canonicalHash), idxEffective: index("idx_payroll_salary_versions_effective").on(t.tenantId, t.bookSetId, t.structureId, t.effectiveFrom), chkProration: check("chk_payroll_salary_version_proration", sql`${t.prorationPolicy} IN ('NONE','PAYABLE_DAYS_OVER_PERIOD_DAYS','CALENDAR_DAYS')`), chkDates: check("chk_payroll_salary_version_dates", sql`${t.effectiveTo} IS NULL OR ${t.effectiveTo} > ${t.effectiveFrom}`) }));

export const payrollSalaryComponents = sqliteTable("payroll_salary_components", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), versionId: text("version_id").notNull(), componentCode: text("component_code").notNull(), label: text("label").notNull(), kind: text("kind").notNull(), basisType: text("basis_type").notNull(), fixedMinor: integer("fixed_minor"), rateBps: integer("rate_bps"), basisComponentCode: text("basis_component_code"), expenseAccountId: text("expense_account_id"), payableAccountId: text("payable_account_id"), liabilityAccountId: text("liability_account_id"), createdAt: text("created_at").notNull(),
}, (t) => ({ fkBookSet: scope(t), fkVersion: foreignKey({ columns: [t.versionId, t.tenantId, t.bookSetId], foreignColumns: [payrollSalaryVersions.id, payrollSalaryVersions.tenantId, payrollSalaryVersions.bookSetId] }), fkExpense: foreignKey({ columns: [t.expenseAccountId, t.tenantId, t.bookSetId], foreignColumns: [accounts.id, accounts.tenantId, accounts.bookSetId] }), fkPayable: foreignKey({ columns: [t.payableAccountId, t.tenantId, t.bookSetId], foreignColumns: [accounts.id, accounts.tenantId, accounts.bookSetId] }), fkLiability: foreignKey({ columns: [t.liabilityAccountId, t.tenantId, t.bookSetId], foreignColumns: [accounts.id, accounts.tenantId, accounts.bookSetId] }), uqCode: uniqueIndex("uq_payroll_salary_components_code").on(t.versionId, t.componentCode), uqScope: uniqueIndex("uq_payroll_salary_components_scope_key").on(t.id, t.tenantId, t.bookSetId), idxVersion: index("idx_payroll_salary_components_version").on(t.tenantId, t.bookSetId, t.versionId, t.componentCode), chkKind: check("chk_payroll_salary_component_kind", sql`${t.kind} IN ('EARNING','EMPLOYEE_DEDUCTION','EMPLOYER_CONTRIBUTION','INFORMATIONAL')`), chkBasis: check("chk_payroll_salary_component_basis", sql`(${t.basisType} = 'FIXED_MINOR' AND ${t.fixedMinor} IS NOT NULL AND ${t.fixedMinor} >= 0 AND ${t.rateBps} IS NULL AND ${t.basisComponentCode} IS NULL) OR (${t.basisType} = 'RATE_BPS' AND ${t.rateBps} IS NOT NULL AND ${t.rateBps} >= 0 AND ${t.rateBps} <= 100000 AND ${t.fixedMinor} IS NULL AND ${t.basisComponentCode} IS NOT NULL)`), chkAccount: check("chk_payroll_salary_component_accounts", sql`(${t.kind} = 'EARNING' AND ${t.expenseAccountId} IS NOT NULL) OR (${t.kind} = 'EMPLOYER_CONTRIBUTION' AND ${t.expenseAccountId} IS NOT NULL AND ${t.liabilityAccountId} IS NOT NULL) OR (${t.kind} IN ('EMPLOYEE_DEDUCTION') AND ${t.liabilityAccountId} IS NOT NULL) OR ${t.kind} = 'INFORMATIONAL'`) }));

export const payrollClaims = sqliteTable("payroll_claims", { id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), employeeId: text("employee_id").notNull(), taxYear: text("tax_year").notNull(), category: text("category").notNull(), amountMinor: integer("amount_minor").notNull(), evidenceId: text("evidence_id").notNull(), status: text("status").notNull(), reviewerId: text("reviewer_id"), reviewObservation: text("review_observation"), reviewedAt: text("reviewed_at"), createdAt: text("created_at").notNull(),
}, (t) => ({ fkBookSet: scope(t), fkEmployee: foreignKey({ columns: [t.employeeId, t.tenantId, t.bookSetId], foreignColumns: [payrollEmployees.id, payrollEmployees.tenantId, payrollEmployees.bookSetId] }), uqScope: uniqueIndex("uq_payroll_claims_scope_key").on(t.id, t.tenantId, t.bookSetId), idxStatus: index("idx_payroll_claims_status").on(t.tenantId, t.bookSetId, t.employeeId, t.taxYear, t.status), chkStatus: check("chk_payroll_claim_status", sql`${t.status} IN ('PENDING','APPROVED','REJECTED')`), chkAmount: check("chk_payroll_claim_amount", sql`${t.amountMinor} >= 0`) }));

export const payrollRuleSnapshots = sqliteTable("payroll_rule_snapshots", { id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), jurisdiction: text("jurisdiction").notNull(), ruleType: text("rule_type").notNull(), effectiveFrom: text("effective_from").notNull(), effectiveTo: text("effective_to"), officialSource: text("official_source").notNull(), lawReference: text("law_reference").notNull(), ruleVersion: text("rule_version").notNull(), applicabilityFactsJson: text("applicability_facts_json").notNull(), rateBps: integer("rate_bps"), capMinor: integer("cap_minor"), basis: text("basis").notNull(), rounding: text("rounding").notNull(), status: text("status").notNull(), salaryTdsFactsJson: text("salary_tds_facts_json"), canonicalHash: text("canonical_hash").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({ fkBookSet: scope(t), uqHash: uniqueIndex("uq_payroll_rule_snapshots_hash").on(t.tenantId, t.bookSetId, t.canonicalHash), uqScope: uniqueIndex("uq_payroll_rule_snapshots_scope_key").on(t.id, t.tenantId, t.bookSetId), idxEffective: index("idx_payroll_rule_snapshots_effective").on(t.tenantId, t.bookSetId, t.jurisdiction, t.ruleType, t.effectiveFrom), chkType: check("chk_payroll_rule_snapshot_type", sql`${t.ruleType} IN ('SALARY_TDS','EPF','ESI','PT','LWF')`), chkStatus: check("chk_payroll_rule_snapshot_status", sql`${t.status} IN ('VERIFIED','UNVERIFIED','TENTATIVE')`), chkBasis: check("chk_payroll_rule_snapshot_basis", sql`${t.basis} IN ('GROSS','NAMED_COMPONENT','TAXABLE_INCOME','FIXED')`), chkRounding: check("chk_payroll_rule_snapshot_rounding", sql`${t.rounding} IN ('PAISE_HALF_UP','PAISE_DOWN','PAISE_UP')`), chkDates: check("chk_payroll_rule_snapshot_dates", sql`${t.effectiveTo} IS NULL OR ${t.effectiveTo} > ${t.effectiveFrom}`), chkRate: check("chk_payroll_rule_snapshot_rate", sql`${t.rateBps} IS NULL OR (${t.rateBps} >= 0 AND ${t.rateBps} <= 100000)`) }));

export const payrollPayRuns = sqliteTable("payroll_pay_runs", { id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), periodStart: text("period_start").notNull(), periodEnd: text("period_end").notNull(), paymentDate: text("payment_date").notNull(), status: text("status").notNull(), inputHash: text("input_hash").notNull(), calculationHash: text("calculation_hash"), journalId: text("journal_id"), createdAt: text("created_at").notNull(), approvedAt: text("approved_at"), postedAt: text("posted_at").notNull().default(""),
}, (t) => ({ fkBookSet: scope(t), fkJournal: foreignKey({ columns: [t.journalId, t.tenantId, t.bookSetId], foreignColumns: [journalEntries.id, journalEntries.tenantId, journalEntries.bookSetId] }), uqScope: uniqueIndex("uq_payroll_pay_runs_scope_key").on(t.id, t.tenantId, t.bookSetId), uqPeriod: uniqueIndex("uq_payroll_pay_runs_period").on(t.tenantId, t.bookSetId, t.periodStart, t.periodEnd, t.paymentDate), idxStatus: index("idx_payroll_pay_runs_status").on(t.tenantId, t.bookSetId, t.status, t.paymentDate), chkStatus: check("chk_payroll_pay_run_status", sql`${t.status} IN ('PREPARED','APPROVED','POSTED','REVIEW_REQUIRED')`), chkDates: check("chk_payroll_pay_run_dates", sql`${t.periodEnd} >= ${t.periodStart} AND ${t.paymentDate} >= ${t.periodEnd}`), chkFields: check("chk_payroll_pay_run_fields", sql`(${t.status} IN ('PREPARED','REVIEW_REQUIRED') AND ${t.journalId} IS NULL AND ${t.approvedAt} IS NULL AND ${t.postedAt} = '') OR (${t.status} = 'APPROVED' AND ${t.journalId} IS NULL AND ${t.approvedAt} IS NOT NULL AND ${t.postedAt} = '') OR (${t.status} = 'POSTED' AND ${t.journalId} IS NOT NULL AND ${t.approvedAt} IS NOT NULL AND ${t.postedAt} <> '')`) }));

export const payrollPayRunEmployees = sqliteTable("payroll_pay_run_employees", { id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), payRunId: text("pay_run_id").notNull(), employeeId: text("employee_id").notNull(), salaryVersionId: text("salary_version_id").notNull(), payableDays: integer("payable_days").notNull(), periodDays: integer("period_days").notNull(), unpaidLeaveDays: integer("unpaid_leave_days").notNull(), variableFactsJson: text("variable_facts_json").notNull(), grossMinor: integer("gross_minor").notNull().default(0), employeeDeductionMinor: integer("employee_deduction_minor").notNull().default(0), employerContributionMinor: integer("employer_contribution_minor").notNull().default(0), netMinor: integer("net_minor").notNull().default(0), ruleIdsJson: text("rule_ids_json").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({ fkBookSet: scope(t), fkRun: foreignKey({ columns: [t.payRunId, t.tenantId, t.bookSetId], foreignColumns: [payrollPayRuns.id, payrollPayRuns.tenantId, payrollPayRuns.bookSetId] }), fkEmployee: foreignKey({ columns: [t.employeeId, t.tenantId, t.bookSetId], foreignColumns: [payrollEmployees.id, payrollEmployees.tenantId, payrollEmployees.bookSetId] }), fkVersion: foreignKey({ columns: [t.salaryVersionId, t.tenantId, t.bookSetId], foreignColumns: [payrollSalaryVersions.id, payrollSalaryVersions.tenantId, payrollSalaryVersions.bookSetId] }), uqEmployee: uniqueIndex("uq_payroll_pay_run_employee").on(t.payRunId, t.employeeId), uqScope: uniqueIndex("uq_payroll_pay_run_employees_scope_key").on(t.id, t.tenantId, t.bookSetId), idxRun: index("idx_payroll_pay_run_employees_run").on(t.tenantId, t.bookSetId, t.payRunId), chkDays: check("chk_payroll_pay_run_employee_days", sql`${t.periodDays} > 0 AND ${t.payableDays} >= 0 AND ${t.payableDays} <= ${t.periodDays} AND ${t.unpaidLeaveDays} >= 0 AND ${t.unpaidLeaveDays} <= ${t.periodDays}`), chkAmounts: check("chk_payroll_pay_run_employee_amounts", sql`${t.grossMinor} >= 0 AND ${t.employeeDeductionMinor} >= 0 AND ${t.employerContributionMinor} >= 0 AND ${t.netMinor} >= 0`) }));

export const payrollComponentLines = sqliteTable("payroll_component_lines", { id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), payRunEmployeeId: text("pay_run_employee_id").notNull(), componentId: text("component_id").notNull(), amountMinor: integer("amount_minor").notNull(), calculationFactsJson: text("calculation_facts_json").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({ fkBookSet: scope(t), fkRunEmployee: foreignKey({ columns: [t.payRunEmployeeId, t.tenantId, t.bookSetId], foreignColumns: [payrollPayRunEmployees.id, payrollPayRunEmployees.tenantId, payrollPayRunEmployees.bookSetId] }), fkComponent: foreignKey({ columns: [t.componentId, t.tenantId, t.bookSetId], foreignColumns: [payrollSalaryComponents.id, payrollSalaryComponents.tenantId, payrollSalaryComponents.bookSetId] }), uqComponent: uniqueIndex("uq_payroll_component_lines_component").on(t.payRunEmployeeId, t.componentId), idxRun: index("idx_payroll_component_lines_run").on(t.tenantId, t.bookSetId, t.payRunEmployeeId), chkAmount: check("chk_payroll_component_line_amount", sql`${t.amountMinor} >= 0`) }));

export const payrollPayslips = sqliteTable("payroll_payslips", { id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), payRunEmployeeId: text("pay_run_employee_id").notNull(), payslipNumber: text("payslip_number").notNull(), renderedText: text("rendered_text").notNull(), renderedHtml: text("rendered_html").notNull(), evidenceHash: text("evidence_hash").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({ fkBookSet: scope(t), fkRunEmployee: foreignKey({ columns: [t.payRunEmployeeId, t.tenantId, t.bookSetId], foreignColumns: [payrollPayRunEmployees.id, payrollPayRunEmployees.tenantId, payrollPayRunEmployees.bookSetId] }), uqNumber: uniqueIndex("uq_payroll_payslips_number").on(t.tenantId, t.bookSetId, t.payslipNumber), uqEmployee: uniqueIndex("uq_payroll_payslips_run_employee").on(t.payRunEmployeeId), idxRun: index("idx_payroll_payslips_run").on(t.tenantId, t.bookSetId, t.payRunEmployeeId), chkHash: check("chk_payroll_payslip_hash", sql`length(${t.evidenceHash}) = 64 AND ${t.evidenceHash} NOT GLOB '*[^0-9a-f]*'`) }));

export const payrollPaymentBatches = sqliteTable("payroll_payment_batches", { id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), paymentDate: text("payment_date").notNull(), bankAccountId: text("bank_account_id").notNull(), status: text("status").notNull(), createdAt: text("created_at").notNull(), journalId: text("journal_id"),
}, (t) => ({ fkBookSet: scope(t), fkBank: foreignKey({ columns: [t.bankAccountId, t.tenantId, t.bookSetId], foreignColumns: [accounts.id, accounts.tenantId, accounts.bookSetId] }), fkJournal: foreignKey({ columns: [t.journalId, t.tenantId, t.bookSetId], foreignColumns: [journalEntries.id, journalEntries.tenantId, journalEntries.bookSetId] }), uqScope: uniqueIndex("uq_payroll_payment_batches_scope_key").on(t.id, t.tenantId, t.bookSetId), chkStatus: check("chk_payroll_payment_batch_status", sql`${t.status} IN ('PREPARED','POSTED')`) }));
export const payrollPaymentAllocations = sqliteTable("payroll_payment_allocations", { id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), batchId: text("batch_id").notNull(), payRunEmployeeId: text("pay_run_employee_id").notNull(), amountMinor: integer("amount_minor").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({ fkBookSet: scope(t), fkBatch: foreignKey({ columns: [t.batchId, t.tenantId, t.bookSetId], foreignColumns: [payrollPaymentBatches.id, payrollPaymentBatches.tenantId, payrollPaymentBatches.bookSetId] }), fkRunEmployee: foreignKey({ columns: [t.payRunEmployeeId, t.tenantId, t.bookSetId], foreignColumns: [payrollPayRunEmployees.id, payrollPayRunEmployees.tenantId, payrollPayRunEmployees.bookSetId] }), uqEmployee: uniqueIndex("uq_payroll_payment_allocations_employee").on(t.batchId, t.payRunEmployeeId), chkAmount: check("chk_payroll_payment_allocation_amount", sql`${t.amountMinor} > 0`) }));

export const payrollBankExportPresets = sqliteTable("payroll_bank_export_presets", { id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), presetCode: text("preset_code").notNull(), version: integer("version").notNull(), columnsJson: text("columns_json").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({ fkBookSet: scope(t), uqVersion: uniqueIndex("uq_payroll_bank_export_presets_version").on(t.tenantId, t.bookSetId, t.presetCode, t.version), uqScope: uniqueIndex("uq_payroll_bank_export_presets_scope_key").on(t.id, t.tenantId, t.bookSetId), chkPreset: check("chk_payroll_bank_export_preset_code", sql`${t.presetCode} = 'GENERIC_NEFT'`) }));
export const payrollBankExportArtifacts = sqliteTable("payroll_bank_export_artifacts", { id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), batchId: text("batch_id").notNull(), presetId: text("preset_id").notNull(), csvText: text("csv_text").notNull(), artifactHash: text("artifact_hash").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({ fkBookSet: scope(t), fkBatch: foreignKey({ columns: [t.batchId, t.tenantId, t.bookSetId], foreignColumns: [payrollPaymentBatches.id, payrollPaymentBatches.tenantId, payrollPaymentBatches.bookSetId] }), fkPreset: foreignKey({ columns: [t.presetId, t.tenantId, t.bookSetId], foreignColumns: [payrollBankExportPresets.id, payrollBankExportPresets.tenantId, payrollBankExportPresets.bookSetId] }), uqBatchPreset: uniqueIndex("uq_payroll_bank_export_artifacts_batch_preset").on(t.batchId, t.presetId), chkHash: check("chk_payroll_bank_export_artifact_hash", sql`length(${t.artifactHash}) = 64 AND ${t.artifactHash} NOT GLOB '*[^0-9a-f]*'`) }));

export const payrollRemittances = sqliteTable("payroll_remittances", { id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), ruleType: text("rule_type").notNull(), periodStart: text("period_start").notNull(), periodEnd: text("period_end").notNull(), liabilityAccountId: text("liability_account_id").notNull(), amountMinor: integer("amount_minor").notNull(), status: text("status").notNull(), evidenceId: text("evidence_id"), observation: text("observation"), createdAt: text("created_at").notNull(), journalId: text("journal_id"),
}, (t) => ({ fkBookSet: scope(t), fkLiability: foreignKey({ columns: [t.liabilityAccountId, t.tenantId, t.bookSetId], foreignColumns: [accounts.id, accounts.tenantId, accounts.bookSetId] }), fkJournal: foreignKey({ columns: [t.journalId, t.tenantId, t.bookSetId], foreignColumns: [journalEntries.id, journalEntries.tenantId, journalEntries.bookSetId] }), uqScope: uniqueIndex("uq_payroll_remittances_scope_key").on(t.id, t.tenantId, t.bookSetId), uqPeriod: uniqueIndex("uq_payroll_remittances_period").on(t.tenantId, t.bookSetId, t.ruleType, t.periodStart, t.periodEnd), chkType: check("chk_payroll_remittance_type", sql`${t.ruleType} IN ('SALARY_TDS','EPF','ESI','PT','LWF')`), chkStatus: check("chk_payroll_remittance_status", sql`${t.status} IN ('PREPARED','EXPORTED','SUBMITTED','ACKNOWLEDGED','REJECTED')`), chkAmount: check("chk_payroll_remittance_amount", sql`${t.amountMinor} > 0`), chkAcknowledged: check("chk_payroll_remittance_acknowledged", sql`${t.status} <> 'ACKNOWLEDGED' OR ${t.evidenceId} IS NOT NULL`) }));
export const payrollRemittanceAllocations = sqliteTable("payroll_remittance_allocations", { id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), remittanceId: text("remittance_id").notNull(), payRunId: text("pay_run_id").notNull(), amountMinor: integer("amount_minor").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({ fkBookSet: scope(t), fkRemittance: foreignKey({ columns: [t.remittanceId, t.tenantId, t.bookSetId], foreignColumns: [payrollRemittances.id, payrollRemittances.tenantId, payrollRemittances.bookSetId] }), fkPayRun: foreignKey({ columns: [t.payRunId, t.tenantId, t.bookSetId], foreignColumns: [payrollPayRuns.id, payrollPayRuns.tenantId, payrollPayRuns.bookSetId] }), uqRun: uniqueIndex("uq_payroll_remittance_allocations_run").on(t.remittanceId, t.payRunId), chkAmount: check("chk_payroll_remittance_allocation_amount", sql`${t.amountMinor} > 0`) }));
