import { sqliteTable, text, integer, foreignKey, uniqueIndex, index, check } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import { tenants, bookSets } from "./foundation-schema";
import { payrollEmployees } from "./payroll-schema";

export const payrollStatutoryPacks = sqliteTable("payroll_statutory_packs", {
  id: text("id").primaryKey(), semanticKind: text("semantic_kind").notNull(), jurisdiction: text("jurisdiction").notNull(), applicableFrom: text("applicable_from").notNull(), applicableTo: text("applicable_to"), officialFormCode: text("official_form_code").notNull(), officialFormVersion: text("official_form_version").notNull(), authorityReference: text("authority_reference").notNull(), validatorVersion: text("validator_version").notNull(), validationSchemaJson: text("validation_schema_json").notNull(), mappingSpecJson: text("mapping_spec_json").notNull(), exportFormat: text("export_format").notNull(), canonicalHash: text("canonical_hash").notNull(), supersedesPackId: text("supersedes_pack_id"), createdAt: text("created_at").notNull(), createdByActorKind: text("created_by_actor_kind").notNull(), createdByActorId: text("created_by_actor_id").notNull(),
}, (t) => ({
  fkSupersedes: foreignKey({ columns: [t.supersedesPackId], foreignColumns: [t.id] }).onDelete("no action"),
  uqHash: uniqueIndex("uq_payroll_statutory_packs_hash").on(t.canonicalHash),
  uqIdentity: uniqueIndex("uq_payroll_statutory_packs_identity").on(t.semanticKind, t.officialFormCode, t.officialFormVersion, t.applicableFrom),
  idxEffective: index("idx_payroll_statutory_packs_effective").on(t.semanticKind, t.applicableFrom, t.applicableTo),
  chkKind: check("chk_payroll_statutory_packs_kind", sql`${t.semanticKind} IN ('SALARY_TDS_QUARTERLY_STATEMENT','SALARY_TDS_ANNUAL_CERTIFICATE')`),
  chkJurisdiction: check("chk_payroll_statutory_packs_jurisdiction", sql`${t.jurisdiction} = 'IN'`),
  chkFormat: check("chk_payroll_statutory_packs_format", sql`${t.exportFormat} IN ('JSON','CSV','TEXT')`),
  chkDates: check("chk_payroll_statutory_packs_dates", sql`${t.applicableTo} IS NULL OR ${t.applicableTo} >= ${t.applicableFrom}`),
  chkHash: check("chk_payroll_statutory_packs_hash", sql`length(${t.canonicalHash}) = 64 AND ${t.canonicalHash} NOT GLOB '*[^0-9a-f]*'`),
  chkActor: check("chk_payroll_statutory_packs_actor", sql`${t.createdByActorKind} IN ('AGENT','HUMAN') AND length(trim(${t.createdByActorId})) > 0`),
}));

export const payrollStatutoryPackEvents = sqliteTable("payroll_statutory_pack_events", {
  id: text("id").primaryKey(), packId: text("pack_id").notNull(), eventType: text("event_type").notNull(), actorKind: text("actor_kind").notNull(), actorId: text("actor_id").notNull(), reason: text("reason").notNull(), expectedPackHash: text("expected_pack_hash").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({
  fkPack: foreignKey({ columns: [t.packId], foreignColumns: [payrollStatutoryPacks.id] }).onDelete("no action"),
  uqRequest: uniqueIndex("uq_payroll_statutory_pack_events_request").on(t.requestId),
  idxPack: index("idx_payroll_statutory_pack_events_pack").on(t.packId, t.createdAt, t.id),
  chkType: check("chk_payroll_statutory_pack_event_type", sql`${t.eventType} IN ('REGISTERED','HUMAN_VERIFIED','REJECTED','SUPERSEDED')`),
  chkActor: check("chk_payroll_statutory_pack_event_actor", sql`${t.actorKind} IN ('AGENT','HUMAN') AND length(trim(${t.actorId})) > 0 AND (${t.eventType} IN ('REGISTERED','SUPERSEDED') OR ${t.actorKind} = 'HUMAN')`),
  chkHashes: check("chk_payroll_statutory_pack_event_hashes", sql`length(${t.expectedPackHash}) = 64 AND ${t.expectedPackHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.requestHash}) = 64 AND ${t.requestHash} NOT GLOB '*[^0-9a-f]*'`),
}));

export const payrollStatutoryArtifacts = sqliteTable("payroll_statutory_artifacts", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), semanticKind: text("semantic_kind").notNull(), financialYear: text("financial_year").notNull(), quarter: text("quarter"), employeeId: text("employee_id"), schemaPackId: text("schema_pack_id").notNull(), schemaPackHash: text("schema_pack_hash").notNull(), sourceModelHash: text("source_model_hash").notNull(), neutralContent: text("neutral_content").notNull(), governmentContent: text("government_content").notNull(), neutralContentHash: text("neutral_content_hash").notNull(), governmentContentHash: text("government_content_hash").notNull(), contentByteLength: integer("content_byte_length").notNull(), contentType: text("content_type").notNull(), bindingsJson: text("bindings_json").notNull(), createdAt: text("created_at").notNull(), createdByActorKind: text("created_by_actor_kind").notNull(), createdByActorId: text("created_by_actor_id").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(),
}, (t) => ({
  fkTenant: foreignKey({ columns: [t.tenantId], foreignColumns: [tenants.id] }).onDelete("no action"), fkBookSet: foreignKey({ columns: [t.bookSetId, t.tenantId], foreignColumns: [bookSets.id, bookSets.tenantId] }).onDelete("no action"), fkEmployee: foreignKey({ columns: [t.employeeId, t.tenantId, t.bookSetId], foreignColumns: [payrollEmployees.id, payrollEmployees.tenantId, payrollEmployees.bookSetId] }).onDelete("no action"), fkPack: foreignKey({ columns: [t.schemaPackId], foreignColumns: [payrollStatutoryPacks.id] }).onDelete("no action"),
  uqScopeHash: uniqueIndex("uq_payroll_statutory_artifacts_scope_hash").on(t.tenantId, t.bookSetId, t.semanticKind, t.financialYear, t.quarter, t.employeeId, t.governmentContentHash), uqRequest: uniqueIndex("uq_payroll_statutory_artifacts_request").on(t.tenantId, t.requestId), uqScopeId: uniqueIndex("uq_payroll_statutory_artifacts_id_scope").on(t.id, t.tenantId, t.bookSetId), idxScope: index("idx_payroll_statutory_artifacts_scope").on(t.tenantId, t.bookSetId, t.semanticKind, t.financialYear, t.quarter, t.employeeId, t.createdAt),
  chkKind: check("chk_payroll_statutory_artifacts_kind", sql`${t.semanticKind} IN ('SALARY_TDS_QUARTERLY_STATEMENT','SALARY_TDS_ANNUAL_CERTIFICATE')`), chkQuarter: check("chk_payroll_statutory_artifacts_quarter", sql`${t.quarter} IS NULL OR ${t.quarter} IN ('Q1','Q2','Q3','Q4')`), chkHashes: check("chk_payroll_statutory_artifacts_hashes", sql`length(${t.schemaPackHash}) = 64 AND ${t.schemaPackHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.sourceModelHash}) = 64 AND ${t.sourceModelHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.neutralContentHash}) = 64 AND ${t.neutralContentHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.governmentContentHash}) = 64 AND ${t.governmentContentHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.requestHash}) = 64 AND ${t.requestHash} NOT GLOB '*[^0-9a-f]*'`), chkActor: check("chk_payroll_statutory_artifacts_actor", sql`${t.createdByActorKind} IN ('AGENT','HUMAN') AND length(trim(${t.createdByActorId})) > 0`),
}));

export const payrollStatutoryValidationRuns = sqliteTable("payroll_statutory_validation_runs", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), artifactId: text("artifact_id").notNull(), artifactHash: text("artifact_hash").notNull(), schemaPackHash: text("schema_pack_hash").notNull(), validationHash: text("validation_hash").notNull(), status: text("status").notNull(), diagnosticsJson: text("diagnostics_json").notNull(), createdAt: text("created_at").notNull(), createdByActorKind: text("created_by_actor_kind").notNull(), createdByActorId: text("created_by_actor_id").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(),
}, (t) => ({ fkArtifact: foreignKey({ columns: [t.artifactId, t.tenantId, t.bookSetId], foreignColumns: [payrollStatutoryArtifacts.id, payrollStatutoryArtifacts.tenantId, payrollStatutoryArtifacts.bookSetId] }).onDelete("no action"), uqRequest: uniqueIndex("uq_payroll_statutory_validation_request").on(t.tenantId, t.requestId), idxArtifact: index("idx_payroll_statutory_validation_artifact").on(t.tenantId, t.bookSetId, t.artifactId, t.createdAt), chkStatus: check("chk_payroll_statutory_validation_status", sql`${t.status} IN ('LOCAL_VALID','LOCAL_INVALID')`), chkHashes: check("chk_payroll_statutory_validation_hashes", sql`length(${t.artifactHash}) = 64 AND ${t.artifactHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.schemaPackHash}) = 64 AND ${t.schemaPackHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.validationHash}) = 64 AND ${t.validationHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.requestHash}) = 64 AND ${t.requestHash} NOT GLOB '*[^0-9a-f]*'`) }));

export const payrollStatutoryExportActivities = sqliteTable("payroll_statutory_export_activities", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), artifactId: text("artifact_id").notNull(), artifactHash: text("artifact_hash").notNull(), validationHash: text("validation_hash").notNull(), actorKind: text("actor_kind").notNull(), actorId: text("actor_id").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({ fkArtifact: foreignKey({ columns: [t.artifactId, t.tenantId, t.bookSetId], foreignColumns: [payrollStatutoryArtifacts.id, payrollStatutoryArtifacts.tenantId, payrollStatutoryArtifacts.bookSetId] }).onDelete("no action"), uqRequest: uniqueIndex("uq_payroll_statutory_export_request").on(t.tenantId, t.requestId), idxArtifact: index("idx_payroll_statutory_export_artifact").on(t.tenantId, t.bookSetId, t.artifactId, t.createdAt), chkActor: check("chk_payroll_statutory_export_actor", sql`${t.actorKind} = 'HUMAN' AND length(trim(${t.actorId})) > 0`), chkHashes: check("chk_payroll_statutory_export_hashes", sql`length(${t.artifactHash}) = 64 AND ${t.artifactHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.validationHash}) = 64 AND ${t.validationHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.requestHash}) = 64 AND ${t.requestHash} NOT GLOB '*[^0-9a-f]*'`) }));
