import { sqliteTable, text, integer, foreignKey, uniqueIndex, index, check } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import { tenants } from "./foundation-schema";
import { taxCases } from "./personal-taxcase-schema";
import { personalTaxAuthorityPacks } from "./personal-tax-itr-eligibility-schema";

export const personalTaxReturnSchemaPacks = sqliteTable("personal_tax_return_schema_packs", {
  id: text("id").primaryKey(), authorityPackId: text("authority_pack_id").notNull(), authorityPackHash: text("authority_pack_hash").notNull(), itrForm: text("itr_form").notNull(), filingType: text("filing_type").notNull(), financialYear: text("financial_year").notNull(), assessmentYear: text("assessment_year").notNull(), artifactReferencesJson: text("artifact_references_json").notNull(), packVersion: text("pack_version").notNull(), validationSchemaJson: text("validation_schema_json").notNull(), mappingSpecJson: text("mapping_spec_json").notNull(), canonicalHash: text("canonical_hash").notNull(), supersedesPackId: text("supersedes_pack_id"), createdAt: text("created_at").notNull(), createdByActorKind: text("created_by_actor_kind").notNull(), createdByActorId: text("created_by_actor_id").notNull(),
}, (table) => ({
  fkAuthority: foreignKey({ columns: [table.authorityPackId], foreignColumns: [personalTaxAuthorityPacks.id] }).onDelete("no action"), fkSupersedes: foreignKey({ columns: [table.supersedesPackId], foreignColumns: [table.id] }).onDelete("no action"), uqHash: uniqueIndex("uq_personal_tax_return_schema_packs_hash").on(table.canonicalHash), uqIdentity: uniqueIndex("uq_personal_tax_return_schema_packs_identity").on(table.authorityPackId, table.itrForm, table.filingType, table.packVersion), idxApplicable: index("idx_personal_tax_return_schema_packs_applicable").on(table.financialYear, table.assessmentYear, table.itrForm, table.filingType), chkHashes: check("chk_personal_tax_return_schema_packs_hashes", sql`length(${table.authorityPackHash}) = 64 AND ${table.authorityPackHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.canonicalHash}) = 64 AND ${table.canonicalHash} NOT GLOB '*[^0-9a-f]*'`), chkActor: check("chk_personal_tax_return_schema_packs_actor", sql`${table.createdByActorKind} IN ('AGENT', 'HUMAN') AND length(trim(${table.createdByActorId})) > 0`),
}));

export const personalTaxReturnSchemaPackEvents = sqliteTable("personal_tax_return_schema_pack_events", {
  id: text("id").primaryKey(), packId: text("pack_id").notNull(), eventType: text("event_type").notNull(), actorKind: text("actor_kind").notNull(), actorId: text("actor_id").notNull(), reason: text("reason").notNull(), expectedPackHash: text("expected_pack_hash").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(), createdAt: text("created_at").notNull(),
}, (table) => ({ fkPack: foreignKey({ columns: [table.packId], foreignColumns: [personalTaxReturnSchemaPacks.id] }).onDelete("no action"), uqRequest: uniqueIndex("uq_personal_tax_return_schema_pack_events_request").on(table.requestId), idxPack: index("idx_personal_tax_return_schema_pack_events_pack").on(table.packId, table.createdAt, table.id), chkType: check("chk_personal_tax_return_schema_pack_event_type", sql`${table.eventType} IN ('REGISTERED', 'HUMAN_VERIFIED', 'REJECTED', 'SUPERSEDED')`), chkActor: check("chk_personal_tax_return_schema_pack_event_actor", sql`${table.actorKind} IN ('AGENT', 'HUMAN') AND length(trim(${table.actorId})) > 0 AND (${table.eventType} IN ('REGISTERED', 'SUPERSEDED') OR ${table.actorKind} = 'HUMAN')`), chkHashes: check("chk_personal_tax_return_schema_pack_event_hashes", sql`length(${table.expectedPackHash}) = 64 AND ${table.expectedPackHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.requestHash}) = 64 AND ${table.requestHash} NOT GLOB '*[^0-9a-f]*'`) }));

export const personalTaxReturnArtifacts = sqliteTable("personal_tax_return_artifacts", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), taxCaseId: text("tax_case_id").notNull(), filingSnapshotId: text("filing_snapshot_id").notNull(), worksheetId: text("worksheet_id").notNull(), evaluationId: text("evaluation_id").notNull(), selectionId: text("selection_id").notNull(), computationId: text("computation_id").notNull(), schemaPackId: text("schema_pack_id").notNull(), schemaPackHash: text("schema_pack_hash").notNull(), contentJson: text("content_json").notNull(), contentByteLength: integer("content_byte_length").notNull(), contentHash: text("content_hash").notNull(), bindingsJson: text("bindings_json").notNull(), createdAt: text("created_at").notNull(), createdByActorKind: text("created_by_actor_kind").notNull(), createdByActorId: text("created_by_actor_id").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(),
}, (table) => ({ fkTenant: foreignKey({ columns: [table.tenantId], foreignColumns: [tenants.id] }).onDelete("no action"), fkCase: foreignKey({ columns: [table.taxCaseId, table.tenantId], foreignColumns: [taxCases.id, taxCases.tenantId] }).onDelete("no action"), uqScope: uniqueIndex("uq_personal_tax_return_artifacts_id_scope").on(table.id, table.tenantId, table.taxCaseId), uqScopeHash: uniqueIndex("uq_personal_tax_return_artifacts_scope_hash").on(table.tenantId, table.taxCaseId, table.contentHash), uqRequest: uniqueIndex("uq_personal_tax_return_artifacts_request").on(table.tenantId, table.requestId), idxCase: index("idx_personal_tax_return_artifacts_case").on(table.tenantId, table.taxCaseId, table.createdAt, table.id), chkHashes: check("chk_personal_tax_return_artifacts_hashes", sql`length(${table.schemaPackHash}) = 64 AND ${table.schemaPackHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.contentHash}) = 64 AND ${table.contentHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.requestHash}) = 64 AND ${table.requestHash} NOT GLOB '*[^0-9a-f]*'`), chkActor: check("chk_personal_tax_return_artifacts_actor", sql`${table.createdByActorKind} IN ('AGENT', 'HUMAN') AND length(trim(${table.createdByActorId})) > 0`) }));

export const personalTaxReturnValidationRuns = sqliteTable("personal_tax_return_validation_runs", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), taxCaseId: text("tax_case_id").notNull(), artifactId: text("artifact_id").notNull(), artifactHash: text("artifact_hash").notNull(), schemaPackHash: text("schema_pack_hash").notNull(), validationHash: text("validation_hash").notNull(), status: text("status").notNull(), diagnosticsJson: text("diagnostics_json").notNull(), createdAt: text("created_at").notNull(), createdByActorKind: text("created_by_actor_kind").notNull(), createdByActorId: text("created_by_actor_id").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(),
}, (table) => ({ fkArtifact: foreignKey({ columns: [table.artifactId, table.tenantId, table.taxCaseId], foreignColumns: [personalTaxReturnArtifacts.id, personalTaxReturnArtifacts.tenantId, personalTaxReturnArtifacts.taxCaseId] }).onDelete("no action"), uqRequest: uniqueIndex("uq_personal_tax_return_validation_runs_request").on(table.tenantId, table.requestId), idxArtifact: index("idx_personal_tax_return_validation_runs_artifact").on(table.tenantId, table.taxCaseId, table.artifactId, table.createdAt), chkStatus: check("chk_personal_tax_return_validation_runs_status", sql`${table.status} IN ('LOCAL_VALID', 'LOCAL_INVALID')`), chkHashes: check("chk_personal_tax_return_validation_runs_hashes", sql`length(${table.artifactHash}) = 64 AND ${table.artifactHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.schemaPackHash}) = 64 AND ${table.schemaPackHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.validationHash}) = 64 AND ${table.validationHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.requestHash}) = 64 AND ${table.requestHash} NOT GLOB '*[^0-9a-f]*'`) }));

export const personalTaxReturnExportActivities = sqliteTable("personal_tax_return_export_activities", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), taxCaseId: text("tax_case_id").notNull(), artifactId: text("artifact_id").notNull(), artifactHash: text("artifact_hash").notNull(), validationHash: text("validation_hash").notNull(), actorKind: text("actor_kind").notNull(), actorId: text("actor_id").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(), createdAt: text("created_at").notNull(),
}, (table) => ({ fkArtifact: foreignKey({ columns: [table.artifactId, table.tenantId, table.taxCaseId], foreignColumns: [personalTaxReturnArtifacts.id, personalTaxReturnArtifacts.tenantId, personalTaxReturnArtifacts.taxCaseId] }).onDelete("no action"), uqRequest: uniqueIndex("uq_personal_tax_return_export_activities_request").on(table.tenantId, table.requestId), idxArtifact: index("idx_personal_tax_return_export_activities_artifact").on(table.tenantId, table.taxCaseId, table.artifactId, table.createdAt), chkActor: check("chk_personal_tax_return_export_activities_actor", sql`${table.actorKind} = 'HUMAN' AND length(trim(${table.actorId})) > 0`), chkHashes: check("chk_personal_tax_return_export_activities_hashes", sql`length(${table.artifactHash}) = 64 AND ${table.artifactHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.validationHash}) = 64 AND ${table.validationHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.requestHash}) = 64 AND ${table.requestHash} NOT GLOB '*[^0-9a-f]*'`) }));
