import { sqliteTable, text, foreignKey, uniqueIndex, index, check } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import { tenants } from "./foundation-schema";
import { taxCases, filingSnapshots, personalTaxPositionWorksheets } from "./personal-taxcase-schema";
import { personalTaxAuthorityPacks, taxCaseItrEligibilityEvaluations, taxCaseItrFormSelections } from "./personal-tax-itr-eligibility-schema";

/** Immutable, externally sourced computation rules. No tax rates are bundled here. */
export const personalTaxComputationPacks = sqliteTable("personal_tax_computation_packs", {
  id: text("id").primaryKey(), authorityPackId: text("authority_pack_id").notNull(), authorityPackHash: text("authority_pack_hash").notNull(),
  financialYear: text("financial_year").notNull(), assessmentYear: text("assessment_year").notNull(), itrForm: text("itr_form").notNull(), packVersion: text("pack_version").notNull(),
  provenanceArtifactsJson: text("provenance_artifacts_json").notNull(), declaredInputsJson: text("declared_inputs_json").notNull(), namedSchedulesJson: text("named_schedules_json").notNull(), programJson: text("program_json").notNull(), canonicalHash: text("canonical_hash").notNull(), lifecycle: text("lifecycle").notNull().default("PROPOSED"), supersedesPackId: text("supersedes_pack_id"), createdAt: text("created_at").notNull(), createdByActorKind: text("created_by_actor_kind").notNull(), createdByActorId: text("created_by_actor_id").notNull(),
}, (table) => ({
  fkAuthority: foreignKey({ columns: [table.authorityPackId], foreignColumns: [personalTaxAuthorityPacks.id] }).onDelete("no action"),
  fkSupersedes: foreignKey({ columns: [table.supersedesPackId], foreignColumns: [table.id] }).onDelete("no action"),
  uqHash: uniqueIndex("uq_personal_tax_computation_packs_hash").on(table.canonicalHash),
  uqIdentity: uniqueIndex("uq_personal_tax_computation_packs_identity").on(table.authorityPackId, table.itrForm, table.packVersion),
  idxApplicable: index("idx_personal_tax_computation_packs_applicable").on(table.financialYear, table.assessmentYear, table.itrForm, table.lifecycle),
  chkLifecycle: check("chk_personal_tax_computation_packs_lifecycle", sql`${table.lifecycle} IN ('PROPOSED','HUMAN_VERIFIED','REJECTED')`),
  chkHashes: check("chk_personal_tax_computation_packs_hashes", sql`length(${table.authorityPackHash}) = 64 AND ${table.authorityPackHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.canonicalHash}) = 64 AND ${table.canonicalHash} NOT GLOB '*[^0-9a-f]*'`),
}));

export const personalTaxComputationPackEvents = sqliteTable("personal_tax_computation_pack_events", {
  id: text("id").primaryKey(), packId: text("pack_id").notNull(), eventType: text("event_type").notNull(), actorKind: text("actor_kind").notNull(), actorId: text("actor_id").notNull(), reason: text("reason").notNull(), expectedPackHash: text("expected_pack_hash").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(), createdAt: text("created_at").notNull(),
}, (table) => ({
  fkPack: foreignKey({ columns: [table.packId], foreignColumns: [personalTaxComputationPacks.id] }).onDelete("no action"),
  uqRequest: uniqueIndex("uq_personal_tax_computation_pack_events_request").on(table.requestId), idxPack: index("idx_personal_tax_computation_pack_events_pack").on(table.packId, table.createdAt, table.id),
  chkType: check("chk_personal_tax_computation_pack_event_type", sql`${table.eventType} IN ('REGISTERED','HUMAN_VERIFIED','REJECTED','SUPERSEDED')`),
  chkActor: check("chk_personal_tax_computation_pack_event_actor", sql`${table.actorKind} IN ('AGENT','HUMAN') AND length(trim(${table.actorId})) > 0 AND (${table.eventType} IN ('REGISTERED','SUPERSEDED') OR ${table.actorKind} = 'HUMAN')`),
  chkHashes: check("chk_personal_tax_computation_pack_event_hashes", sql`length(${table.expectedPackHash}) = 64 AND ${table.expectedPackHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.requestHash}) = 64 AND ${table.requestHash} NOT GLOB '*[^0-9a-f]*'`),
}));

export const personalTaxComputationInputs = sqliteTable("personal_tax_computation_inputs", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), taxCaseId: text("tax_case_id").notNull(), filingSnapshotId: text("filing_snapshot_id").notNull(), snapshotCandidateHash: text("snapshot_candidate_hash").notNull(), worksheetId: text("worksheet_id").notNull(), worksheetOutputHash: text("worksheet_output_hash").notNull(), evaluationId: text("evaluation_id").notNull(), evaluationHash: text("evaluation_hash").notNull(), selectionId: text("selection_id").notNull(), selectionHash: text("selection_hash").notNull(), computationPackId: text("computation_pack_id").notNull(), computationPackHash: text("computation_pack_hash").notNull(), valuesJson: text("values_json").notNull(), inputHash: text("input_hash").notNull(), createdAt: text("created_at").notNull(), createdByActorKind: text("created_by_actor_kind").notNull(), createdByActorId: text("created_by_actor_id").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(),
}, (table) => ({
  fkTenant: foreignKey({ columns: [table.tenantId], foreignColumns: [tenants.id] }).onDelete("no action"), fkCase: foreignKey({ columns: [table.taxCaseId, table.tenantId], foreignColumns: [taxCases.id, taxCases.tenantId] }).onDelete("no action"), fkSnapshot: foreignKey({ columns: [table.filingSnapshotId, table.tenantId, table.taxCaseId], foreignColumns: [filingSnapshots.id, filingSnapshots.tenantId, filingSnapshots.taxCaseId] }).onDelete("no action"), fkWorksheet: foreignKey({ columns: [table.worksheetId, table.tenantId, table.taxCaseId], foreignColumns: [personalTaxPositionWorksheets.id, personalTaxPositionWorksheets.tenantId, personalTaxPositionWorksheets.taxCaseId] }).onDelete("no action"), fkEvaluation: foreignKey({ columns: [table.evaluationId, table.tenantId, table.taxCaseId], foreignColumns: [taxCaseItrEligibilityEvaluations.id, taxCaseItrEligibilityEvaluations.tenantId, taxCaseItrEligibilityEvaluations.taxCaseId] }).onDelete("no action"), fkSelection: foreignKey({ columns: [table.selectionId, table.tenantId, table.taxCaseId], foreignColumns: [taxCaseItrFormSelections.id, taxCaseItrFormSelections.tenantId, taxCaseItrFormSelections.taxCaseId] }).onDelete("no action"), fkPack: foreignKey({ columns: [table.computationPackId], foreignColumns: [personalTaxComputationPacks.id] }).onDelete("no action"),
  uqScopeKey: uniqueIndex("uq_personal_tax_computation_inputs_id_scope").on(table.id, table.tenantId, table.taxCaseId), uqRequest: uniqueIndex("uq_personal_tax_computation_inputs_request").on(table.tenantId, table.requestId), idxCase: index("idx_personal_tax_computation_inputs_case").on(table.tenantId, table.taxCaseId, table.createdAt, table.id), chkHashes: check("chk_personal_tax_computation_inputs_hashes", sql`length(${table.snapshotCandidateHash}) = 64 AND ${table.snapshotCandidateHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.worksheetOutputHash}) = 64 AND ${table.worksheetOutputHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.evaluationHash}) = 64 AND ${table.evaluationHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.selectionHash}) = 64 AND ${table.selectionHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.computationPackHash}) = 64 AND ${table.computationPackHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.inputHash}) = 64 AND ${table.inputHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.requestHash}) = 64 AND ${table.requestHash} NOT GLOB '*[^0-9a-f]*'`),
}));

export const personalTaxComputations = sqliteTable("personal_tax_computations", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), taxCaseId: text("tax_case_id").notNull(), filingSnapshotId: text("filing_snapshot_id").notNull(), snapshotCandidateHash: text("snapshot_candidate_hash").notNull(), worksheetId: text("worksheet_id").notNull(), worksheetOutputHash: text("worksheet_output_hash").notNull(), evaluationId: text("evaluation_id").notNull(), evaluationHash: text("evaluation_hash").notNull(), selectionId: text("selection_id").notNull(), selectionHash: text("selection_hash").notNull(), computationPackId: text("computation_pack_id").notNull(), computationPackHash: text("computation_pack_hash").notNull(), inputSetId: text("input_set_id").notNull(), inputHash: text("input_hash").notNull(), computationHash: text("computation_hash").notNull(), stepTraceJson: text("step_trace_json").notNull(), namedSchedulesJson: text("named_schedules_json").notNull(), grossTaxMinor: text("gross_tax_minor").notNull(), creditsMinor: text("credits_minor").notNull(), netPayableMinor: text("net_payable_minor"), refundMinor: text("refund_minor"), lifecycle: text("lifecycle").notNull().default("GENERATED"), createdAt: text("created_at").notNull(), createdByActorKind: text("created_by_actor_kind").notNull(), createdByActorId: text("created_by_actor_id").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(),
}, (table) => ({
  fkTenant: foreignKey({ columns: [table.tenantId], foreignColumns: [tenants.id] }).onDelete("no action"), fkCase: foreignKey({ columns: [table.taxCaseId, table.tenantId], foreignColumns: [taxCases.id, taxCases.tenantId] }).onDelete("no action"), fkInputs: foreignKey({ columns: [table.inputSetId, table.tenantId, table.taxCaseId], foreignColumns: [personalTaxComputationInputs.id, personalTaxComputationInputs.tenantId, personalTaxComputationInputs.taxCaseId] }).onDelete("no action"), fkPack: foreignKey({ columns: [table.computationPackId], foreignColumns: [personalTaxComputationPacks.id] }).onDelete("no action"),
  uqScopeKey: uniqueIndex("uq_personal_tax_computations_id_scope").on(table.id, table.tenantId, table.taxCaseId), uqRequest: uniqueIndex("uq_personal_tax_computations_request").on(table.tenantId, table.requestId), idxCase: index("idx_personal_tax_computations_case").on(table.tenantId, table.taxCaseId, table.createdAt, table.id), chkHashes: check("chk_personal_tax_computations_hashes", sql`length(${table.computationPackHash}) = 64 AND ${table.computationPackHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.inputHash}) = 64 AND ${table.inputHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.computationHash}) = 64 AND ${table.computationHash} NOT GLOB '*[^0-9a-f]*' AND ((net_payable_minor IS NULL AND refund_minor IS NOT NULL) OR (net_payable_minor IS NOT NULL AND refund_minor IS NULL))`),
}));

export const personalTaxComputationEvents = sqliteTable("personal_tax_computation_events", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), taxCaseId: text("tax_case_id").notNull(), computationId: text("computation_id").notNull(), eventType: text("event_type").notNull(), actorKind: text("actor_kind").notNull(), actorId: text("actor_id").notNull(), reason: text("reason").notNull(), expectedComputationHash: text("expected_computation_hash").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(), createdAt: text("created_at").notNull(),
}, (table) => ({ fkTenant: foreignKey({ columns: [table.tenantId], foreignColumns: [tenants.id] }).onDelete("no action"), fkComputation: foreignKey({ columns: [table.computationId, table.tenantId, table.taxCaseId], foreignColumns: [personalTaxComputations.id, personalTaxComputations.tenantId, personalTaxComputations.taxCaseId] }).onDelete("no action"), uqRequest: uniqueIndex("uq_personal_tax_computation_events_request").on(table.tenantId, table.requestId), idxComputation: index("idx_personal_tax_computation_events_computation").on(table.tenantId, table.taxCaseId, table.computationId, table.createdAt), chkType: check("chk_personal_tax_computation_event_type", sql`${table.eventType} IN ('APPROVED')`), chkActor: check("chk_personal_tax_computation_event_actor", sql`${table.actorKind} = 'HUMAN' AND length(trim(${table.actorId})) > 0`), chkHash: check("chk_personal_tax_computation_event_hash", sql`length(${table.expectedComputationHash}) = 64 AND ${table.expectedComputationHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.requestHash}) = 64 AND ${table.requestHash} NOT GLOB '*[^0-9a-f]*'`) }));
