import { sqliteTable, text, integer, foreignKey, uniqueIndex, index, check } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import { tenants, bookSets } from "./foundation-schema.ts";
import { sourceRegistrations } from "./source-registry-schema.ts";

export const sourceStagingBatches = sqliteTable("source_staging_batches", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), sourceId: text("source_id").notNull(),
  sourceLocator: text("source_locator").notNull(), parserId: text("parser_id").notNull(), parserVersion: text("parser_version").notNull(), schemaFingerprint: text("schema_fingerprint").notNull(), headerFingerprint: text("header_fingerprint").notNull(),
  sourcePeriodStart: text("source_period_start"), sourcePeriodEnd: text("source_period_end"), outcome: text("outcome").notNull(), reportJson: text("report_json").notNull(), reportHash: text("report_hash").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(), createdAt: text("created_at").notNull(),
}, (table) => ({
  tenant: foreignKey({ columns: [table.tenantId], foreignColumns: [tenants.id] }), bookSet: foreignKey({ columns: [table.bookSetId, table.tenantId], foreignColumns: [bookSets.id, bookSets.tenantId] }), source: foreignKey({ columns: [table.sourceId, table.tenantId, table.bookSetId], foreignColumns: [sourceRegistrations.id, sourceRegistrations.tenantId, sourceRegistrations.bookSetId] }),
  scopeId: uniqueIndex("uq_source_staging_batches_scope_id").on(table.id, table.tenantId, table.bookSetId), sourceParser: uniqueIndex("uq_source_staging_source_parser").on(table.tenantId, table.bookSetId, table.sourceId, table.parserId, table.parserVersion), request: uniqueIndex("uq_source_staging_request").on(table.tenantId, table.requestId), scope: index("idx_source_staging_batches_scope").on(table.tenantId, table.bookSetId, table.createdAt),
  outcomeCheck: check("chk_source_staging_batch_outcome", sql`${table.outcome} IN ('STAGED','UNSUPPORTED','REJECTED')`), hashes: check("chk_source_staging_batch_hashes", sql`length(${table.schemaFingerprint}) = 64 AND ${table.schemaFingerprint} NOT GLOB '*[^0-9a-f]*' AND length(${table.headerFingerprint}) = 64 AND ${table.headerFingerprint} NOT GLOB '*[^0-9a-f]*' AND length(${table.reportHash}) = 64 AND ${table.reportHash} NOT GLOB '*[^0-9a-f]*' AND length(${table.requestHash}) = 64 AND ${table.requestHash} NOT GLOB '*[^0-9a-f]*'`),
}));

export const sourceStagingFiles = sqliteTable("source_staging_files", {
  id: text("id").primaryKey(), batchId: text("batch_id").notNull(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), sourceId: text("source_id").notNull(), sourceLocator: text("source_locator").notNull(), contentHash: text("content_hash").notNull(), parserId: text("parser_id").notNull(), parserVersion: text("parser_version").notNull(), pageCount: integer("page_count").notNull(),
}, (table) => ({ batch: foreignKey({ columns: [table.batchId, table.tenantId, table.bookSetId], foreignColumns: [sourceStagingBatches.id, sourceStagingBatches.tenantId, sourceStagingBatches.bookSetId] }), source: foreignKey({ columns: [table.sourceId, table.tenantId, table.bookSetId], foreignColumns: [sourceRegistrations.id, sourceRegistrations.tenantId, sourceRegistrations.bookSetId] }), scopeId: uniqueIndex("uq_source_staging_files_scope_id").on(table.id, table.tenantId, table.bookSetId), uniqueFile: uniqueIndex("uq_source_staging_file").on(table.batchId, table.sourceId, table.contentHash), scope: index("idx_source_staging_files_scope").on(table.tenantId, table.bookSetId), hashes: check("chk_source_staging_file_hash", sql`length(${table.contentHash}) = 64 AND ${table.contentHash} NOT GLOB '*[^0-9a-f]*'`), pageCheck: check("chk_source_staging_file_pages", sql`typeof(${table.pageCount}) = 'integer' AND ${table.pageCount} >= 0`) }));

export const sourceStagingRows = sqliteTable("source_staging_rows", {
  id: text("id").primaryKey(), batchId: text("batch_id").notNull(), fileId: text("file_id").notNull(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), sourceId: text("source_id").notNull(), rowNumber: integer("row_number"), pageNumber: integer("page_number"), outcome: text("outcome").notNull(), reason: text("reason").notNull(), provenanceJson: text("provenance_json").notNull(), rowHash: text("row_hash").notNull(),
}, (table) => ({ batch: foreignKey({ columns: [table.batchId, table.tenantId, table.bookSetId], foreignColumns: [sourceStagingBatches.id, sourceStagingBatches.tenantId, sourceStagingBatches.bookSetId] }), file: foreignKey({ columns: [table.fileId, table.tenantId, table.bookSetId], foreignColumns: [sourceStagingFiles.id, sourceStagingFiles.tenantId, sourceStagingFiles.bookSetId] }), source: foreignKey({ columns: [table.sourceId, table.tenantId, table.bookSetId], foreignColumns: [sourceRegistrations.id, sourceRegistrations.tenantId, sourceRegistrations.bookSetId] }), scopeId: uniqueIndex("uq_source_staging_rows_scope_id").on(table.id, table.tenantId, table.bookSetId), position: uniqueIndex("uq_source_staging_row_position").on(table.batchId, table.sourceId, table.rowNumber, table.pageNumber), scope: index("idx_source_staging_rows_scope").on(table.tenantId, table.bookSetId, table.batchId), outcomeCheck: check("chk_source_staging_row_outcome", sql`${table.outcome} IN ('STAGED','UNSUPPORTED','REJECTED')`), positionCheck: check("chk_source_staging_row_position_values", sql`(${table.rowNumber} IS NULL OR (${table.rowNumber} >= 1 AND typeof(${table.rowNumber}) = 'integer')) AND (${table.pageNumber} IS NULL OR (${table.pageNumber} >= 1 AND typeof(${table.pageNumber}) = 'integer'))`), hashCheck: check("chk_source_staging_row_hash", sql`length(${table.rowHash}) = 64 AND ${table.rowHash} NOT GLOB '*[^0-9a-f]*'`) }));

export const sourceStagingFacts = sqliteTable("source_staging_facts", {
  id: text("id").primaryKey(), rowId: text("row_id").notNull(), batchId: text("batch_id").notNull(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), sourceId: text("source_id").notNull(), factType: text("fact_type").notNull(), factJson: text("fact_json").notNull(), factHash: text("fact_hash").notNull(),
}, (table) => ({ row: foreignKey({ columns: [table.rowId, table.tenantId, table.bookSetId], foreignColumns: [sourceStagingRows.id, sourceStagingRows.tenantId, sourceStagingRows.bookSetId] }), batch: foreignKey({ columns: [table.batchId, table.tenantId, table.bookSetId], foreignColumns: [sourceStagingBatches.id, sourceStagingBatches.tenantId, sourceStagingBatches.bookSetId] }), source: foreignKey({ columns: [table.sourceId, table.tenantId, table.bookSetId], foreignColumns: [sourceRegistrations.id, sourceRegistrations.tenantId, sourceRegistrations.bookSetId] }), uniqueFact: uniqueIndex("uq_source_staging_fact").on(table.rowId, table.factType), scope: index("idx_source_staging_facts_scope").on(table.tenantId, table.bookSetId, table.batchId), hashCheck: check("chk_source_staging_fact_hash", sql`length(${table.factHash}) = 64 AND ${table.factHash} NOT GLOB '*[^0-9a-f]*'`) }));
