import { sqliteTable, text, integer, foreignKey, uniqueIndex, index, check } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import { tenants, bookSets } from "./foundation-schema";
import { tenantDeductorProfiles, withholdingDeposits } from "./tds-tcs-schema";

/** Immutable, human-gated quarterly TDS/TCS statement packs, facts and artifacts. */
export const withholdingStatementSchemaPacks = sqliteTable("withholding_statement_schema_packs", {
  id: text("id").primaryKey(), jurisdiction: text("jurisdiction").notNull(), form: text("form").notNull(), financialYear: text("financial_year").notNull(), quarter: text("quarter").notNull(), filingType: text("filing_type").notNull(), authorityRuleSnapshotReference: text("authority_rule_snapshot_reference").notNull(), artifactReferencesJson: text("artifact_references_json").notNull(), packVersion: text("pack_version").notNull(), validationSchemaJson: text("validation_schema_json").notNull(), mappingSpecJson: text("mapping_spec_json").notNull(), canonicalHash: text("canonical_hash").notNull(), supersedesPackId: text("supersedes_pack_id"), createdAt: text("created_at").notNull(), createdByActorKind: text("created_by_actor_kind").notNull(), createdByActorId: text("created_by_actor_id").notNull(),
}, (t) => ({
  fkSupersedes: foreignKey({ columns: [t.supersedesPackId], foreignColumns: [t.id] }).onDelete("no action"),
  uqHash: uniqueIndex("uq_withholding_statement_schema_packs_hash").on(t.canonicalHash),
  uqIdentity: uniqueIndex("uq_withholding_statement_schema_packs_identity").on(t.jurisdiction, t.form, t.financialYear, t.quarter, t.filingType, t.packVersion),
  idxApplicable: index("idx_withholding_statement_schema_packs_applicable").on(t.jurisdiction, t.form, t.financialYear, t.quarter, t.filingType),
  chkIdentity: check("chk_withholding_statement_schema_packs_identity", sql`${t.jurisdiction} = 'IN' AND ${t.form} IN ('24Q','26Q','27Q','27EQ') AND ${t.quarter} IN ('Q1','Q2','Q3','Q4') AND ${t.filingType} IN ('ORIGINAL','CORRECTION')`),
  chkHashes: check("chk_withholding_statement_schema_packs_hashes", sql`length(${t.canonicalHash}) = 64 AND ${t.canonicalHash} NOT GLOB '*[^0-9a-f]*'`),
  chkActor: check("chk_withholding_statement_schema_packs_actor", sql`${t.createdByActorKind} IN ('AGENT','HUMAN') AND length(trim(${t.createdByActorId})) > 0`),
}));

export const withholdingStatementSchemaPackEvents = sqliteTable("withholding_statement_schema_pack_events", {
  id: text("id").primaryKey(), packId: text("pack_id").notNull(), eventType: text("event_type").notNull(), actorKind: text("actor_kind").notNull(), actorId: text("actor_id").notNull(), reason: text("reason").notNull(), expectedPackHash: text("expected_pack_hash").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({
  fkPack: foreignKey({ columns: [t.packId], foreignColumns: [withholdingStatementSchemaPacks.id] }).onDelete("no action"), uqRequest: uniqueIndex("uq_withholding_statement_schema_pack_events_request").on(t.requestId), idxPack: index("idx_withholding_statement_schema_pack_events_pack").on(t.packId, t.createdAt, t.id),
  chkType: check("chk_withholding_statement_schema_pack_event_type", sql`${t.eventType} IN ('REGISTERED','HUMAN_VERIFIED','REJECTED','SUPERSEDED')`), chkActor: check("chk_withholding_statement_schema_pack_event_actor", sql`${t.actorKind} IN ('AGENT','HUMAN') AND length(trim(${t.actorId})) > 0 AND (${t.eventType} IN ('REGISTERED','SUPERSEDED') OR ${t.actorKind} = 'HUMAN')`), chkHashes: check("chk_withholding_statement_schema_pack_event_hashes", sql`length(${t.expectedPackHash}) = 64 AND ${t.expectedPackHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.requestHash}) = 64 AND ${t.requestHash} NOT GLOB '*[^0-9a-f]*'`),
}));

export const withholdingStatementFacts = sqliteTable("withholding_statement_facts", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), deductorProfileId: text("deductor_profile_id").notNull(), financialYear: text("financial_year").notNull(), quarter: text("quarter").notNull(), factType: text("fact_type").notNull(), depositId: text("deposit_id"), tanPanProfileReference: text("tan_pan_profile_reference"), responsiblePersonJson: text("responsible_person_json"), challanJson: text("challan_json"), deducteeClassification: text("deductee_classification"), remittanceJson: text("remittance_json"), correctionLinkage: text("correction_linkage"), nilStatementAssertion: integer("nil_statement_assertion").notNull().default(0), allocationsJson: text("allocations_json").notNull(), factsJson: text("facts_json").notNull(), canonicalHash: text("canonical_hash").notNull(), createdAt: text("created_at").notNull(), createdByActorKind: text("created_by_actor_kind").notNull(), createdByActorId: text("created_by_actor_id").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(),
}, (t) => ({
  fkTenant: foreignKey({ columns: [t.tenantId], foreignColumns: [tenants.id] }).onDelete("no action"), fkBookSet: foreignKey({ columns: [t.bookSetId, t.tenantId], foreignColumns: [bookSets.id, bookSets.tenantId] }).onDelete("no action"), fkDeductor: foreignKey({ columns: [t.deductorProfileId, t.tenantId], foreignColumns: [tenantDeductorProfiles.id, tenantDeductorProfiles.tenantId] }).onDelete("no action"), fkDeposit: foreignKey({ columns: [t.depositId, t.tenantId, t.bookSetId], foreignColumns: [withholdingDeposits.id, withholdingDeposits.tenantId, withholdingDeposits.bookSetId] }).onDelete("no action"), uqScopeHash: uniqueIndex("uq_withholding_statement_facts_scope_hash").on(t.tenantId, t.bookSetId, t.canonicalHash), uqRequest: uniqueIndex("uq_withholding_statement_facts_request").on(t.tenantId, t.requestId), idxScope: index("idx_withholding_statement_facts_scope_period").on(t.tenantId, t.bookSetId, t.deductorProfileId, t.financialYear, t.quarter, t.factType), chkType: check("chk_withholding_statement_facts_type", sql`${t.factType} IN ('CHALLAN','RESPONSIBLE_PERSON','DEDUCTEE_CLASSIFICATION','NIL_STATEMENT','REMITTANCE','CORRECTION')`), chkQuarter: check("chk_withholding_statement_facts_quarter", sql`${t.quarter} IN ('Q1','Q2','Q3','Q4')`), chkNil: check("chk_withholding_statement_facts_nil", sql`${t.nilStatementAssertion} IN (0,1)`), chkHashes: check("chk_withholding_statement_facts_hashes", sql`length(${t.canonicalHash}) = 64 AND ${t.canonicalHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.requestHash}) = 64 AND ${t.requestHash} NOT GLOB '*[^0-9a-f]*'`), chkActor: check("chk_withholding_statement_facts_actor", sql`${t.createdByActorKind} IN ('AGENT','HUMAN') AND length(trim(${t.createdByActorId})) > 0`),
  uqScopeId: uniqueIndex("uq_withholding_statement_facts_id_scope").on(t.id, t.tenantId, t.bookSetId),
}));

export const withholdingStatementFactEvents = sqliteTable("withholding_statement_fact_events", {
  id: text("id").primaryKey(), factId: text("fact_id").notNull(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), eventType: text("event_type").notNull(), actorKind: text("actor_kind").notNull(), actorId: text("actor_id").notNull(), reason: text("reason").notNull(), expectedFactHash: text("expected_fact_hash").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({ fkFact: foreignKey({ columns: [t.factId, t.tenantId, t.bookSetId], foreignColumns: [withholdingStatementFacts.id, withholdingStatementFacts.tenantId, withholdingStatementFacts.bookSetId] }).onDelete("no action"), uqRequest: uniqueIndex("uq_withholding_statement_fact_events_request").on(t.tenantId, t.requestId), idxFact: index("idx_withholding_statement_fact_events_fact").on(t.tenantId, t.bookSetId, t.factId, t.createdAt), chkType: check("chk_withholding_statement_fact_event_type", sql`${t.eventType} IN ('PROPOSED','HUMAN_CONFIRMED','HUMAN_REJECTED')`), chkActor: check("chk_withholding_statement_fact_event_actor", sql`${t.actorKind} IN ('AGENT','HUMAN') AND length(trim(${t.actorId})) > 0 AND (${t.eventType} = 'PROPOSED' OR ${t.actorKind} = 'HUMAN')`), chkHashes: check("chk_withholding_statement_fact_event_hashes", sql`length(${t.expectedFactHash}) = 64 AND ${t.expectedFactHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.requestHash}) = 64 AND ${t.requestHash} NOT GLOB '*[^0-9a-f]*'`) }));

export const withholdingStatementArtifacts = sqliteTable("withholding_statement_artifacts", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), deductorProfileId: text("deductor_profile_id").notNull(), form: text("form").notNull(), financialYear: text("financial_year").notNull(), quarter: text("quarter").notNull(), filingType: text("filing_type").notNull(), schemaPackId: text("schema_pack_id").notNull(), schemaPackHash: text("schema_pack_hash").notNull(), sourceModelHash: text("source_model_hash").notNull(), contentType: text("content_type").notNull(), contentText: text("content_text").notNull(), contentByteLength: integer("content_byte_length").notNull(), contentHash: text("content_hash").notNull(), bindingsJson: text("bindings_json").notNull(), createdAt: text("created_at").notNull(), createdByActorKind: text("created_by_actor_kind").notNull(), createdByActorId: text("created_by_actor_id").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(),
}, (t) => ({ fkTenant: foreignKey({ columns: [t.tenantId], foreignColumns: [tenants.id] }).onDelete("no action"), fkBookSet: foreignKey({ columns: [t.bookSetId, t.tenantId], foreignColumns: [bookSets.id, bookSets.tenantId] }).onDelete("no action"), fkDeductor: foreignKey({ columns: [t.deductorProfileId, t.tenantId], foreignColumns: [tenantDeductorProfiles.id, tenantDeductorProfiles.tenantId] }).onDelete("no action"), fkPack: foreignKey({ columns: [t.schemaPackId], foreignColumns: [withholdingStatementSchemaPacks.id] }).onDelete("no action"), uqScopeHash: uniqueIndex("uq_withholding_statement_artifacts_scope_hash").on(t.tenantId, t.bookSetId, t.form, t.financialYear, t.quarter, t.filingType, t.contentHash), uqRequest: uniqueIndex("uq_withholding_statement_artifacts_request").on(t.tenantId, t.requestId), uqScopeId: uniqueIndex("uq_withholding_statement_artifacts_id_scope").on(t.id, t.tenantId, t.bookSetId), idxScope: index("idx_withholding_statement_artifacts_scope").on(t.tenantId, t.bookSetId, t.form, t.financialYear, t.quarter, t.createdAt), chkForm: check("chk_withholding_statement_artifacts_form", sql`${t.form} IN ('24Q','26Q','27Q','27EQ') AND ${t.quarter} IN ('Q1','Q2','Q3','Q4')`), chkHashes: check("chk_withholding_statement_artifacts_hashes", sql`length(${t.schemaPackHash}) = 64 AND ${t.schemaPackHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.sourceModelHash}) = 64 AND ${t.sourceModelHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.contentHash}) = 64 AND ${t.contentHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.requestHash}) = 64 AND ${t.requestHash} NOT GLOB '*[^0-9a-f]*'`), chkActor: check("chk_withholding_statement_artifacts_actor", sql`${t.createdByActorKind} IN ('AGENT','HUMAN') AND length(trim(${t.createdByActorId})) > 0`) }));

export const withholdingStatementValidationRuns = sqliteTable("withholding_statement_validation_runs", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), artifactId: text("artifact_id").notNull(), artifactHash: text("artifact_hash").notNull(), schemaPackHash: text("schema_pack_hash").notNull(), validationHash: text("validation_hash").notNull(), status: text("status").notNull(), diagnosticsJson: text("diagnostics_json").notNull(), createdAt: text("created_at").notNull(), createdByActorKind: text("created_by_actor_kind").notNull(), createdByActorId: text("created_by_actor_id").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(),
}, (t) => ({ fkArtifact: foreignKey({ columns: [t.artifactId, t.tenantId, t.bookSetId], foreignColumns: [withholdingStatementArtifacts.id, withholdingStatementArtifacts.tenantId, withholdingStatementArtifacts.bookSetId] }).onDelete("no action"), uqRequest: uniqueIndex("uq_withholding_statement_validation_runs_request").on(t.tenantId, t.requestId), idxArtifact: index("idx_withholding_statement_validation_runs_artifact").on(t.tenantId, t.bookSetId, t.artifactId, t.createdAt), chkStatus: check("chk_withholding_statement_validation_runs_status", sql`${t.status} IN ('LOCAL_VALID','LOCAL_INVALID')`), chkHashes: check("chk_withholding_statement_validation_runs_hashes", sql`length(${t.artifactHash}) = 64 AND ${t.artifactHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.schemaPackHash}) = 64 AND ${t.schemaPackHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.validationHash}) = 64 AND ${t.validationHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.requestHash}) = 64 AND ${t.requestHash} NOT GLOB '*[^0-9a-f]*'`) }));

export const withholdingStatementExportActivities = sqliteTable("withholding_statement_export_activities", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), bookSetId: text("book_set_id").notNull(), artifactId: text("artifact_id").notNull(), artifactHash: text("artifact_hash").notNull(), validationHash: text("validation_hash").notNull(), actorKind: text("actor_kind").notNull(), actorId: text("actor_id").notNull(), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(), createdAt: text("created_at").notNull(),
}, (t) => ({ fkArtifact: foreignKey({ columns: [t.artifactId, t.tenantId, t.bookSetId], foreignColumns: [withholdingStatementArtifacts.id, withholdingStatementArtifacts.tenantId, withholdingStatementArtifacts.bookSetId] }).onDelete("no action"), uqRequest: uniqueIndex("uq_withholding_statement_export_activities_request").on(t.tenantId, t.requestId), idxArtifact: index("idx_withholding_statement_export_activities_artifact").on(t.tenantId, t.bookSetId, t.artifactId, t.createdAt), chkActor: check("chk_withholding_statement_export_activities_actor", sql`${t.actorKind} = 'HUMAN' AND length(trim(${t.actorId})) > 0`), chkHashes: check("chk_withholding_statement_export_activities_hashes", sql`length(${t.artifactHash}) = 64 AND ${t.artifactHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.validationHash}) = 64 AND ${t.validationHash} NOT GLOB '*[^0-9a-f]*' AND length(${t.requestHash}) = 64 AND ${t.requestHash} NOT GLOB '*[^0-9a-f]*'`) }));
