import { describe, expect, test } from "bun:test";
import { randomUUID } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { join } from "node:path";
import { createSqliteApplication, initializeAndUpgradeSqliteApplication } from "../../src/application/application.ts";
import { brandTenantId } from "../../src/core/types.ts";

type App = ReturnType<typeof createSqliteApplication>;
const artifacts = ["LAW", "RULES", "SCHEMA", "INSTRUCTION"].map((kind) => ({ kind, sourceUrl: "https://example.invalid/test-only", sourceTitle: "TEST_ONLY", officialReleaseIdentifier: "TEST_ONLY", officialReleaseDate: "2024-04-01", sha256: "b".repeat(64) }));
const envelope = (tenantId: string, requestId: string, payload: unknown, kind: "HUMAN" | "AGENT" = "HUMAN"): any => ({ schemaVersion: 1 as const, tenantId, requestId, actor: { kind, id: `${kind.toLowerCase()}-computation-test` }, source: "CLI" as const, reason: "TEST_ONLY computation workpaper", payload });

async function setup(app: App): Promise<{ tenantId: ReturnType<typeof brandTenantId>; taxCaseId: string; snapshotId: string; snapshotHash: string; worksheetId: string; worksheetHash: string }> {
  const tenant = JSON.parse((await app.tenant.create(envelope("bootstrap-computation", randomUUID(), { kind: "INDIVIDUAL", name: "TEST_ONLY computation taxpayer" }))).resultJson);
  await app.tenant.activate(envelope(tenant.tenantId, randomUUID(), { defaultBookSetId: tenant.defaultBookSetId }));
  await app.tenant.pan.set(envelope(tenant.tenantId, randomUUID(), { pan: "ABCDE1234F" }));
  const taxCaseId = "computation-case";
  await app.taxCase.create(envelope(tenant.tenantId, randomUUID(), { taxCaseId, financialYear: "2024-25", taxPeriod: "2024-25", filingTrigger: "ANNUAL", bookSetIds: [tenant.defaultBookSetId] }));
  const candidate = await app.taxCase.filingSnapshot.preview(tenant.tenantId, taxCaseId); const snapshot = JSON.parse((await app.taxCase.filingSnapshot.seal(envelope(tenant.tenantId, "computation-seal", { taxCaseId, candidateHash: candidate.candidateHash })).then((r) => r.resultJson)));
  const worksheet = JSON.parse((await app.taxCase.position.generate(envelope(tenant.tenantId, "computation-worksheet", { taxCaseId, filingSnapshotId: snapshot.snapshotId }, "AGENT")).then((r) => r.resultJson)));
  return { tenantId: brandTenantId(tenant.tenantId), taxCaseId, snapshotId: snapshot.snapshotId, snapshotHash: snapshot.candidateHash, worksheetId: worksheet.worksheetId, worksheetHash: worksheet.canonicalOutputHash };
}

test("Personal Tax Computation Workpaper V1 is exact, BigInt-safe, immutable, and human-approved", async () => {
  const directory = await mkdtemp(join(process.env.TMPDIR ?? "/tmp", "agent-bahi-computation-")); const app = await initializeAndUpgradeSqliteApplication(join(directory, "books.sqlite"), { backupDestinationPath: join(directory, "bootstrap.sqlite") });
  try {
    const scope = await setup(app); const authority = JSON.parse((await app.taxAuthority.pack.register(envelope(scope.tenantId, "authority-register", { jurisdiction: "IN", authority: "INCOME_TAX", financialYear: "2024-25", assessmentYear: "2025-26", filingTypes: ["ANNUAL"], effectiveFrom: "2024-04-01", releasedAt: "2024-04-01", releaseIdentifier: "TEST_ONLY", artifactReferences: artifacts, packVersion: "TEST_ONLY-authority", candidateForms: ["ITR-1"], ruleAst: { forms: [{ form: "ITR-1", rule: { op: "eq", field: "is_resident", value: true } }] } }, "AGENT"))).resultJson);
    await app.taxAuthority.pack.verify(envelope(scope.tenantId, "authority-verify", { packId: authority.packId, expectedPackHash: authority.canonicalHash, reason: "TEST_ONLY human verification" }));
    await app.taxCase.eligibilityFacts.record(envelope(scope.tenantId, "eligibility-fact", { taxCaseId: scope.taxCaseId, filingSnapshotId: scope.snapshotId, worksheetId: scope.worksheetId, snapshotCandidateHash: scope.snapshotHash, worksheetOutputHash: scope.worksheetHash, fieldName: "is_resident", valueType: "BOOLEAN", value: true, provenanceKind: "HUMAN_ASSERTION", provenance: { source: "TEST_ONLY" } }));
    const evaluation = JSON.parse((await app.taxCase.itrEligibility.evaluate(envelope(scope.tenantId, "eligibility-evaluate", { taxCaseId: scope.taxCaseId, filingSnapshotId: scope.snapshotId, worksheetId: scope.worksheetId, packId: authority.packId }, "AGENT")).then((r) => r.resultJson))); const selection = JSON.parse((await app.taxCase.itrForm.select(envelope(scope.tenantId, "form-select", { taxCaseId: scope.taxCaseId, evaluationId: evaluation.evaluationId, expectedEvaluationHash: evaluation.evaluationHash, selectedForm: "ITR-1" })).then((r) => r.resultJson)));
    const program = { nodes: [{ name: "gross", op: "constant", value: "10000000000000000001" }, { name: "credits", op: "input", field: "tax_credits_minor" }, { name: "net", op: "subtract", args: ["gross", "credits"] }, { name: "grossfinal", op: "final", arg: "gross" }, { name: "creditsfinal", op: "final", arg: "credits" }, { name: "netfinal", op: "final", arg: "net" }], outputs: [{ name: "grossTaxMinor", ref: "grossfinal" }, { name: "creditsMinor", ref: "creditsfinal" }, { name: "netPayableMinor", ref: "netfinal" }] };
    const computationPack = JSON.parse((await app.taxAuthority.computationPack.register(envelope(scope.tenantId, "computation-pack-register", { authorityPackId: authority.packId, authorityPackHash: authority.canonicalHash, financialYear: "2024-25", assessmentYear: "2025-26", itrForm: "ITR-1", packVersion: "TEST_ONLY-computation", provenanceArtifacts: artifacts, declaredInputs: [{ name: "is_resident", valueType: "BOOLEAN" }], namedSchedules: ["TEST_ONLY"], program }, "AGENT")).then((r) => r.resultJson)));
    await app.taxAuthority.computationPack.verify(envelope(scope.tenantId, "computation-pack-verify", { packId: computationPack.packId, expectedPackHash: computationPack.canonicalHash, reason: "TEST_ONLY human verification" }));
    const inputs = JSON.parse((await app.taxCase.computationInputs.record(envelope(scope.tenantId, "computation-inputs", { taxCaseId: scope.taxCaseId, filingSnapshotId: scope.snapshotId, worksheetId: scope.worksheetId, evaluationId: evaluation.evaluationId, selectionId: selection.selectionId, computationPackId: computationPack.packId, inputs: { is_resident: { valueType: "BOOLEAN", value: true, provenance: { source: "TEST_ONLY" }, verified: true } } })).then((r) => r.resultJson)));
    const preview = await app.taxCase.computation.preview(scope.tenantId, { taxCaseId: scope.taxCaseId, filingSnapshotId: scope.snapshotId, worksheetId: scope.worksheetId, evaluationId: evaluation.evaluationId, selectionId: selection.selectionId, computationPackId: computationPack.packId, inputs: { is_resident: { valueType: "BOOLEAN", value: true, provenance: { source: "TEST_ONLY" }, verified: true } } }); expect(preview.workpaper).toBe("WORKPAPER_NOT_RETURN"); expect(preview.grossTaxMinor).toBe("10000000000000000001");
    const generated = JSON.parse((await app.taxCase.computation.generate(envelope(scope.tenantId, "computation-generate", { taxCaseId: scope.taxCaseId, filingSnapshotId: scope.snapshotId, worksheetId: scope.worksheetId, evaluationId: evaluation.evaluationId, selectionId: selection.selectionId, computationPackId: computationPack.packId, inputSetId: inputs.inputSetId, inputs: { is_resident: { valueType: "BOOLEAN", value: true, provenance: { source: "TEST_ONLY" }, verified: true } } }, "AGENT")).then((r) => r.resultJson))); expect(generated.netPayableMinor).toBe("10000000000000000001"); await expect(app.taxCase.computation.approve(envelope(scope.tenantId, "agent-approve", { taxCaseId: scope.taxCaseId, computationId: generated.computationId, expectedComputationHash: generated.computationHash, reason: "agent" }, "AGENT"))).rejects.toMatchObject({ code: "TAX_COMPUTATION_APPROVAL_HUMAN_REQUIRED" }); const approved = await app.taxCase.computation.approve(envelope(scope.tenantId, "human-approve", { taxCaseId: scope.taxCaseId, computationId: generated.computationId, expectedComputationHash: generated.computationHash, reason: "human approved TEST_ONLY workpaper" })); expect(JSON.parse(approved.resultJson).status).toBe("APPROVED");
  } finally { await rm(directory, { recursive: true, force: true }); }
});
