import { createHash, randomUUID } from "node:crypto";
import type { BusinessSession, BusinessSessionRunner } from "../ports/persistence.ts";
import type { AuthorityArtifactReference, CommandEnvelope, CommandResult, ReturnArtifactBindingPayload, ReturnArtifactExportPayload, ReturnArtifactValidatePayload, ReturnSchemaPackDecisionPayload, ReturnSchemaPackRegisterPayload } from "../commands.ts";
import { canonicalJson, computeCommandHash, computeResultHash } from "../commands.ts";
import { DomainError, IdempotencyConflictError, IdempotencyCorruptError } from "../../core/types.ts";
import { validateCommandEnvelope } from "./bookset-command-service.ts";
import { filingSnapshotStateInSession } from "./tax-case-filing-snapshot-service.ts";
import { evaluateMapping as sharedEvaluateMapping, validateMapping as sharedValidateMapping, validateSchema as sharedValidateSchema, validateValue as sharedValidateValue } from "./return-artifact-engine.ts";

const REGISTER = "tax-authority.return-schema-pack.register";
const VERIFY = "tax-authority.return-schema-pack.verify";
const REJECT = "tax-authority.return-schema-pack.reject";
const PREPARE = "tax-case.return-artifact.prepare";
const VALIDATE = "tax-case.return-artifact.validate";
const EXPORT = "tax-case.return-artifact.export";
const SHA = /^[0-9a-f]{64}$/;
const MAX_JSON = 256_000;
const MAX_DEPTH = 16;
const MAX_NODES = 512;
const MAX_DIAGNOSTICS = 128;
type JsonObject = Record<string, unknown>;
type Schema = JsonObject;
type Mapping = JsonObject;

function text(value: unknown, field: string, max = 256): string {
  if (typeof value !== "string" || value.trim() === "") throw new DomainError("INVALID_RETURN_ARTIFACT_INPUT", `${field} must be a nonblank string`);
  const result = value.trim();
  if (result.length > max) throw new DomainError("INVALID_RETURN_ARTIFACT_INPUT", `${field} exceeds the V1 length limit`);
  return result;
}
function sha(value: unknown, field: string): string { const result = text(value, field, 64).toLowerCase(); if (!SHA.test(result)) throw new DomainError("INVALID_RETURN_ARTIFACT_HASH", `${field} must be lowercase SHA-256`); return result; }
function object(value: unknown, field: string): JsonObject { if (!value || typeof value !== "object" || Array.isArray(value)) throw new DomainError("INVALID_RETURN_ARTIFACT_SCHEMA", `${field} must be an object`); return value as JsonObject; }
function boundedJson(value: unknown, field: string, max = MAX_JSON): string { const result = canonicalJson(value); if (result.length > max) throw new DomainError("RETURN_ARTIFACT_PAYLOAD_TOO_LARGE", `${field} exceeds the V1 size limit`); return result; }
function hash(value: unknown): string { return createHash("sha256").update(canonicalJson(value)).digest("hex"); }
function keysOnly(row: JsonObject, allowed: readonly string[], field: string): void { if (Object.keys(row).some((key) => !allowed.includes(key))) throw new DomainError("RETURN_SCHEMA_UNSUPPORTED_KEYWORD", `${field} contains an unsupported key`); }
function actor(kind: string): void { if (kind !== "AGENT" && kind !== "HUMAN") throw new DomainError("RETURN_ARTIFACT_ACTOR_INVALID", "return artifact operations require an AGENT or HUMAN actor"); }

function artifact(value: unknown, index: number): AuthorityArtifactReference {
  const row = object(value, `artifactReferences[${index}]`);
  keysOnly(row, ["kind", "sourceUrl", "sourceTitle", "officialReleaseIdentifier", "officialReleaseDate", "sha256"], `artifactReferences[${index}]`);
  const kind = text(row.kind, `artifactReferences[${index}].kind`);
  if (!["LAW", "RULES", "SCHEMA", "INSTRUCTION"].includes(kind)) throw new DomainError("INVALID_RETURN_SCHEMA_ARTIFACT", "artifact kind is unsupported");
  const sourceUrl = text(row.sourceUrl, `artifactReferences[${index}].sourceUrl`, 2048);
  if (!/^https:\/\//i.test(sourceUrl)) throw new DomainError("INVALID_RETURN_SCHEMA_ARTIFACT", "artifact sourceUrl must be HTTPS");
  return { kind: kind as AuthorityArtifactReference["kind"], sourceUrl, sourceTitle: text(row.sourceTitle, `artifactReferences[${index}].sourceTitle`, 512), officialReleaseIdentifier: text(row.officialReleaseIdentifier, `artifactReferences[${index}].officialReleaseIdentifier`), officialReleaseDate: text(row.officialReleaseDate, `artifactReferences[${index}].officialReleaseDate`, 64), sha256: sha(row.sha256, `artifactReferences[${index}].sha256`) };
}

const SCHEMA_KEYS = ["type", "properties", "required", "items", "enum", "pattern", "minLength", "maxLength", "minItems", "maxItems", "minimum", "maximum", "additionalProperties", "integerEncoding", "encoding"] as const;
function validateSchema(value: unknown, path = "", depth = 0, counter = { count: 0 }): Schema {
  if (depth > MAX_DEPTH) throw new DomainError("RETURN_SCHEMA_DEPTH_EXCEEDED", "validation schema depth exceeds the V1 bound", { path });
  counter.count += 1; if (counter.count > MAX_NODES) throw new DomainError("RETURN_SCHEMA_NODES_EXCEEDED", "validation schema node count exceeds the V1 bound");
  const row = object(value, path || "validationSchema"); keysOnly(row, SCHEMA_KEYS, path || "validationSchema");
  const type = row.type;
  if (!["object", "array", "string", "integer", "boolean", "null"].includes(String(type))) throw new DomainError("RETURN_SCHEMA_UNSUPPORTED_TYPE", `${path || "/"}.type is unsupported`);
  if (row.additionalProperties !== undefined && row.additionalProperties !== false) throw new DomainError("RETURN_SCHEMA_UNSUPPORTED_KEYWORD", "additionalProperties must be false");
  if (row.required !== undefined && (!Array.isArray(row.required) || row.required.some((key) => typeof key !== "string"))) throw new DomainError("RETURN_SCHEMA_INVALID_REQUIRED", `${path || "/"}.required must be string names`);
  if (row.enum !== undefined && (!Array.isArray(row.enum) || row.enum.length > 64)) throw new DomainError("RETURN_SCHEMA_INVALID_ENUM", `${path || "/"}.enum must be a bounded array`);
  for (const name of ["minLength", "maxLength", "minItems", "maxItems"] as const) if (row[name] !== undefined && (!Number.isSafeInteger(row[name]) || Number(row[name]) < 0 || Number(row[name]) > 100_000)) throw new DomainError("RETURN_SCHEMA_INVALID_BOUND", `${path || "/"}.${name} must be a safe nonnegative integer`);
  for (const name of ["minimum", "maximum"] as const) if (row[name] !== undefined && (typeof row[name] !== "string" || !/^-?(?:0|[1-9][0-9]*)$/.test(row[name]))) throw new DomainError("RETURN_SCHEMA_INVALID_BOUND", `${path || "/"}.${name} must be a decimal string`);
  if (row.pattern !== undefined && (typeof row.pattern !== "string" || row.pattern.length > 256)) throw new DomainError("RETURN_SCHEMA_INVALID_PATTERN", `${path || "/"}.pattern is invalid`);
  if (typeof row.pattern === "string") { try { new RegExp(row.pattern, "u"); } catch { throw new DomainError("RETURN_SCHEMA_INVALID_PATTERN", `${path || "/"}.pattern is invalid`); } }
  if (type === "object") {
    const properties = row.properties === undefined ? {} : object(row.properties, `${path || "/"}.properties`);
    for (const [key, child] of Object.entries(properties)) { if (key.length > 128 || key.includes("\0")) throw new DomainError("RETURN_SCHEMA_INVALID_PROPERTY", "schema property name is invalid"); validateSchema(child, `${path}/${key}`, depth + 1, counter); }
    if (Array.isArray(row.required) && new Set(row.required).size !== row.required.length) throw new DomainError("RETURN_SCHEMA_INVALID_REQUIRED", "required contains duplicate names");
    if (Array.isArray(row.required) && row.required.some((key) => !Object.prototype.hasOwnProperty.call(properties, key))) throw new DomainError("RETURN_SCHEMA_INVALID_REQUIRED", "required names must be declared properties");
  } else if (type === "array") {
    if (row.items === undefined) throw new DomainError("RETURN_SCHEMA_ITEMS_REQUIRED", `${path || "/"}.items is required for arrays`);
    validateSchema(row.items, `${path}/*`, depth + 1, counter);
  } else if (row.properties !== undefined || row.items !== undefined || row.required !== undefined || row.additionalProperties !== undefined) throw new DomainError("RETURN_SCHEMA_KEYWORD_TYPE_MISMATCH", `${path || "/"} uses object/array keywords for a scalar`);
  if (type !== "string" && (row.minLength !== undefined || row.maxLength !== undefined)) throw new DomainError("RETURN_SCHEMA_KEYWORD_TYPE_MISMATCH", `${path || "/"} uses string length bounds for a non-string`);
  if (type !== "array" && (row.minItems !== undefined || row.maxItems !== undefined)) throw new DomainError("RETURN_SCHEMA_KEYWORD_TYPE_MISMATCH", `${path || "/"} uses item bounds for a non-array`);
  if (type !== "integer" && (row.minimum !== undefined || row.maximum !== undefined)) throw new DomainError("RETURN_SCHEMA_KEYWORD_TYPE_MISMATCH", `${path || "/"} uses value bounds for a non-integer`);
  if (type === "integer") {
    const encoding = row.integerEncoding ?? row.encoding;
    if (encoding !== "DECIMAL_STRING" && encoding !== "SAFE_JSON_INTEGER") throw new DomainError("RETURN_SCHEMA_INTEGER_ENCODING_REQUIRED", `${path || "/"} must explicitly declare integerEncoding`);
  } else if (row.integerEncoding !== undefined || row.encoding !== undefined) throw new DomainError("RETURN_SCHEMA_INTEGER_ENCODING_INVALID", `${path || "/"} declares integer encoding for a non-integer`);
  return row;
}

function normalizePack(payload: ReturnSchemaPackRegisterPayload): { value: JsonObject; canonicalHash: string } {
  const references = Array.isArray(payload?.artifactReferences) ? payload.artifactReferences.map(artifact) : [];
  if (references.length !== 4 || new Set(references.map((item) => item.kind)).size !== 4) throw new DomainError("RETURN_SCHEMA_ARTIFACTS_REQUIRED", "exactly one LAW, RULES, SCHEMA, and INSTRUCTION reference is required");
  const schema = sharedValidateSchema(payload.validationSchema);
  const mapping = sharedValidateMapping(payload.mappingSpec);
  const value = { schemaVersion: 1, jurisdiction: "IN", authority: "INCOME_TAX", authorityPackId: text(payload.authorityPackId, "authorityPackId"), authorityPackHash: sha(payload.authorityPackHash, "authorityPackHash"), itrForm: text(payload.itrForm, "itrForm", 64), filingType: text(payload.filingType, "filingType", 64), financialYear: text(payload.financialYear, "financialYear", 32), assessmentYear: text(payload.assessmentYear, "assessmentYear", 32), artifactReferences: references, packVersion: text(payload.packVersion, "packVersion", 64), validationSchema: schema, mappingSpec: mapping, ...(payload.supersedesPackId ? { supersedesPackId: text(payload.supersedesPackId, "supersedesPackId") } : {}) };
  const canonicalHash = hash(value);
  if (payload.packId !== undefined) text(payload.packId, "packId");
  return { value, canonicalHash };
}

function validateMapping(value: unknown, path = "mappingSpec", depth = 0, counter = { count: 0 }): Mapping {
  if (depth > MAX_DEPTH) throw new DomainError("RETURN_MAPPING_DEPTH_EXCEEDED", "mapping depth exceeds the V1 bound");
  counter.count += 1; if (counter.count > MAX_NODES) throw new DomainError("RETURN_MAPPING_NODES_EXCEEDED", "mapping node count exceeds the V1 bound");
  const row = object(value, path); const kind = row.type ?? (row.pointer !== undefined ? "pointer" : row.value !== undefined ? "constant" : undefined);
  if (!["object", "array", "constant", "pointer"].includes(String(kind))) throw new DomainError("RETURN_MAPPING_OPERATOR_INVALID", `${path}.type is unsupported`);
  if (kind === "object") { keysOnly(row, ["type", "properties"], path); const properties = object(row.properties, `${path}.properties`); const names = Object.keys(properties); if (new Set(names).size !== names.length) throw new DomainError("RETURN_MAPPING_DUPLICATE_KEY", `${path}.properties contains duplicate keys`); for (const [key, child] of Object.entries(properties)) validateMapping(child, `${path}.properties.${key}`, depth + 1, counter); }
  else if (kind === "array") { keysOnly(row, ["type", "items"], path); if (!Array.isArray(row.items) || row.items.length === 0 || row.items.length > 256) throw new DomainError("RETURN_MAPPING_ARRAY_INVALID", `${path}.items must be a bounded non-empty array`); row.items.forEach((child, index) => validateMapping(child, `${path}.items[${index}]`, depth + 1, counter)); }
  else if (kind === "constant") { keysOnly(row, ["type", "value", "convert"], path); if (row.convert !== undefined && !["string", "integer", "boolean", "null"].includes(String(row.convert))) throw new DomainError("RETURN_MAPPING_CONVERSION_INVALID", `${path}.convert is unsupported`); }
  else { keysOnly(row, ["type", "pointer", "convert"], path); const pointer = text(row.pointer, `${path}.pointer`, 256); if (!/^\/(identity|taxCase|selectedForm|filingSnapshot|worksheet|eligibility|computation)(\/[^/]+)*$/.test(pointer)) throw new DomainError("RETURN_MAPPING_POINTER_INVALID", `pointer is not whitelisted: ${pointer}`); if (row.convert !== undefined && !["string", "integer", "boolean", "null"].includes(String(row.convert))) throw new DomainError("RETURN_MAPPING_CONVERSION_INVALID", `${path}.convert is unsupported`); }
  return { ...row, type: kind };
}

function pointerValue(root: JsonObject, pointer: string): unknown {
  const parts = pointer.slice(1).split("/").map((part) => part.replaceAll("~1", "/").replaceAll("~0", "~")); let value: unknown = root;
  for (const part of parts) { if (!value || typeof value !== "object" || !Object.prototype.hasOwnProperty.call(value, part)) throw new DomainError("RETURN_MAPPING_POINTER_MISSING", `bound pointer is unavailable: ${pointer}`); value = (value as JsonObject)[part]; }
  return value;
}
function convert(value: unknown, conversion: unknown, path: string): unknown {
  if (conversion === undefined) return value;
  if (conversion === "null") return null;
  if (conversion === "string") { if (typeof value === "string") return value; if (typeof value === "number" && Number.isSafeInteger(value)) return String(value); if (typeof value === "boolean") return value ? "true" : "false"; throw new DomainError("RETURN_MAPPING_CONVERSION_INVALID", `${path} cannot convert to string`); }
  if (conversion === "boolean") { if (typeof value === "boolean") return value; if (value === "true" || value === "false") return value === "true"; throw new DomainError("RETURN_MAPPING_CONVERSION_INVALID", `${path} cannot convert to boolean`); }
  if (conversion === "integer") { if (typeof value === "string" && /^-?(?:0|[1-9][0-9]*)$/.test(value)) return value; if (typeof value === "number" && Number.isSafeInteger(value)) return value; throw new DomainError("RETURN_MAPPING_UNSAFE_INTEGER", `${path} cannot convert to integer safely`); }
  throw new DomainError("RETURN_MAPPING_CONVERSION_INVALID", `${path} has unknown conversion`);
}
function evaluateMapping(node: Mapping, root: JsonObject, path = "mappingSpec"): unknown {
  if (node.type === "object") { const output: JsonObject = {}; for (const [key, child] of Object.entries(object(node.properties, `${path}.properties`))) { if (Object.prototype.hasOwnProperty.call(output, key)) throw new DomainError("RETURN_MAPPING_DUPLICATE_KEY", `${path} contains duplicate object key`); output[key] = evaluateMapping(child as Mapping, root, `${path}.${key}`); } return output; }
  if (node.type === "array") return (node.items as unknown[]).map((child, index) => evaluateMapping(child as Mapping, root, `${path}[${index}]`));
  if (node.type === "constant") return convert(node.value, node.convert, path);
  return convert(pointerValue(root, String(node.pointer)), node.convert, path);
}

type Diagnostic = { pointer: string; code: string; message: string };
function compareDecimalInteger(left: string, right: string): number {
  const normalize = (value: string) => { const negative = value.startsWith("-"); const digits = (negative ? value.slice(1) : value).replace(/^0+(?=\d)/, ""); return { negative: negative && digits !== "0", digits }; };
  const a = normalize(left); const b = normalize(right); if (a.negative !== b.negative) return a.negative ? -1 : 1; const sign = a.negative ? -1 : 1; if (a.digits.length !== b.digits.length) return (a.digits.length < b.digits.length ? -1 : 1) * sign; return (a.digits === b.digits ? 0 : a.digits < b.digits ? -1 : 1) * sign;
}
function validateValue(schema: Schema, value: unknown, pointer = "", diagnostics: Diagnostic[] = []): Diagnostic[] {
  if (diagnostics.length >= MAX_DIAGNOSTICS) return diagnostics;
  const fail = (code: string, message: string) => { if (diagnostics.length < MAX_DIAGNOSTICS) diagnostics.push({ pointer: pointer || "/", code, message }); };
  const type = String(schema.type);
  if (type === "null" && value !== null) { fail("TYPE", "expected null"); return diagnostics; }
  if (type === "boolean" && typeof value !== "boolean") { fail("TYPE", "expected boolean"); return diagnostics; }
  if (type === "string" && typeof value !== "string") { fail("TYPE", "expected string"); return diagnostics; }
  if (type === "integer") { const encoding = schema.integerEncoding ?? schema.encoding; const valid = encoding === "DECIMAL_STRING" ? typeof value === "string" && /^-?(?:0|[1-9][0-9]*)$/.test(value) : typeof value === "number" && Number.isSafeInteger(value); if (!valid) { fail("TYPE", `expected ${String(encoding)}`); return diagnostics; } const comparable = typeof value === "string" ? value : String(value); if (schema.minimum !== undefined && compareDecimalInteger(comparable, String(schema.minimum)) < 0) fail("MINIMUM", "integer is below minimum"); if (schema.maximum !== undefined && compareDecimalInteger(comparable, String(schema.maximum)) > 0) fail("MAXIMUM", "integer is above maximum"); }
  if (type === "string" && typeof value === "string") { if (schema.minLength !== undefined && value.length < Number(schema.minLength)) fail("MIN_LENGTH", "string is shorter than minLength"); if (schema.maxLength !== undefined && value.length > Number(schema.maxLength)) fail("MAX_LENGTH", "string is longer than maxLength"); if (schema.pattern !== undefined) { let regex: RegExp; try { regex = new RegExp(String(schema.pattern), "u"); } catch { fail("PATTERN_INVALID", "schema pattern is invalid"); regex = /$a/; } if (!regex.test(value)) fail("PATTERN", "string does not match pattern"); } }
  if (schema.enum !== undefined && !(schema.enum as unknown[]).some((candidate) => canonicalJson(candidate) === canonicalJson(value))) fail("ENUM", "value is not in enum");
  if (type === "object" && value && typeof value === "object" && !Array.isArray(value)) { const row = value as JsonObject; const properties = (schema.properties ?? {}) as JsonObject; for (const required of (schema.required as string[] | undefined) ?? []) if (!Object.prototype.hasOwnProperty.call(row, required)) fail("REQUIRED", `required property is missing: ${required}`); if (schema.additionalProperties === false) for (const key of Object.keys(row)) if (!Object.prototype.hasOwnProperty.call(properties, key)) { fail("ADDITIONAL_PROPERTY", `additional property is not allowed: ${key}`); } for (const [key, child] of Object.entries(properties)) if (Object.prototype.hasOwnProperty.call(row, key)) validateValue(child as Schema, row[key], `${pointer}/${key.replaceAll("~", "~0").replaceAll("/", "~1")}`, diagnostics); }
  if (type === "array" && Array.isArray(value)) { if (schema.minItems !== undefined && value.length < Number(schema.minItems)) fail("MIN_ITEMS", "array has fewer than minItems"); if (schema.maxItems !== undefined && value.length > Number(schema.maxItems)) fail("MAX_ITEMS", "array has more than maxItems"); for (const [index, item] of value.entries()) validateValue(schema.items as Schema, item, `${pointer}/${index}`, diagnostics); }
  return diagnostics;
}

async function replay(session: BusinessSession, tenantId: string, requestId: string, requestHash: string): Promise<CommandResult<Record<string, unknown>> | undefined> { const row = await session.querySingle("SELECT request_hash, result_json, result_hash FROM idempotency_records WHERE tenant_id = ? AND request_id = ?", [tenantId, requestId]); if (!row) return undefined; if (String(row.request_hash) !== requestHash) throw new IdempotencyConflictError("same request_id with different normalized request payload"); const resultJson = String(row.result_json); const resultHash = String(row.result_hash); if (computeResultHash(resultJson) !== resultHash) throw new IdempotencyCorruptError("stored result_json hash mismatch"); return { resultJson, resultHash, replayed: true }; }
async function finish(session: BusinessSession, command: string, envelope: CommandEnvelope<unknown>, requestHash: string, result: Record<string, unknown>, entityId: string, entityType: string): Promise<CommandResult<Record<string, unknown>>> { const resultJson = canonicalJson(result); const resultHash = computeResultHash(resultJson); const now = new Date().toISOString(); await session.execute("INSERT INTO audit_records (id, tenant_id, command, action, actor_type, actor_id, source, reason, request_id, entity_type, entity_id, canonical_after_hash, change_summary, committed_at, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", [randomUUID(), envelope.tenantId, command, command, envelope.actor.kind, envelope.actor.id, envelope.source, envelope.reason, envelope.requestId, entityType, entityId, resultHash, JSON.stringify(result), now, now]); await session.execute("INSERT INTO idempotency_records (id, tenant_id, request_id, request_hash, result_json, result_hash, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)", [randomUUID(), envelope.tenantId, envelope.requestId, requestHash, resultJson, resultHash, now]); return { resultJson, resultHash }; }
async function packRow(session: BusinessSession, id: string): Promise<JsonObject> { const row = await session.querySingle("SELECT * FROM personal_tax_return_schema_packs WHERE id = ?", [id]); if (!row) throw new DomainError("RETURN_SCHEMA_PACK_NOT_FOUND", "return schema pack was not found"); return row; }
async function packLifecycle(session: BusinessSession, id: string): Promise<string> { const row = await session.querySingle("SELECT event_type FROM personal_tax_return_schema_pack_events WHERE pack_id = ? ORDER BY created_at DESC, id DESC LIMIT 1", [id]); return String(row?.event_type ?? "PROPOSED"); }
function packView(row: JsonObject, lifecycle: string): JsonObject { return { packId: String(row.id), authorityPackId: String(row.authority_pack_id), authorityPackHash: String(row.authority_pack_hash), itrForm: String(row.itr_form), filingType: String(row.filing_type), financialYear: String(row.financial_year), assessmentYear: String(row.assessment_year), packVersion: String(row.pack_version), canonicalHash: String(row.canonical_hash), lifecycle, supersedesPackId: row.supersedes_pack_id == null ? undefined : String(row.supersedes_pack_id), artifactReferences: JSON.parse(String(row.artifact_references_json)), validationSchema: JSON.parse(String(row.validation_schema_json)), mappingSpec: JSON.parse(String(row.mapping_spec_json)) }; }

export async function registerReturnSchemaPack(runner: BusinessSessionRunner, envelope: CommandEnvelope<ReturnSchemaPackRegisterPayload>): Promise<CommandResult<Record<string, unknown>>> {
  validateCommandEnvelope(envelope); actor(envelope.actor.kind); const normalized = normalizePack(envelope.payload); const requestHash = computeCommandHash(REGISTER, envelope, normalized.value);
  return runner.withBusinessSession("write", async (session) => { const prior = await replay(session, envelope.tenantId, envelope.requestId, requestHash); if (prior) return prior; const authority = await session.querySingle("SELECT canonical_hash FROM personal_tax_authority_packs WHERE id = ?", [normalized.value.authorityPackId]); if (!authority || String(authority.canonical_hash) !== normalized.value.authorityPackHash) throw new DomainError("RETURN_SCHEMA_AUTHORITY_BINDING_MISMATCH", "schema pack must bind the exact AuthorityPack hash"); const existing = await session.querySingle("SELECT * FROM personal_tax_return_schema_packs WHERE canonical_hash = ?", [normalized.canonicalHash]); if (existing) return finish(session, REGISTER, envelope, requestHash, { ...packView(existing, await packLifecycle(session, String(existing.id))), duplicate: true }, String(existing.id), "PersonalTaxReturnSchemaPack"); if (normalized.value.supersedesPackId) { const previous = await session.querySingle("SELECT id, canonical_hash FROM personal_tax_return_schema_packs WHERE id = ?", [normalized.value.supersedesPackId]); if (!previous) throw new DomainError("RETURN_SCHEMA_SUPERSESSION_NOT_FOUND", "superseded schema pack was not found"); }
    const id = normalized.value.packId ? text(normalized.value.packId, "packId") : randomUUID(); const now = new Date().toISOString(); await session.execute("INSERT INTO personal_tax_return_schema_packs (id, authority_pack_id, authority_pack_hash, itr_form, filing_type, financial_year, assessment_year, artifact_references_json, pack_version, validation_schema_json, mapping_spec_json, canonical_hash, supersedes_pack_id, created_at, created_by_actor_kind, created_by_actor_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", [id, normalized.value.authorityPackId, normalized.value.authorityPackHash, normalized.value.itrForm, normalized.value.filingType, normalized.value.financialYear, normalized.value.assessmentYear, canonicalJson(normalized.value.artifactReferences), normalized.value.packVersion, canonicalJson(normalized.value.validationSchema), canonicalJson(normalized.value.mappingSpec), normalized.canonicalHash, normalized.value.supersedesPackId ?? null, now, envelope.actor.kind, envelope.actor.id]); await session.execute("INSERT INTO personal_tax_return_schema_pack_events (id, pack_id, event_type, actor_kind, actor_id, reason, expected_pack_hash, request_id, request_hash, created_at) VALUES (?, ?, 'REGISTERED', ?, ?, ?, ?, ?, ?, ?)", [randomUUID(), id, envelope.actor.kind, envelope.actor.id, envelope.reason, normalized.canonicalHash, envelope.requestId, requestHash, now]); if (normalized.value.supersedesPackId) { const previous = await session.querySingle("SELECT canonical_hash FROM personal_tax_return_schema_packs WHERE id = ?", [normalized.value.supersedesPackId]); await session.execute("INSERT INTO personal_tax_return_schema_pack_events (id, pack_id, event_type, actor_kind, actor_id, reason, expected_pack_hash, request_id, request_hash, created_at) VALUES (?, ?, 'SUPERSEDED', ?, ?, ?, ?, ?, ?, ?)", [randomUUID(), normalized.value.supersedesPackId, envelope.actor.kind, envelope.actor.id, envelope.reason, String(previous?.canonical_hash), `${envelope.requestId}:supersede`, requestHash, now]); } return finish(session, REGISTER, envelope, requestHash, { ...packView(await packRow(session, id), "REGISTERED"), duplicate: false }, id, "PersonalTaxReturnSchemaPack"); });
}
async function decidePack(runner: BusinessSessionRunner, envelope: CommandEnvelope<ReturnSchemaPackDecisionPayload>, eventType: "HUMAN_VERIFIED" | "REJECTED"): Promise<CommandResult<Record<string, unknown>>> { validateCommandEnvelope(envelope); if (envelope.actor.kind !== "HUMAN") throw new DomainError("RETURN_SCHEMA_HUMAN_REQUIRED", "schema pack verification/rejection requires a HUMAN actor"); const payload = { packId: text(envelope.payload?.packId, "packId"), expectedPackHash: sha(envelope.payload?.expectedPackHash, "expectedPackHash"), reason: text(envelope.payload?.reason, "reason") }; const requestHash = computeCommandHash(eventType === "HUMAN_VERIFIED" ? VERIFY : REJECT, envelope, payload); return runner.withBusinessSession("write", async (session) => { const prior = await replay(session, envelope.tenantId, envelope.requestId, requestHash); if (prior) return prior; const row = await packRow(session, payload.packId); if (String(row.canonical_hash) !== payload.expectedPackHash) throw new DomainError("RETURN_SCHEMA_PACK_CAS_MISMATCH", "expected schema pack hash does not match"); if (await packLifecycle(session, payload.packId) !== "REGISTERED") throw new DomainError("RETURN_SCHEMA_PACK_LIFECYCLE_CONFLICT", "only a registered schema pack can be verified or rejected"); if (eventType === "HUMAN_VERIFIED") { const authorityEvent = await session.querySingle("SELECT event_type FROM personal_tax_authority_pack_events WHERE pack_id = ? ORDER BY created_at DESC, id DESC LIMIT 1", [row.authority_pack_id]); if (String(authorityEvent?.event_type) !== "HUMAN_VERIFIED") throw new DomainError("RETURN_SCHEMA_AUTHORITY_NOT_VERIFIED", "linked AuthorityPack must be HUMAN_VERIFIED"); } const now = new Date().toISOString(); await session.execute("INSERT INTO personal_tax_return_schema_pack_events (id, pack_id, event_type, actor_kind, actor_id, reason, expected_pack_hash, request_id, request_hash, created_at) VALUES (?, ?, ?, 'HUMAN', ?, ?, ?, ?, ?, ?)", [randomUUID(), payload.packId, eventType, envelope.actor.id, payload.reason, payload.expectedPackHash, envelope.requestId, requestHash, now]); return finish(session, eventType === "HUMAN_VERIFIED" ? VERIFY : REJECT, envelope, requestHash, { ...packView(row, eventType), eventType }, payload.packId, "PersonalTaxReturnSchemaPackEvent"); }); }
export function verifyReturnSchemaPack(runner: BusinessSessionRunner, envelope: CommandEnvelope<ReturnSchemaPackDecisionPayload>) { return decidePack(runner, envelope, "HUMAN_VERIFIED"); }
export function rejectReturnSchemaPack(runner: BusinessSessionRunner, envelope: CommandEnvelope<ReturnSchemaPackDecisionPayload>) { return decidePack(runner, envelope, "REJECTED"); }
export async function showReturnSchemaPack(runner: BusinessSessionRunner, packId: string): Promise<JsonObject> { return runner.withBusinessSession("read", async (session) => { const row = await packRow(session, text(packId, "packId")); return packView(row, await packLifecycle(session, packId)); }); }

async function boundInputs(session: BusinessSession, tenantId: string, payload: ReturnArtifactBindingPayload): Promise<{ root: JsonObject; bindings: JsonObject; pack: JsonObject; schemaHash: string }> {
  const taxCase = await session.querySingle("SELECT * FROM tax_cases WHERE id = ? AND tenant_id = ?", [payload.taxCaseId, tenantId]); if (!taxCase) throw new DomainError("TAX_CASE_NOT_FOUND", "TaxCase does not belong to tenant");
  const snapshot = await filingSnapshotStateInSession(session, tenantId, payload.taxCaseId, payload.filingSnapshotId); if (snapshot.status !== "CURRENT") throw new DomainError("RETURN_ARTIFACT_SNAPSHOT_NOT_CURRENT", "return artifact requires a CURRENT FilingSnapshot", { status: snapshot.status, reasons: snapshot.currentBlockers });
  const worksheet = await session.querySingle("SELECT * FROM personal_tax_position_worksheets WHERE id = ? AND tenant_id = ? AND tax_case_id = ?", [payload.worksheetId, tenantId, payload.taxCaseId]); if (!worksheet || String(worksheet.filing_snapshot_id) !== payload.filingSnapshotId || String(worksheet.snapshot_candidate_hash) !== snapshot.candidateHash) throw new DomainError("RETURN_ARTIFACT_WORKSHEET_BINDING_MISMATCH", "worksheet is not bound to the exact current snapshot");
  const evaluation = await session.querySingle("SELECT * FROM tax_case_itr_eligibility_evaluations WHERE id = ? AND tenant_id = ? AND tax_case_id = ?", [payload.evaluationId, tenantId, payload.taxCaseId]); if (!evaluation || String(evaluation.filing_snapshot_id) !== payload.filingSnapshotId || String(evaluation.worksheet_id) !== payload.worksheetId) throw new DomainError("RETURN_ARTIFACT_ELIGIBILITY_BINDING_MISMATCH", "eligibility evaluation is not bound to the exact current inputs");
  const selection = await session.querySingle("SELECT * FROM tax_case_itr_form_selections WHERE id = ? AND tenant_id = ? AND tax_case_id = ?", [payload.selectionId, tenantId, payload.taxCaseId]); if (!selection || String(selection.evaluation_id) !== payload.evaluationId || String(selection.expected_evaluation_hash) !== String(evaluation.evaluation_hash)) throw new DomainError("RETURN_ARTIFACT_SELECTION_BINDING_MISMATCH", "selected form is not bound to the exact evaluation");
  const computation = await session.querySingle("SELECT * FROM personal_tax_computations WHERE id = ? AND tenant_id = ? AND tax_case_id = ?", [payload.computationId, tenantId, payload.taxCaseId]); if (!computation || String(computation.filing_snapshot_id) !== payload.filingSnapshotId || String(computation.worksheet_id) !== payload.worksheetId || String(computation.evaluation_id) !== payload.evaluationId || String(computation.selection_id) !== payload.selectionId) throw new DomainError("RETURN_ARTIFACT_COMPUTATION_BINDING_MISMATCH", "computation is not bound to the exact current inputs"); if (String(computation.snapshot_candidate_hash) !== snapshot.candidateHash || String(computation.worksheet_output_hash) !== String(worksheet.output_hash) || String(computation.evaluation_hash) !== String(evaluation.evaluation_hash)) throw new DomainError("RETURN_ARTIFACT_COMPUTATION_BINDING_MISMATCH", "computation input hashes do not match current inputs");
  const approved = await session.querySingle("SELECT id FROM personal_tax_computation_events WHERE computation_id = ? AND tenant_id = ? AND tax_case_id = ? AND event_type = 'APPROVED' AND expected_computation_hash = ?", [payload.computationId, tenantId, payload.taxCaseId, computation.computation_hash]); if (!approved) throw new DomainError("RETURN_ARTIFACT_COMPUTATION_NOT_APPROVED", "return preparation requires an exact HUMAN_APPROVED computation");
  const pack = await packRow(session, payload.schemaPackId); if (await packLifecycle(session, payload.schemaPackId) !== "HUMAN_VERIFIED") throw new DomainError("RETURN_ARTIFACT_SCHEMA_NOT_VERIFIED", "return preparation requires a HUMAN_VERIFIED schema pack"); if (String(pack.itr_form) !== String(selection.selected_form) || String(pack.filing_type) !== String(taxCase.filing_trigger) || String(pack.financial_year) !== String(taxCase.financial_year)) throw new DomainError("RETURN_ARTIFACT_SCHEMA_NOT_APPLICABLE", "schema pack does not match selected form, filing type, or financial year"); const authority = await session.querySingle("SELECT event_type FROM personal_tax_authority_pack_events WHERE pack_id = ? ORDER BY created_at DESC, id DESC LIMIT 1", [pack.authority_pack_id]); if (String(authority?.event_type) !== "HUMAN_VERIFIED") throw new DomainError("RETURN_ARTIFACT_AUTHORITY_NOT_VERIFIED", "linked AuthorityPack is no longer HUMAN_VERIFIED");
  const pan = await session.querySingle("SELECT pan, masked_display FROM tenant_pan_profiles WHERE tenant_id = ?", [tenantId]); if (!pan) throw new DomainError("RETURN_ARTIFACT_PAN_REQUIRED", "a PAN identity is required");
  const safeJsonParse = (value: unknown, field: string): unknown => { try { return JSON.parse(String(value)); } catch { throw new DomainError("RETURN_ARTIFACT_UPSTREAM_INTEGRITY", `${field} is malformed JSON`); } };
  const root: JsonObject = { identity: { pan: String(pan.pan), maskedPan: String(pan.masked_display) }, taxCase: { id: String(taxCase.id), financialYear: String(taxCase.financial_year), assessmentYear: String(pack.assessment_year), filingType: String(taxCase.filing_trigger), taxPeriod: String(taxCase.tax_period) }, selectedForm: String(selection.selected_form), filingSnapshot: { id: String(payload.filingSnapshotId), candidateHash: snapshot.candidateHash, candidate: safeJsonParse((await session.querySingle("SELECT candidate_json FROM filing_snapshots WHERE id = ? AND tenant_id = ? AND tax_case_id = ?", [payload.filingSnapshotId, tenantId, payload.taxCaseId]))?.candidate_json, "FilingSnapshot") }, worksheet: { id: String(worksheet.id), outputHash: String(worksheet.output_hash), output: safeJsonParse(worksheet.output_json, "Position Worksheet") }, eligibility: { id: String(evaluation.id), evaluationHash: String(evaluation.evaluation_hash), results: safeJsonParse(evaluation.results_json, "eligibility evaluation"), selectedForm: String(selection.selected_form) }, computation: { id: String(computation.id), computationHash: String(computation.computation_hash), grossTaxMinor: String(computation.gross_tax_minor), creditsMinor: String(computation.credits_minor), netPayableMinor: computation.net_payable_minor == null ? null : String(computation.net_payable_minor), refundMinor: computation.refund_minor == null ? null : String(computation.refund_minor), trace: safeJsonParse(computation.step_trace_json, "computation trace"), schedules: safeJsonParse(computation.named_schedules_json, "computation schedules") } };
  const bindings = { tenantId, taxCaseId: payload.taxCaseId, filingSnapshotId: payload.filingSnapshotId, snapshotCandidateHash: snapshot.candidateHash, worksheetId: payload.worksheetId, worksheetOutputHash: String(worksheet.output_hash), evaluationId: payload.evaluationId, evaluationHash: String(evaluation.evaluation_hash), selectionId: payload.selectionId, selectedForm: String(selection.selected_form), computationId: payload.computationId, computationHash: String(computation.computation_hash), schemaPackId: payload.schemaPackId, schemaPackHash: String(pack.canonical_hash) };
  return { root, bindings, pack, schemaHash: String(pack.canonical_hash) };
}

function bindingPayload(value: unknown): ReturnArtifactBindingPayload { const row = object(value, "payload"); return { taxCaseId: text(row.taxCaseId, "taxCaseId"), filingSnapshotId: text(row.filingSnapshotId, "filingSnapshotId"), worksheetId: text(row.worksheetId, "worksheetId"), evaluationId: text(row.evaluationId, "evaluationId"), selectionId: text(row.selectionId, "selectionId"), computationId: text(row.computationId, "computationId"), schemaPackId: text(row.schemaPackId, "schemaPackId") }; }
function artifactView(row: JsonObject, status: string, reasons: string[] = []): JsonObject { return { artifactId: String(row.id), tenantId: String(row.tenant_id), taxCaseId: String(row.tax_case_id), status, statusReasons: reasons, schemaPackId: String(row.schema_pack_id), schemaPackHash: String(row.schema_pack_hash), contentByteLength: Number(row.content_byte_length), contentHash: String(row.content_hash), bindings: JSON.parse(String(row.bindings_json)), createdAt: String(row.created_at) }; }
async function artifactRow(session: BusinessSession, tenantId: string, taxCaseId: string, artifactId: string): Promise<JsonObject> { const row = await session.querySingle("SELECT * FROM personal_tax_return_artifacts WHERE id = ? AND tenant_id = ? AND tax_case_id = ?", [artifactId, tenantId, taxCaseId]); if (!row) throw new DomainError("RETURN_ARTIFACT_NOT_FOUND", "return artifact does not belong to TaxCase and tenant"); return row; }
async function artifactStatus(session: BusinessSession, row: JsonObject): Promise<{ status: string; reasons: string[] }> { const binding = JSON.parse(String(row.bindings_json)) as JsonObject; try { const inputs = await boundInputs(session, String(row.tenant_id), binding as unknown as ReturnArtifactBindingPayload); if (String(inputs.schemaHash) !== String(row.schema_pack_hash)) return { status: "STALE", reasons: ["SCHEMA_PACK_CHANGED"] }; const content = Buffer.from(String(row.content_json), "utf8"); if (createHash("sha256").update(content).digest("hex") !== String(row.content_hash)) return { status: "BLOCKED", reasons: ["CONTENT_HASH_MISMATCH"] }; const latest = await session.querySingle("SELECT status FROM personal_tax_return_validation_runs WHERE artifact_id = ? ORDER BY created_at DESC, id DESC LIMIT 1", [row.id]); if (latest?.status === "LOCAL_INVALID") return { status: "LOCAL_INVALID", reasons: ["LATEST_LOCAL_VALIDATION_FAILED"] }; const exported = await session.querySingle("SELECT id FROM personal_tax_return_export_activities WHERE artifact_id = ? LIMIT 1", [row.id]); return exported ? { status: "EXPORTED", reasons: [] } : latest?.status === "LOCAL_VALID" ? { status: "LOCAL_VALID", reasons: [] } : { status: "PREPARED", reasons: [] }; } catch (error) { if (error instanceof DomainError && error.code === "RETURN_ARTIFACT_COMPUTATION_NOT_APPROVED") return { status: "STALE", reasons: [error.code] }; return { status: "STALE", reasons: [error instanceof DomainError ? error.code : "UPSTREAM_CHANGED"] }; } }

export async function previewReturnArtifact(runner: BusinessSessionRunner, tenantId: string, payload: ReturnArtifactBindingPayload): Promise<JsonObject> { return runner.withBusinessSession("read", async (session) => { const binding = await boundInputs(session, tenantId, payload); const mapped = sharedEvaluateMapping(JSON.parse(String(binding.pack.mapping_spec_json)) as Mapping, binding.root); return { schemaVersion: 1, status: "PREVIEW", content: mapped, contentByteLength: Buffer.byteLength(`${canonicalJson(mapped)}\n`, "utf8"), contentHash: createHash("sha256").update(Buffer.from(`${canonicalJson(mapped)}\n`, "utf8")).digest("hex"), bindings: binding.bindings, schemaPackHash: binding.schemaHash }; }); }
export async function prepareReturnArtifact(runner: BusinessSessionRunner, envelope: CommandEnvelope<ReturnArtifactBindingPayload>): Promise<CommandResult<Record<string, unknown>>> { validateCommandEnvelope(envelope); actor(envelope.actor.kind); const payload = bindingPayload(envelope.payload); const requestHash = computeCommandHash(PREPARE, envelope, payload); return runner.withBusinessSession("write", async (session) => { const prior = await replay(session, envelope.tenantId, envelope.requestId, requestHash); if (prior) return prior; const binding = await boundInputs(session, envelope.tenantId, payload); const mapped = sharedEvaluateMapping(JSON.parse(String(binding.pack.mapping_spec_json)) as Mapping, binding.root); const contentJson = `${canonicalJson(mapped)}\n`; const content = Buffer.from(contentJson, "utf8"); if (content.length > MAX_JSON) throw new DomainError("RETURN_ARTIFACT_PAYLOAD_TOO_LARGE", "mapped return content exceeds the V1 size limit"); const contentHash = createHash("sha256").update(content).digest("hex"); const existing = await session.querySingle("SELECT * FROM personal_tax_return_artifacts WHERE tenant_id = ? AND tax_case_id = ? AND content_hash = ?", [envelope.tenantId, payload.taxCaseId, contentHash]); if (existing) return finish(session, PREPARE, envelope, requestHash, { ...artifactView(existing, "PREPARED"), duplicate: true }, String(existing.id), "PersonalTaxReturnArtifact"); const id = randomUUID(); const now = new Date().toISOString(); await session.execute("INSERT INTO personal_tax_return_artifacts (id, tenant_id, tax_case_id, filing_snapshot_id, worksheet_id, evaluation_id, selection_id, computation_id, schema_pack_id, schema_pack_hash, content_json, content_byte_length, content_hash, bindings_json, created_at, created_by_actor_kind, created_by_actor_id, request_id, request_hash) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", [id, envelope.tenantId, payload.taxCaseId, payload.filingSnapshotId, payload.worksheetId, payload.evaluationId, payload.selectionId, payload.computationId, payload.schemaPackId, binding.schemaHash, contentJson, content.length, contentHash, canonicalJson(binding.bindings), now, envelope.actor.kind, envelope.actor.id, envelope.requestId, requestHash]); return finish(session, PREPARE, envelope, requestHash, { ...artifactView(await artifactRow(session, envelope.tenantId, payload.taxCaseId, id), "PREPARED"), duplicate: false }, id, "PersonalTaxReturnArtifact"); }); }
export async function validateReturnArtifact(runner: BusinessSessionRunner, envelope: CommandEnvelope<ReturnArtifactValidatePayload>): Promise<CommandResult<Record<string, unknown>>> { validateCommandEnvelope(envelope); actor(envelope.actor.kind); const payload = { taxCaseId: text(envelope.payload?.taxCaseId, "taxCaseId"), artifactId: text(envelope.payload?.artifactId, "artifactId"), expectedArtifactHash: sha(envelope.payload?.expectedArtifactHash, "expectedArtifactHash") }; const requestHash = computeCommandHash(VALIDATE, envelope, payload); return runner.withBusinessSession("write", async (session) => { const prior = await replay(session, envelope.tenantId, envelope.requestId, requestHash); if (prior) return prior; const row = await artifactRow(session, envelope.tenantId, payload.taxCaseId, payload.artifactId); if (String(row.content_hash) !== payload.expectedArtifactHash) throw new DomainError("RETURN_ARTIFACT_CAS_MISMATCH", "expected artifact hash does not match"); const status = await artifactStatus(session, row); if (["STALE", "BLOCKED"].includes(status.status)) throw new DomainError("RETURN_ARTIFACT_NOT_VALIDATABLE", "artifact is not bound to current upstream inputs", status); const pack = await packRow(session, String(row.schema_pack_id)); const diagnostics = sharedValidateValue(JSON.parse(String(pack.validation_schema_json)) as Schema, JSON.parse(String(row.content_json))); const validationStatus = diagnostics.length === 0 ? "LOCAL_VALID" : "LOCAL_INVALID"; const validationBody = { schemaVersion: 1, artifactId: payload.artifactId, artifactHash: payload.expectedArtifactHash, schemaPackId: String(pack.id), schemaPackHash: String(pack.canonical_hash), status: validationStatus, diagnostics }; const validationHash = hash(validationBody); const id = randomUUID(); const now = new Date().toISOString(); await session.execute("INSERT INTO personal_tax_return_validation_runs (id, tenant_id, tax_case_id, artifact_id, artifact_hash, schema_pack_hash, validation_hash, status, diagnostics_json, created_at, created_by_actor_kind, created_by_actor_id, request_id, request_hash) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", [id, envelope.tenantId, payload.taxCaseId, payload.artifactId, payload.expectedArtifactHash, String(pack.canonical_hash), validationHash, validationStatus, canonicalJson(diagnostics), now, envelope.actor.kind, envelope.actor.id, envelope.requestId, requestHash]); return finish(session, VALIDATE, envelope, requestHash, { validationId: id, validationHash, ...validationBody }, id, "PersonalTaxReturnValidationRun"); }); }
export async function exportReturnArtifact(runner: BusinessSessionRunner, envelope: CommandEnvelope<ReturnArtifactExportPayload>): Promise<CommandResult<Record<string, unknown>>> { validateCommandEnvelope(envelope); if (envelope.actor.kind !== "HUMAN") throw new DomainError("RETURN_ARTIFACT_EXPORT_HUMAN_REQUIRED", "export is an explicit HUMAN action"); const payload = { taxCaseId: text(envelope.payload?.taxCaseId, "taxCaseId"), artifactId: text(envelope.payload?.artifactId, "artifactId"), expectedArtifactHash: sha(envelope.payload?.expectedArtifactHash, "expectedArtifactHash"), expectedValidationHash: sha(envelope.payload?.expectedValidationHash, "expectedValidationHash") }; const requestHash = computeCommandHash(EXPORT, envelope, payload); return runner.withBusinessSession("write", async (session) => { const prior = await replay(session, envelope.tenantId, envelope.requestId, requestHash); if (prior) return prior; const row = await artifactRow(session, envelope.tenantId, payload.taxCaseId, payload.artifactId); if (String(row.content_hash) !== payload.expectedArtifactHash) throw new DomainError("RETURN_ARTIFACT_CAS_MISMATCH", "expected artifact hash does not match"); const actual = await session.querySingle("SELECT * FROM personal_tax_return_validation_runs WHERE artifact_id = ? AND tenant_id = ? AND tax_case_id = ? ORDER BY created_at DESC, id DESC LIMIT 1", [payload.artifactId, envelope.tenantId, payload.taxCaseId]); if (!actual || String(actual.status) !== "LOCAL_VALID" || String(actual.validation_hash) !== payload.expectedValidationHash) throw new DomainError("RETURN_ARTIFACT_VALIDATION_CAS_MISMATCH", "latest validation is not the exact LOCAL_VALID validation requested"); const now = new Date().toISOString(); const exportId = randomUUID(); await session.execute("INSERT INTO personal_tax_return_export_activities (id, tenant_id, tax_case_id, artifact_id, artifact_hash, validation_hash, actor_kind, actor_id, request_id, request_hash, created_at) VALUES (?, ?, ?, ?, ?, ?, 'HUMAN', ?, ?, ?, ?)", [exportId, envelope.tenantId, payload.taxCaseId, payload.artifactId, payload.expectedArtifactHash, payload.expectedValidationHash, envelope.actor.id, envelope.requestId, requestHash, now]); return finish(session, EXPORT, envelope, requestHash, { exportActivityId: exportId, artifactId: payload.artifactId, artifactHash: payload.expectedArtifactHash, validationHash: payload.expectedValidationHash, status: "EXPORTED", submitted: false, accepted: false }, exportId, "PersonalTaxReturnExportActivity"); }); }
export async function showReturnArtifact(runner: BusinessSessionRunner, tenantId: string, taxCaseId: string, artifactId: string): Promise<JsonObject> { return runner.withBusinessSession("read", async (session) => { const row = await artifactRow(session, tenantId, taxCaseId, artifactId); const state = await artifactStatus(session, row); return artifactView(row, state.status, state.reasons); }); }
export async function statusReturnArtifact(runner: BusinessSessionRunner, tenantId: string, taxCaseId: string, artifactId: string): Promise<JsonObject> { const view = await showReturnArtifact(runner, tenantId, taxCaseId, artifactId); return { artifactId: view.artifactId, tenantId, taxCaseId, status: view.status, statusReasons: view.statusReasons }; }
export async function contentReturnArtifact(runner: BusinessSessionRunner, tenantId: string, taxCaseId: string, artifactId: string, revealSensitive = false, actorKind?: string): Promise<JsonObject> { return runner.withBusinessSession("read", async (session) => { const row = await artifactRow(session, tenantId, taxCaseId, artifactId); const metadata = artifactView(row, (await artifactStatus(session, row)).status); if (!revealSensitive) return { ...metadata, revealed: false }; if (actorKind !== "HUMAN") throw new DomainError("RETURN_ARTIFACT_SENSITIVE_HUMAN_REQUIRED", "raw return JSON requires an explicit HUMAN actor"); return { ...metadata, revealed: true, content: JSON.parse(String(row.content_json)) }; }); }
