import type { JsonSchema } from "./types.ts";

export type OperationSideEffect = "read" | "write";
export type RequiredScope = "none" | "tenant" | "bookSet";

export interface OperationCatalogEntry {
  readonly id: string;
  readonly description: string;
  readonly sideEffect: OperationSideEffect;
  readonly requiredScope: RequiredScope;
  readonly inputSchema: JsonSchema;
  readonly outputDescription: string;
  readonly examples: readonly string[];
  readonly remediation: string;
  readonly operatorOnly?: boolean;
}

const objectSchema = (required: readonly string[] = [], properties: Record<string, unknown> = {}): JsonSchema => ({
  type: "object",
  properties,
  required: [...required],
  additionalProperties: true,
});

const id = { type: "string", minLength: 1 };
const date = { type: "string", pattern: "^\\d{4}-\\d{2}-\\d{2}$" };
const envelopeProperties = {
  schemaVersion: { type: "number", const: 1 }, tenantId: id, requestId: id,
  actor: { type: "object", required: ["kind", "id"] }, source: { type: "string" },
  reason: { type: "string", minLength: 1 }, requestedAt: { type: "string" }, payload: { type: "object" },
};
const scopedEnvelopeProperties = { ...envelopeProperties, bookSetId: id };
const readScopeProperties = { tenantId: id, bookSetId: id };
const companyStatusProperties = { tenantId: id, bookSetId: id, asOfDate: date };
const commandSchema = (bookSet: boolean, payloadRequired = true) => objectSchema(
  bookSet ? ["schemaVersion", "tenantId", "bookSetId", "requestId", "actor", "source", "reason", ...(payloadRequired ? ["payload"] : [])] : ["schemaVersion", "tenantId", "requestId", "actor", "source", "reason", ...(payloadRequired ? ["payload"] : [])],
  bookSet ? scopedEnvelopeProperties : envelopeProperties,
);

const entries: OperationCatalogEntry[] = [
  { id: "tenant.get", description: "Read one tenant by its explicit ID.", sideEffect: "read", requiredScope: "tenant", inputSchema: objectSchema(["tenantId"], { tenantId: id }), outputDescription: "Tenant record.", examples: ['{"tenantId":"tenant-1"}'], remediation: "Provide the exact tenantId; the transport never infers a tenant." },
  { id: "tenant.list-active", description: "List active tenants.", sideEffect: "read", requiredScope: "none", inputSchema: objectSchema(), outputDescription: "Active tenant records.", examples: ["{}"], remediation: "No database mutation is performed." },
  { id: "tenant.create", description: "Create a tenant and its audited default BookSet.", sideEffect: "write", requiredScope: "none", inputSchema: commandSchema(false), outputDescription: "Versioned command result with tenant and default BookSet IDs.", examples: ['{"schemaVersion":1,"tenantId":"tenant-new","requestId":"req-1","actor":{"kind":"HUMAN","id":"user-1"},"source":"CLI","reason":"setup","payload":{"kind":"COMPANY","name":"Acme"}}'], remediation: "Use a new requestId for new content; replaying the same requestId is idempotent." },
  { id: "tenant.activate", description: "Activate a tenant through its audited command boundary.", sideEffect: "write", requiredScope: "tenant", inputSchema: commandSchema(false), outputDescription: "Versioned activation command result.", examples: ["{\"schemaVersion\":1,\"tenantId\":\"tenant-1\",\"requestId\":\"req-2\",\"actor\":{\"kind\":\"HUMAN\",\"id\":\"user-1\"},\"source\":\"CLI\",\"reason\":\"activate\",\"payload\":{\"defaultBookSetId\":\"bookset-1\"}}"], remediation: "The defaultBookSetId must belong to the tenant." },
  { id: "book-set.get-default", description: "Read a tenant's default BookSet.", sideEffect: "read", requiredScope: "tenant", inputSchema: objectSchema(["tenantId"], { tenantId: id }), outputDescription: "Default BookSet record.", examples: ['{"tenantId":"tenant-1"}'], remediation: "Provide an explicit tenantId." },
  { id: "book-set.get", description: "Read a BookSet under an explicit tenant scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], readScopeProperties), outputDescription: "BookSet record.", examples: ['{"tenantId":"tenant-1","bookSetId":"bookset-1"}'], remediation: "Cross-tenant BookSet access is rejected." },
  { id: "book-set.list", description: "List BookSets owned by an explicit tenant.", sideEffect: "read", requiredScope: "tenant", inputSchema: objectSchema(["tenantId"], { tenantId: id }), outputDescription: "BookSet records.", examples: ['{"tenantId":"tenant-1"}'], remediation: "Provide an explicit tenantId." },
  { id: "book-set.create", description: "Create an audited BookSet.", sideEffect: "write", requiredScope: "tenant", inputSchema: commandSchema(false), outputDescription: "Versioned BookSet command result.", examples: ['{"schemaVersion":1,"tenantId":"tenant-1","requestId":"req-3","actor":{"kind":"HUMAN","id":"user-1"},"source":"CLI","reason":"setup","payload":{"kind":"COMPANY","displayName":"Books"}}'], remediation: "The command envelope must include a nonblank reason and explicit tenantId." },
  { id: "book-set.set-default", description: "Set a tenant's default BookSet through an audited command.", sideEffect: "write", requiredScope: "tenant", inputSchema: commandSchema(false), outputDescription: "Versioned default-change command result.", examples: ["{\"schemaVersion\":1,\"tenantId\":\"tenant-1\",\"requestId\":\"req-4\",\"actor\":{\"kind\":\"HUMAN\",\"id\":\"user-1\"},\"source\":\"CLI\",\"reason\":\"change default\",\"payload\":{\"bookSetId\":\"bookset-1\"}}"], remediation: "The BookSet must belong to the tenant." },
  { id: "book-set.archive", description: "Archive a BookSet through an audited command.", sideEffect: "write", requiredScope: "tenant", inputSchema: commandSchema(false), outputDescription: "Versioned archive command result.", examples: ["{\"schemaVersion\":1,\"tenantId\":\"tenant-1\",\"requestId\":\"req-5\",\"actor\":{\"kind\":\"HUMAN\",\"id\":\"user-1\"},\"source\":\"CLI\",\"reason\":\"close books\",\"payload\":{\"bookSetId\":\"bookset-1\"}}"], remediation: "The default active BookSet cannot be archived." },
  { id: "account.get", description: "Read an account under explicit tenant and BookSet scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "accountId"], { ...readScopeProperties, accountId: id }), outputDescription: "Account record.", examples: ['{"tenantId":"tenant-1","bookSetId":"bookset-1","accountId":"account-1"}'], remediation: "Cross-scope account access is rejected." },
  { id: "account.get-by-code", description: "Read an account by code under explicit scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "code"], { ...readScopeProperties, code: id }), outputDescription: "Account record or null when absent.", examples: ['{"tenantId":"tenant-1","bookSetId":"bookset-1","code":"1000"}'], remediation: "Use the exact tenantId and BookSet ID." },
  { id: "account.list", description: "List accounts in an explicit BookSet.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], readScopeProperties), outputDescription: "Account records.", examples: ['{"tenantId":"tenant-1","bookSetId":"bookset-1"}'], remediation: "Cross-scope access is rejected." },
  { id: "book-set.scope.resolve", description: "Resolve a BookSet only from an explicit tenant and optional explicit BookSet ID.", sideEffect: "read", requiredScope: "tenant", inputSchema: objectSchema(["tenantId"], { tenantId: id, bookSetId: id }), outputDescription: "Resolved BookSet record.", examples: ['{"tenantId":"tenant-1","bookSetId":"bookset-1"}'], remediation: "If no BookSet ID is supplied, resolution is allowed only when the tenant has one unambiguous default." },
  { id: "journal.post", description: "Post an audited, idempotent balanced journal.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned journal post result and result hash.", examples: ['{"schemaVersion":1,"tenantId":"tenant-1","bookSetId":"bookset-1","requestId":"req-journal-1","actor":{"kind":"AGENT","id":"agent-1"},"source":"MCP","reason":"record sale","payload":{"postingDate":"2026-01-01","lines":[]}}'], remediation: "Use explicit account IDs, positive minor units, and equal debit/credit totals." },
  { id: "ledger.trial-balance", description: "Read the Trial Balance as of an explicit date.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "asOfDate"], { ...readScopeProperties, asOfDate: date }), outputDescription: "Trial Balance report.", examples: ['{"tenantId":"tenant-1","bookSetId":"bookset-1","asOfDate":"2026-03-31"}'], remediation: "Use a valid ISO date and exact BookSet scope." },
  { id: "ledger.profit-and-loss", description: "Read Profit and Loss for an explicit date range.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "fromDate", "toDate"], { ...readScopeProperties, fromDate: date, toDate: date }), outputDescription: "Profit and Loss report.", examples: ['{"tenantId":"tenant-1","bookSetId":"bookset-1","fromDate":"2026-01-01","toDate":"2026-03-31"}'], remediation: "Use valid ISO dates and a range accepted by the report service." },
  { id: "ledger.balance-sheet", description: "Read the Balance Sheet as of an explicit date.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "asOfDate"], { ...readScopeProperties, asOfDate: date }), outputDescription: "Balance Sheet report.", examples: ['{"tenantId":"tenant-1","bookSetId":"bookset-1","asOfDate":"2026-03-31"}'], remediation: "Use a valid ISO date and exact BookSet scope." },
  { id: "party.create", description: "Create an audited party.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned party command result.", examples: [], remediation: "Use an explicit BookSet-scoped command envelope." },
  { id: "invoice.create", description: "Create an invoice draft through the audited sales boundary.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned invoice creation result.", examples: [], remediation: "Use explicit customer and revenue account IDs." },
  { id: "invoice.post", description: "Post an invoice and its journal through the audited sales boundary.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned invoice posting result.", examples: [], remediation: "The invoice and receivable account must belong to the same scope." },
  { id: "invoice.get", description: "Read one invoice in an explicit scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "invoiceId"], { ...readScopeProperties, invoiceId: id }), outputDescription: "Invoice view.", examples: [], remediation: "Cross-scope invoice access is rejected." },
  { id: "invoice.outstanding", description: "List outstanding invoices in an explicit scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], readScopeProperties), outputDescription: "Outstanding invoice views.", examples: [], remediation: "Provide explicit tenantId and bookSetId." },
  { id: "receipt.record", description: "Record an audited customer receipt and allocation.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned receipt result.", examples: [], remediation: "Receipt allocations must target eligible invoices in this scope." },
  { id: "bill.create", description: "Create a vendor bill draft through the audited purchase boundary.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned bill creation result.", examples: [], remediation: "Use explicit vendor and expense account IDs." },
  { id: "bill.post", description: "Post a vendor bill and its journal.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned bill posting result.", examples: [], remediation: "The bill and payable account must belong to the same scope." },
  { id: "bill.get", description: "Read one vendor bill in an explicit scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "billId"], { ...readScopeProperties, billId: id }), outputDescription: "Bill view.", examples: [], remediation: "Cross-scope bill access is rejected." },
  { id: "bill.outstanding", description: "List outstanding vendor bills in an explicit scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], readScopeProperties), outputDescription: "Outstanding bill views.", examples: [], remediation: "Provide explicit tenantId and bookSetId." },
  { id: "vendor-payment.record", description: "Record an audited vendor payment and allocation.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned vendor payment result.", examples: [], remediation: "Payment allocations must target eligible bills in this scope." },
  { id: "bank-statement.import", description: "Import a bank statement through the audited import boundary.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned bank statement import result.", examples: [], remediation: "Use a stable requestId and explicit bank account and statement identity." },
  { id: "bank-statement.get", description: "Read one bank statement in an explicit scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "statementId"], { ...readScopeProperties, statementId: id }), outputDescription: "Bank statement with lines.", examples: [], remediation: "Cross-scope statement access is rejected." },
  { id: "bank-statement.list", description: "List bank statements in an explicit scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], { ...readScopeProperties, statementId: id }), outputDescription: "Bank statement views.", examples: [], remediation: "Provide explicit tenantId and bookSetId." },
  { id: "bank-match.confirm", description: "Confirm an explicit bank reconciliation match.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned bank match result.", examples: [], remediation: "Candidates are non-mutating; confirmation must provide the exact statement line and journal entry." },
  { id: "bank-match.undo", description: "Undo an explicit bank reconciliation match.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned bank match undo result.", examples: [], remediation: "Provide the exact match or statement line and a reason when required." },
  { id: "bank-match.candidates", description: "List deterministic bank match candidates without mutation.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "statementLineId"], { ...readScopeProperties, statementLineId: id }), outputDescription: "Candidate journal entries.", examples: [], remediation: "Candidate generation never confirms a match." },
  { id: "bank-reconciliation.status", description: "Read bank reconciliation status for an explicit statement.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "statementId"], { ...readScopeProperties, statementId: id }), outputDescription: "Reconciliation status.", examples: [], remediation: "Provide an explicit statementId." },
  { id: "gst.registration.create", description: "Create an audited GST registration.", sideEffect: "write", requiredScope: "tenant", inputSchema: commandSchema(false), outputDescription: "Versioned GST registration result.", examples: [], remediation: "GSTIN and effective dates are validated by the domain service." },
  { id: "gst.registration.get", description: "Read a GST registration in an explicit tenant scope.", sideEffect: "read", requiredScope: "tenant", inputSchema: objectSchema(["tenantId", "registrationId"], { tenantId: id, registrationId: id }), outputDescription: "GST registration view.", examples: [], remediation: "The registration must belong to the tenant." },
  { id: "gst.registration.list", description: "List GST registrations for an explicit tenant.", sideEffect: "read", requiredScope: "tenant", inputSchema: objectSchema(["tenantId"], { tenantId: id, date }), outputDescription: "GST registration views.", examples: [], remediation: "Provide an explicit tenantId." },
  { id: "gst.party-profile.create", description: "Create an audited GST party profile.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned party GST profile result.", examples: [], remediation: "The party and GST profile must belong to the same tenant and BookSet." },
  { id: "gst.party-profile.list", description: "List GST profiles for an explicit party scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "partyId"], { ...readScopeProperties, partyId: id, date }), outputDescription: "Party GST profile views.", examples: [], remediation: "Cross-scope party access is rejected." },
  { id: "gst.register.sales", description: "Read the GST sales register for an explicit scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "gstin"], { ...readScopeProperties, gstin: id, fromDate: date, toDate: date }), outputDescription: "GST sales register rows.", examples: [], remediation: "Provide the exact registration GSTIN and optional valid date range." },
  { id: "gst.register.purchases", description: "Read the GST purchase register for an explicit scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "gstin"], { ...readScopeProperties, gstin: id, fromDate: date, toDate: date }), outputDescription: "GST purchase register rows.", examples: [], remediation: "Provide the exact registration GSTIN and optional valid date range." },
  { id: "tax.deductor-profile.create", description: "Create an effective-dated tenant deductor profile with masked identifiers.", sideEffect: "write", requiredScope: "tenant", inputSchema: commandSchema(false), outputDescription: "Masked deductor profile result.", examples: [], remediation: "Use public PAN/TAN syntax and explicit evidence for verified or rejected status." },
  { id: "tax.deductor-profile.list", description: "List effective-dated tenant deductor profiles with masked identifiers.", sideEffect: "read", requiredScope: "tenant", inputSchema: objectSchema(["tenantId"], { tenantId: id, date }), outputDescription: "Masked deductor profile views.", examples: [], remediation: "Provide an explicit tenantId and optional effective date." },
  { id: "tax.party-profile.create", description: "Create an effective-dated BookSet party tax profile.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Masked party tax profile result.", examples: [], remediation: "Profiles may not overlap for the same tenant, BookSet, and party." },
  { id: "tax.party-profile.list", description: "List effective-dated BookSet party tax profiles with masked identifiers.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "partyId"], { ...readScopeProperties, partyId: id, date }), outputDescription: "Masked party tax profile views.", examples: [], remediation: "Cross-tenant and cross-BookSet party access is rejected." },
  { id: "tax.rule-snapshot.create", description: "Create an immutable source-verified or reviewable TDS/TCS rule snapshot.", sideEffect: "write", requiredScope: "tenant", inputSchema: commandSchema(false), outputDescription: "Immutable rule snapshot identity and canonical hash.", examples: [], remediation: "Posting requires sourceVerified, effective CREDIT timing, and explicit caller facts." },
  { id: "tax.deposit", description: "Deposit and allocate posted TDS/TCS liabilities with challan evidence.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Audited deposit and allocation result.", examples: [], remediation: "Allocations must be within the exact liability scope and outstanding event amount." },
  { id: "tax.register.tds", description: "Read a deterministic TDS event register.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], readScopeProperties), outputDescription: "Stable TDS register rows with deposited and outstanding amounts.", examples: [], remediation: "Provide explicit tenant and BookSet IDs." },
  { id: "tax.register.tcs", description: "Read a deterministic TCS event register.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], readScopeProperties), outputDescription: "Stable TCS register rows with deposited and outstanding amounts.", examples: [], remediation: "Provide explicit tenant and BookSet IDs." },
  { id: "asset.register", description: "Register an immutable fixed asset with explicit book policy and acquisition evidence.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Audited fixed-asset registration result.", examples: [], remediation: "Linked bill lines must be posted asset-account lines; manual registration requires a posted acquisition journal and evidence." },
  { id: "asset.depreciation.preview", description: "Preview deterministic book depreciation for an explicit period.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Immutable preview run and calculation facts.", examples: [], remediation: "Supply an explicit period; no policy or tax rate is inferred." },
  { id: "asset.depreciation.post", description: "Post an immutable, balanced book depreciation run for an explicit period.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Audited depreciation run and journal result.", examples: [], remediation: "Overlapping or duplicate posted periods are rejected." },
  { id: "asset.tax-rule.create", description: "Store a source-verified effective-dated fixed-asset tax rule snapshot.", sideEffect: "write", requiredScope: "tenant", inputSchema: commandSchema(false), outputDescription: "Immutable tax rule snapshot result.", examples: [], remediation: "Provide official HTTPS source, law/rule version, block, rate, and half-rate facts." },
  { id: "asset.tax-block.register", description: "Register a fixed-asset tax block against a rule snapshot.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Tax block identity and opening WDV.", examples: [], remediation: "The rule snapshot block code must match the tax block." },
  { id: "asset.tax.compute", description: "Compute an immutable block-wise tax depreciation schedule without posting a book journal.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Tax-year block schedule with preserved calculation facts.", examples: [], remediation: "The effective source-verified rule must cover the explicit period." },
  { id: "asset.dispose", description: "Dispose a fixed asset with carrying amount, gain/loss journal, and evidence.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Audited disposal and balanced journal result.", examples: [], remediation: "Disposal is immutable and tax consideration remains a separate schedule fact." },
  { id: "asset.register.report", description: "Read the deterministic fixed-asset register.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], { ...readScopeProperties, asOfDate: date }), outputDescription: "Stable CSV-ready asset rows.", examples: [], remediation: "Provide explicit tenant and BookSet IDs." },
  { id: "asset.depreciation.report", description: "Read posted book depreciation rows for an explicit period.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "periodStart", "periodEnd"], { ...readScopeProperties, periodStart: date, periodEnd: date }), outputDescription: "Stable book depreciation schedule rows.", examples: [], remediation: "Provide an explicit period." },
  { id: "asset.tax.report", description: "Read a computed block-wise tax schedule for an explicit period.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "periodStart", "periodEnd"], { ...readScopeProperties, periodStart: date, periodEnd: date }), outputDescription: "Stable tax block schedule rows.", examples: [], remediation: "Compute the tax period before requesting the schedule." },
  { id: "asset.reconciliation.report", description: "Read deterministic book-versus-tax depreciation reconciliation rows.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "periodStart", "periodEnd"], { ...readScopeProperties, periodStart: date, periodEnd: date }), outputDescription: "Stable reconciliation rows.", examples: [], remediation: "Provide an explicit period." },
  { id: "currency.register", description: "Register an immutable tenant currency exponent.", sideEffect: "write", requiredScope: "tenant", inputSchema: commandSchema(false), outputDescription: "Currency definition result.", examples: [], remediation: "Use an uppercase three-letter code and exponent 0 through 6." },
  { id: "fx.rate.create", description: "Create a verified immutable purpose-specific FX rate snapshot.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Exact FX rate snapshot result.", examples: [], remediation: "Supply a decimal string, source, evidence, purpose, and effective date; numeric rates are rejected." },
  { id: "fx.exposure.report", description: "Read open foreign-currency exposure in original and base minor units.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], readScopeProperties), outputDescription: "Stable FX exposure rows.", examples: [], remediation: "Provide explicit tenant and BookSet IDs." },
  { id: "fx.revaluation-policy.create", description: "Register an immutable supported FX revaluation policy.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Revaluation policy result.", examples: [], remediation: "Use AS_11, IND_AS_21, or CUSTOM_SUPPORTED with explicit control accounts." },
  { id: "fx.revaluation.post", description: "Post a deterministic period-end FX revaluation run.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Posted revaluation run and journal.", examples: [], remediation: "Supply one verified PERIOD_END rate snapshot per currency." },
  { id: "fx.revaluation.reverse", description: "Reverse a posted FX revaluation exactly once.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Reversal journal result.", examples: [], remediation: "Supply the runId in the payload and its policyId." },
  { id: "company.status", description: "Read a bounded company health summary without mutation.", sideEffect: "read", requiredScope: "none", inputSchema: objectSchema([], companyStatusProperties), outputDescription: "Database compatibility, tenant identity, one or more BookSet summaries, prioritized issues, readiness state, and stable drill-down templates.", examples: ["{}", '{"tenantId":"tenant-1","asOfDate":"2026-03-31"}'], remediation: "Omit tenantId only when exactly one ACTIVE tenant exists. Omit bookSetId to receive separate summaries for every ACTIVE BookSet." },
  { id: "database.status", description: "Inspect database compatibility without mutation.", sideEffect: "read", requiredScope: "none", inputSchema: objectSchema(), outputDescription: "Compatibility status and required schema versions.", examples: ["{}"], remediation: "Use database.init for an empty database or database.upgrade with an explicit verified backup for an older database.", operatorOnly: true },
  { id: "database.init", description: "Explicitly initialize an empty SQLite database.", sideEffect: "write", requiredScope: "none", inputSchema: objectSchema(), outputDescription: "Initialization result and post-action compatibility status.", examples: ["{}"], remediation: "Initialization is an operator action and is never invoked by normal business commands.", operatorOnly: true },
  { id: "database.upgrade", description: "Explicitly upgrade SQLite with a verified backup destination.", sideEffect: "write", requiredScope: "none", inputSchema: objectSchema(["backupDestinationPath"], { backupDestinationPath: id }), outputDescription: "Upgrade result and post-action compatibility status.", examples: ['{"backupDestinationPath":"/tmp/agent-bahi-backup"}'], remediation: "Provide an absolute backup path and inspect status before retrying failures.", operatorOnly: true },
];

entries.push(
  { id: "expense.claimant.create", description: "Create a tenant and BookSet-scoped expense claimant.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Claimant identity and active status.", examples: [], remediation: "Use an optional same-scope payroll employee link; no employee portal is created." },
  { id: "expense.claimant.get", description: "Read one scoped expense claimant.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "claimantId"], { ...readScopeProperties, claimantId: id }), outputDescription: "Claimant record.", examples: [], remediation: "Provide explicit tenant and BookSet IDs." },
  { id: "expense.claimant.list", description: "List scoped expense claimants.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], readScopeProperties), outputDescription: "Claimant records.", examples: [], remediation: "Provide explicit tenant and BookSet IDs." },
  { id: "expense.claim.create", description: "Create a DRAFT immutable-line expense claim with explicit business and personal allocations.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Draft claim identity.", examples: [], remediation: "Missing evidence is visible and does not block submit, approval, or posting." },
  { id: "expense.claim.submit", description: "Validate and submit an expense claim for independent review.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Submitted claim and business total.", examples: [], remediation: "Account classes, amount conservation, and tenant+BookSet scope are checked." },
  { id: "expense.claim.review", description: "Approve or reject a submitted expense claim with an independent reviewer observation.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Reviewed claim state.", examples: [], remediation: "Mixed-use claims require explicit allocation-confirmation facts." },
  { id: "expense.claim.post", description: "Post an approved claim and optional scoped advance allocations to the ledger.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Posted journal and settlement state.", examples: [], remediation: "Only business share posts; zero business totals and over-allocation are rejected." },
  { id: "expense.claim.get", description: "Read one scoped expense claim with immutable lines and settlement totals.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "claimId"], { ...readScopeProperties, claimId: id }), outputDescription: "Claim and line view.", examples: [], remediation: "Provide explicit tenant and BookSet IDs." },
  { id: "expense.claim.list", description: "List scoped expense claims.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], readScopeProperties), outputDescription: "Claim views.", examples: [], remediation: "Provide explicit tenant and BookSet IDs." },
  { id: "expense.advance.issue", description: "Issue a scoped expense advance with explicit asset and bank accounts.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Open advance and issue journal.", examples: [], remediation: "Advance issue posts Dr advance asset and Cr bank/cash asset." },
  { id: "expense.advance.get", description: "Read one scoped advance and outstanding balance.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "advanceId"], { ...readScopeProperties, advanceId: id }), outputDescription: "Advance view.", examples: [], remediation: "Provide explicit tenant and BookSet IDs." },
  { id: "expense.advance.list", description: "List scoped expense advances.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], readScopeProperties), outputDescription: "Advance views.", examples: [], remediation: "Provide explicit tenant and BookSet IDs." },
  { id: "expense.advance.repay", description: "Record an explicit partial or full advance repayment.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Repayment journal and advance state.", examples: [], remediation: "Repayment cannot exceed the outstanding advance." },
  { id: "expense.reimbursement.record", description: "Record a partial or full reimbursement against a posted expense claim.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Reimbursement journal and claim state.", examples: [], remediation: "Reimbursement cannot exceed the outstanding business share." },
  { id: "expense.register", description: "Read the bounded expense register with personal shares and evidence exceptions.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], readScopeProperties), outputDescription: "Expense register rows.", examples: [], remediation: "No deductibility, ITC, TDS, or statutory due-date inference is performed." },
  { id: "expense.open-items", description: "Read open reimbursement payables and advances.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], readScopeProperties), outputDescription: "Open claim and advance items.", examples: [], remediation: "Use explicit tenant and BookSet IDs." },
  { id: "expense.evidence-exceptions", description: "Read visible missing, explanation-only, or invalid evidence exceptions.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], readScopeProperties), outputDescription: "Evidence exception rows.", examples: [], remediation: "Exceptions do not currently infer deductibility or ITC." },
  { id: "payroll.employee.create", description: "Create a scoped employee master record with masked statutory and bank identifiers.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Masked employee identity and verification facts.", examples: [], remediation: "Store evidence and verification status; no employee portal is created." },
  { id: "payroll.employee.get", description: "Read one scoped employee with masked sensitive identifiers.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "employeeId"], { ...readScopeProperties, employeeId: id }), outputDescription: "Masked employee record.", examples: [], remediation: "Use explicit tenant and BookSet scope." },
  { id: "payroll.employee.list", description: "List scoped employees with masked identifiers.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], readScopeProperties), outputDescription: "Masked employee records.", examples: [], remediation: "Use explicit tenant and BookSet scope." },
  { id: "payroll.employee-profile.create", description: "Create an immutable effective-dated tax or statutory employee profile.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Profile identity and canonical hash.", examples: [], remediation: "Overlapping effective ranges are rejected." },
  { id: "payroll.salary-structure.create", description: "Create a scoped salary structure.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Salary structure identity.", examples: [], remediation: "Create immutable effective-dated versions separately." },
  { id: "payroll.salary-version.create", description: "Create an effective-dated salary version and typed components.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Version and component identities.", examples: [], remediation: "Use fixed minor amounts or basis points of a named component; arbitrary expressions are unsupported." },
  { id: "payroll.rule-snapshot.create", description: "Create an immutable source-backed payroll rule snapshot.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Rule snapshot identity and canonical hash.", examples: [], remediation: "Unverified, stale, or applicability-unknown rules block payroll." },
  { id: "payroll.claim.create", description: "Create a pending employee tax claim with evidence.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Pending claim identity.", examples: [], remediation: "A pending claim blocks pay-run approval." },
  { id: "payroll.claim.review", description: "Approve or reject an employee claim with an observation.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Reviewed claim state.", examples: [], remediation: "Claim reviews are append-audited." },
  { id: "payroll.pay-run.prepare", description: "Calculate and freeze a rule-gated payroll pay run.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Prepared pay run with calculation hash.", examples: [], remediation: "Supply explicit payable-day facts, salary version IDs, and rule snapshot IDs." },
  { id: "payroll.pay-run.approve", description: "Approve a prepared payroll run after claim and rule gates.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Approved pay run.", examples: [], remediation: "Pending claims and unresolved rules block approval." },
  { id: "payroll.pay-run.post", description: "Post an immutable balanced payroll journal and payslips.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Posted journal and immutable payslip identities.", examples: [], remediation: "Payroll posts only from an approved frozen run." },
  { id: "payroll.register", description: "Read the deterministic payroll register.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], { ...readScopeProperties, periodStart: date, periodEnd: date }), outputDescription: "Payroll register rows.", examples: [], remediation: "Use explicit scope and optional period bounds." },
  { id: "payroll.payslip.list", description: "Read immutable payslip exports.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], { ...readScopeProperties, payRunId: id }), outputDescription: "Deterministic text and HTML payslip data.", examples: [], remediation: "PDF binary rendering is not claimed." },
  { id: "payroll.payment-batch.create", description: "Allocate posted employee net pay to an export-only payment batch.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Prepared payment batch total.", examples: [], remediation: "Partial payment is allowed; overpay is rejected." },
  { id: "payroll.bank-export.create", description: "Generate a deterministic generic NEFT CSV artifact without submitting payment.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "CSV artifact, hash, and submitted=false.", examples: [], remediation: "Bank account values are masked and export never marks submission." },
  { id: "payroll.remittance.create", description: "Create a statutory remittance record separate from filing/payment submission.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Prepared remittance record.", examples: [], remediation: "No government portal submission is performed." },
  { id: "payroll.remittance.update", description: "Advance a remittance state with separate acknowledgement evidence.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Remittance state and observation.", examples: [], remediation: "ACKNOWLEDGED requires acknowledgement evidence." },
);

export const OPERATION_CATALOG: readonly OperationCatalogEntry[] = entries;
export const BUSINESS_OPERATION_CATALOG = OPERATION_CATALOG.filter((entry) => !entry.operatorOnly);

export function findOperation(id: string, includeOperator = true): OperationCatalogEntry | undefined {
  return OPERATION_CATALOG.find((entry) => entry.id === id && (includeOperator || !entry.operatorOnly));
}
