import type { JsonSchema } from "./types.ts";

export type OperationSideEffect = "read" | "write";
export type RequiredScope = "none" | "tenant" | "bookSet";

export interface OperationCatalogEntry {
  readonly id: string;
  readonly description: string;
  readonly sideEffect: OperationSideEffect;
  readonly requiredScope: RequiredScope;
  readonly inputSchema: JsonSchema;
  readonly outputDescription: string;
  readonly examples: readonly string[];
  readonly remediation: string;
  readonly operatorOnly?: boolean;
}

const objectSchema = (required: readonly string[] = [], properties: Record<string, unknown> = {}): JsonSchema => ({
  type: "object",
  properties,
  required: [...required],
  additionalProperties: true,
});

const id = { type: "string", minLength: 1 };
const date = { type: "string", pattern: "^\\d{4}-\\d{2}-\\d{2}$" };
const envelopeProperties = {
  schemaVersion: { type: "number", const: 1 }, tenantId: id, requestId: id,
  actor: { type: "object", required: ["kind", "id"] }, source: { type: "string" },
  reason: { type: "string", minLength: 1 }, requestedAt: { type: "string" }, payload: { type: "object" },
};
const scopedEnvelopeProperties = { ...envelopeProperties, bookSetId: id };
const readScopeProperties = { tenantId: id, bookSetId: id };
const commandSchema = (bookSet: boolean, payloadRequired = true) => objectSchema(
  bookSet ? ["schemaVersion", "tenantId", "bookSetId", "requestId", "actor", "source", "reason", ...(payloadRequired ? ["payload"] : [])] : ["schemaVersion", "tenantId", "requestId", "actor", "source", "reason", ...(payloadRequired ? ["payload"] : [])],
  bookSet ? scopedEnvelopeProperties : envelopeProperties,
);

const entries: OperationCatalogEntry[] = [
  { id: "tenant.get", description: "Read one tenant by its explicit ID.", sideEffect: "read", requiredScope: "tenant", inputSchema: objectSchema(["tenantId"], { tenantId: id }), outputDescription: "Tenant record.", examples: ['{"tenantId":"tenant-1"}'], remediation: "Provide the exact tenantId; the transport never infers a tenant." },
  { id: "tenant.list-active", description: "List active tenants.", sideEffect: "read", requiredScope: "none", inputSchema: objectSchema(), outputDescription: "Active tenant records.", examples: ["{}"], remediation: "No database mutation is performed." },
  { id: "tenant.create", description: "Create a tenant and its audited default BookSet.", sideEffect: "write", requiredScope: "none", inputSchema: commandSchema(false), outputDescription: "Versioned command result with tenant and default BookSet IDs.", examples: ['{"schemaVersion":1,"tenantId":"tenant-new","requestId":"req-1","actor":{"kind":"HUMAN","id":"user-1"},"source":"CLI","reason":"setup","payload":{"kind":"COMPANY","name":"Acme"}}'], remediation: "Use a new requestId for new content; replaying the same requestId is idempotent." },
  { id: "tenant.activate", description: "Activate a tenant through its audited command boundary.", sideEffect: "write", requiredScope: "tenant", inputSchema: commandSchema(false), outputDescription: "Versioned activation command result.", examples: ["{\"schemaVersion\":1,\"tenantId\":\"tenant-1\",\"requestId\":\"req-2\",\"actor\":{\"kind\":\"HUMAN\",\"id\":\"user-1\"},\"source\":\"CLI\",\"reason\":\"activate\",\"payload\":{\"defaultBookSetId\":\"bookset-1\"}}"], remediation: "The defaultBookSetId must belong to the tenant." },
  { id: "book-set.get-default", description: "Read a tenant's default BookSet.", sideEffect: "read", requiredScope: "tenant", inputSchema: objectSchema(["tenantId"], { tenantId: id }), outputDescription: "Default BookSet record.", examples: ['{"tenantId":"tenant-1"}'], remediation: "Provide an explicit tenantId." },
  { id: "book-set.get", description: "Read a BookSet under an explicit tenant scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], readScopeProperties), outputDescription: "BookSet record.", examples: ['{"tenantId":"tenant-1","bookSetId":"bookset-1"}'], remediation: "Cross-tenant BookSet access is rejected." },
  { id: "book-set.list", description: "List BookSets owned by an explicit tenant.", sideEffect: "read", requiredScope: "tenant", inputSchema: objectSchema(["tenantId"], { tenantId: id }), outputDescription: "BookSet records.", examples: ['{"tenantId":"tenant-1"}'], remediation: "Provide an explicit tenantId." },
  { id: "book-set.create", description: "Create an audited BookSet.", sideEffect: "write", requiredScope: "tenant", inputSchema: commandSchema(false), outputDescription: "Versioned BookSet command result.", examples: ['{"schemaVersion":1,"tenantId":"tenant-1","requestId":"req-3","actor":{"kind":"HUMAN","id":"user-1"},"source":"CLI","reason":"setup","payload":{"kind":"COMPANY","displayName":"Books"}}'], remediation: "The command envelope must include a nonblank reason and explicit tenantId." },
  { id: "book-set.set-default", description: "Set a tenant's default BookSet through an audited command.", sideEffect: "write", requiredScope: "tenant", inputSchema: commandSchema(false), outputDescription: "Versioned default-change command result.", examples: ["{\"schemaVersion\":1,\"tenantId\":\"tenant-1\",\"requestId\":\"req-4\",\"actor\":{\"kind\":\"HUMAN\",\"id\":\"user-1\"},\"source\":\"CLI\",\"reason\":\"change default\",\"payload\":{\"bookSetId\":\"bookset-1\"}}"], remediation: "The BookSet must belong to the tenant." },
  { id: "book-set.archive", description: "Archive a BookSet through an audited command.", sideEffect: "write", requiredScope: "tenant", inputSchema: commandSchema(false), outputDescription: "Versioned archive command result.", examples: ["{\"schemaVersion\":1,\"tenantId\":\"tenant-1\",\"requestId\":\"req-5\",\"actor\":{\"kind\":\"HUMAN\",\"id\":\"user-1\"},\"source\":\"CLI\",\"reason\":\"close books\",\"payload\":{\"bookSetId\":\"bookset-1\"}}"], remediation: "The default active BookSet cannot be archived." },
  { id: "account.get", description: "Read an account under explicit tenant and BookSet scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "accountId"], { ...readScopeProperties, accountId: id }), outputDescription: "Account record.", examples: ['{"tenantId":"tenant-1","bookSetId":"bookset-1","accountId":"account-1"}'], remediation: "Cross-scope account access is rejected." },
  { id: "account.get-by-code", description: "Read an account by code under explicit scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "code"], { ...readScopeProperties, code: id }), outputDescription: "Account record or null when absent.", examples: ['{"tenantId":"tenant-1","bookSetId":"bookset-1","code":"1000"}'], remediation: "Use the exact tenantId and BookSet ID." },
  { id: "account.list", description: "List accounts in an explicit BookSet.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], readScopeProperties), outputDescription: "Account records.", examples: ['{"tenantId":"tenant-1","bookSetId":"bookset-1"}'], remediation: "Cross-scope access is rejected." },
  { id: "book-set.scope.resolve", description: "Resolve a BookSet only from an explicit tenant and optional explicit BookSet ID.", sideEffect: "read", requiredScope: "tenant", inputSchema: objectSchema(["tenantId"], { tenantId: id, bookSetId: id }), outputDescription: "Resolved BookSet record.", examples: ['{"tenantId":"tenant-1","bookSetId":"bookset-1"}'], remediation: "If no BookSet ID is supplied, resolution is allowed only when the tenant has one unambiguous default." },
  { id: "journal.post", description: "Post an audited, idempotent balanced journal.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned journal post result and result hash.", examples: ['{"schemaVersion":1,"tenantId":"tenant-1","bookSetId":"bookset-1","requestId":"req-journal-1","actor":{"kind":"AGENT","id":"agent-1"},"source":"MCP","reason":"record sale","payload":{"postingDate":"2026-01-01","lines":[]}}'], remediation: "Use explicit account IDs, positive minor units, and equal debit/credit totals." },
  { id: "ledger.trial-balance", description: "Read the Trial Balance as of an explicit date.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "asOfDate"], { ...readScopeProperties, asOfDate: date }), outputDescription: "Trial Balance report.", examples: ['{"tenantId":"tenant-1","bookSetId":"bookset-1","asOfDate":"2026-03-31"}'], remediation: "Use a valid ISO date and exact BookSet scope." },
  { id: "ledger.profit-and-loss", description: "Read Profit and Loss for an explicit date range.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "fromDate", "toDate"], { ...readScopeProperties, fromDate: date, toDate: date }), outputDescription: "Profit and Loss report.", examples: ['{"tenantId":"tenant-1","bookSetId":"bookset-1","fromDate":"2026-01-01","toDate":"2026-03-31"}'], remediation: "Use valid ISO dates and a range accepted by the report service." },
  { id: "ledger.balance-sheet", description: "Read the Balance Sheet as of an explicit date.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "asOfDate"], { ...readScopeProperties, asOfDate: date }), outputDescription: "Balance Sheet report.", examples: ['{"tenantId":"tenant-1","bookSetId":"bookset-1","asOfDate":"2026-03-31"}'], remediation: "Use a valid ISO date and exact BookSet scope." },
  { id: "party.create", description: "Create an audited party.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned party command result.", examples: [], remediation: "Use an explicit BookSet-scoped command envelope." },
  { id: "invoice.create", description: "Create an invoice draft through the audited sales boundary.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned invoice creation result.", examples: [], remediation: "Use explicit customer and revenue account IDs." },
  { id: "invoice.post", description: "Post an invoice and its journal through the audited sales boundary.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned invoice posting result.", examples: [], remediation: "The invoice and receivable account must belong to the same scope." },
  { id: "invoice.get", description: "Read one invoice in an explicit scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "invoiceId"], { ...readScopeProperties, invoiceId: id }), outputDescription: "Invoice view.", examples: [], remediation: "Cross-scope invoice access is rejected." },
  { id: "invoice.outstanding", description: "List outstanding invoices in an explicit scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], readScopeProperties), outputDescription: "Outstanding invoice views.", examples: [], remediation: "Provide explicit tenantId and bookSetId." },
  { id: "receipt.record", description: "Record an audited customer receipt and allocation.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned receipt result.", examples: [], remediation: "Receipt allocations must target eligible invoices in this scope." },
  { id: "bill.create", description: "Create a vendor bill draft through the audited purchase boundary.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned bill creation result.", examples: [], remediation: "Use explicit vendor and expense account IDs." },
  { id: "bill.post", description: "Post a vendor bill and its journal.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned bill posting result.", examples: [], remediation: "The bill and payable account must belong to the same scope." },
  { id: "bill.get", description: "Read one vendor bill in an explicit scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "billId"], { ...readScopeProperties, billId: id }), outputDescription: "Bill view.", examples: [], remediation: "Cross-scope bill access is rejected." },
  { id: "bill.outstanding", description: "List outstanding vendor bills in an explicit scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], readScopeProperties), outputDescription: "Outstanding bill views.", examples: [], remediation: "Provide explicit tenantId and bookSetId." },
  { id: "vendor-payment.record", description: "Record an audited vendor payment and allocation.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned vendor payment result.", examples: [], remediation: "Payment allocations must target eligible bills in this scope." },
  { id: "bank-statement.import", description: "Import a bank statement through the audited import boundary.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned bank statement import result.", examples: [], remediation: "Use a stable requestId and explicit bank account and statement identity." },
  { id: "bank-statement.get", description: "Read one bank statement in an explicit scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "statementId"], { ...readScopeProperties, statementId: id }), outputDescription: "Bank statement with lines.", examples: [], remediation: "Cross-scope statement access is rejected." },
  { id: "bank-statement.list", description: "List bank statements in an explicit scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId"], { ...readScopeProperties, statementId: id }), outputDescription: "Bank statement views.", examples: [], remediation: "Provide explicit tenantId and bookSetId." },
  { id: "bank-match.confirm", description: "Confirm an explicit bank reconciliation match.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned bank match result.", examples: [], remediation: "Candidates are non-mutating; confirmation must provide the exact statement line and journal entry." },
  { id: "bank-match.undo", description: "Undo an explicit bank reconciliation match.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned bank match undo result.", examples: [], remediation: "Provide the exact match or statement line and a reason when required." },
  { id: "bank-match.candidates", description: "List deterministic bank match candidates without mutation.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "statementLineId"], { ...readScopeProperties, statementLineId: id }), outputDescription: "Candidate journal entries.", examples: [], remediation: "Candidate generation never confirms a match." },
  { id: "bank-reconciliation.status", description: "Read bank reconciliation status for an explicit statement.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "statementId"], { ...readScopeProperties, statementId: id }), outputDescription: "Reconciliation status.", examples: [], remediation: "Provide an explicit statementId." },
  { id: "gst.registration.create", description: "Create an audited GST registration.", sideEffect: "write", requiredScope: "tenant", inputSchema: commandSchema(false), outputDescription: "Versioned GST registration result.", examples: [], remediation: "GSTIN and effective dates are validated by the domain service." },
  { id: "gst.registration.get", description: "Read a GST registration in an explicit tenant scope.", sideEffect: "read", requiredScope: "tenant", inputSchema: objectSchema(["tenantId", "registrationId"], { tenantId: id, registrationId: id }), outputDescription: "GST registration view.", examples: [], remediation: "The registration must belong to the tenant." },
  { id: "gst.registration.list", description: "List GST registrations for an explicit tenant.", sideEffect: "read", requiredScope: "tenant", inputSchema: objectSchema(["tenantId"], { tenantId: id, date }), outputDescription: "GST registration views.", examples: [], remediation: "Provide an explicit tenantId." },
  { id: "gst.party-profile.create", description: "Create an audited GST party profile.", sideEffect: "write", requiredScope: "bookSet", inputSchema: commandSchema(true), outputDescription: "Versioned party GST profile result.", examples: [], remediation: "The party and GST profile must belong to the same tenant and BookSet." },
  { id: "gst.party-profile.list", description: "List GST profiles for an explicit party scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "partyId"], { ...readScopeProperties, partyId: id, date }), outputDescription: "Party GST profile views.", examples: [], remediation: "Cross-scope party access is rejected." },
  { id: "gst.register.sales", description: "Read the GST sales register for an explicit scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "gstin"], { ...readScopeProperties, gstin: id, fromDate: date, toDate: date }), outputDescription: "GST sales register rows.", examples: [], remediation: "Provide the exact registration GSTIN and optional valid date range." },
  { id: "gst.register.purchases", description: "Read the GST purchase register for an explicit scope.", sideEffect: "read", requiredScope: "bookSet", inputSchema: objectSchema(["tenantId", "bookSetId", "gstin"], { ...readScopeProperties, gstin: id, fromDate: date, toDate: date }), outputDescription: "GST purchase register rows.", examples: [], remediation: "Provide the exact registration GSTIN and optional valid date range." },
  { id: "database.status", description: "Inspect database compatibility without mutation.", sideEffect: "read", requiredScope: "none", inputSchema: objectSchema(), outputDescription: "Compatibility status and required schema versions.", examples: ["{}"], remediation: "Use database.init for an empty database or database.upgrade with an explicit verified backup for an older database.", operatorOnly: true },
  { id: "database.init", description: "Explicitly initialize an empty SQLite database.", sideEffect: "write", requiredScope: "none", inputSchema: objectSchema(), outputDescription: "Initialization result and post-action compatibility status.", examples: ["{}"], remediation: "Initialization is an operator action and is never invoked by normal business commands.", operatorOnly: true },
  { id: "database.upgrade", description: "Explicitly upgrade SQLite with a verified backup destination.", sideEffect: "write", requiredScope: "none", inputSchema: objectSchema(["backupDestinationPath"], { backupDestinationPath: id }), outputDescription: "Upgrade result and post-action compatibility status.", examples: ['{"backupDestinationPath":"/tmp/agent-bahi-backup"}'], remediation: "Provide an absolute backup path and inspect status before retrying failures.", operatorOnly: true },
];

export const OPERATION_CATALOG: readonly OperationCatalogEntry[] = entries;
export const BUSINESS_OPERATION_CATALOG = OPERATION_CATALOG.filter((entry) => !entry.operatorOnly);

export function findOperation(id: string, includeOperator = true): OperationCatalogEntry | undefined {
  return OPERATION_CATALOG.find((entry) => entry.id === id && (includeOperator || !entry.operatorOnly));
}
